"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Calculator,Save} from "lucide-react";
import {loadVehicles} from "@/lib/vehicle-store";
import {loadSales} from "@/lib/sales-store";
import {loadVehicleExpenses} from "@/lib/ledger-store";
import {loadCostAnalyses,saveCostAnalyses,totalIndirectCost,VehicleCostAnalysis} from "@/lib/cost-analysis-store";
import {Currency,formatCurrency,normalizeCurrency} from "@/lib/currency";
import {saleProfitAnalysis,vehicleCostTotals} from "@/lib/financial-analysis";
export default function CostAnalysisPage(){
 const [vehicles,setVehicles]=useState<any[]>([]),[sales,setSales]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[analyses,setAnalyses]=useState<VehicleCostAnalysis[]>([]),[selected,setSelected]=useState("");
 useEffect(()=>{const v=loadVehicles();setVehicles(v);setSales(loadSales());setExpenses(loadVehicleExpenses());setAnalyses(loadCostAnalyses());if(v.length)setSelected(v[0].id)},[]);
 const rows=useMemo(()=>vehicles.map(v=>{const sale=sales.find(s=>s.vehicleId===v.id);const costs=vehicleCostTotals(v,expenses);const analysis=analyses.find(a=>a.vehicleId===v.id);const indirect=totalIndirectCost(analysis);const indirectCurrency=(analysis as any)?.currency as Currency|undefined;const result=sale?saleProfitAnalysis(sale,v,expenses):null;const comparable=!!result&&!result.mixed&&(!indirect||normalizeCurrency(indirectCurrency)===result.currency);const gross=comparable&&result?result.profit:0;const net=comparable?gross-indirect:0;return{v,sale,costs,analysis,indirect,indirectCurrency:normalizeCurrency(indirectCurrency),result,comparable,gross,net}}),[vehicles,sales,expenses,analyses]);
 const current=rows.find(r=>r.v.id===selected);
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);const item:any={vehicleId:selected,currency:String(f.get("currency")||"ZMW"),allocatedOverheads:Number(f.get("allocatedOverheads")||0),salesCommission:Number(f.get("salesCommission")||0),financeCharges:Number(f.get("financeCharges")||0),taxCost:Number(f.get("taxCost")||0),otherIndirectCosts:Number(f.get("otherIndirectCosts")||0),notes:String(f.get("notes")||""),updatedAt:new Date().toISOString()};const next=[item,...analyses.filter(x=>x.vehicleId!==selected)];saveCostAnalyses(next);setAnalyses(next)}
 const totals=(currency:Currency)=>rows.filter(r=>r.comparable&&r.result?.currency===currency).reduce((a,r)=>({gross:a.gross+r.gross,indirect:a.indirect+r.indirect,net:a.net+r.net}),{gross:0,indirect:0,net:0});const z=totals("ZMW"),u=totals("USD");
 return <><div className="topbar"><div className="title"><h1>Vehicle Cost Analysis</h1><p>Profit is calculated only where sale, direct costs and allocated indirect costs use one currency.</p></div></div>
 <div className="cards"><div className="card"><div className="metric-label">Comparable analyses</div><div className="metric-value">{rows.filter(r=>r.comparable).length}</div></div><div className="card"><div className="metric-label">Gross Profit</div><div className="metric-value small-money">{formatCurrency(z.gross,"ZMW")}</div><small>{formatCurrency(u.gross,"USD")}</small></div><div className="card"><div className="metric-label">Indirect Costs</div><div className="metric-value small-money">{formatCurrency(z.indirect,"ZMW")}</div><small>{formatCurrency(u.indirect,"USD")}</small></div><div className="card"><div className="metric-label">Net Profit/Loss</div><div className="metric-value small-money">{formatCurrency(z.net,"ZMW")}</div><small>{formatCurrency(u.net,"USD")}</small></div></div>
 <section className="form-card section-gap"><div className="field"><label>Select Vehicle</label><select className="select" value={selected} onChange={e=>setSelected(e.target.value)}>{vehicles.map(v=><option key={v.id} value={v.id}>{v.stockId} — {v.make} {v.model} {v.year}</option>)}</select></div></section>
 {current&&<><div className="deal-kpis"><div><span>Actual Sale</span><b>{current.sale?formatCurrency(current.sale.sellingPrice,normalizeCurrency(current.sale.currency)):"Not sold"}</b></div><div><span>Vehicle Costs</span><b>{formatCurrency(current.costs.ZMW,"ZMW")} · {formatCurrency(current.costs.USD,"USD")}</b></div><div><span>Gross Profit/Loss</span><b>{current.comparable&&current.result?formatCurrency(current.gross,current.result.currency):"Mixed currency — review"}</b></div><div><span>Net Profit/Loss</span><b>{current.comparable&&current.result?formatCurrency(current.net,current.result.currency):"Manual review required"}</b></div></div>
 <div className="grid-2"><form className="form-card" onSubmit={save}><h2>Indirect Cost Allocation</h2><div className="form-grid"><div className="field"><label>Currency</label><select className="select" name="currency" defaultValue={(current.analysis as any)?.currency||current.sale?.currency||"ZMW"}><option value="ZMW">ZMW</option><option value="USD">USD</option></select></div>{[["allocatedOverheads","Allocated operating overheads"],["salesCommission","Sales commission"],["financeCharges","Finance charges"],["taxCost","Taxes attributable to sale"],["otherIndirectCosts","Other indirect costs"]].map(([name,label])=><div className="field" key={name}><label>{label}</label><input className="input" type="number" min="0" step="0.01" name={name} defaultValue={(current.analysis as any)?.[name]||0}/></div>)}<div className="field full"><label>Notes</label><textarea className="textarea" name="notes" defaultValue={current.analysis?.notes||""}/></div></div><div className="actions"><button className="button"><Save size={17}/>Save Analysis</button></div></form>
 <section className="panel"><div className="panel-head"><h2>Profit Bridge</h2><Calculator size={20}/></div><div className="ledger-list"><div className="ledger-sale"><span>Actual Selling Price</span><b>{current.sale?formatCurrency(current.sale.sellingPrice,normalizeCurrency(current.sale.currency)):"Not sold"}</b></div><div className="ledger-row"><span><b>Costs in ZMW</b></span><b>{formatCurrency(current.costs.ZMW,"ZMW")}</b></div><div className="ledger-row"><span><b>Costs in USD</b></span><b>{formatCurrency(current.costs.USD,"USD")}</b></div><div className="ledger-row"><span><b>Allocated Indirect Costs</b></span><b>{formatCurrency(current.indirect,current.indirectCurrency)}</b></div><div className={current.comparable&&current.net>=0?"ledger-profit":"ledger-loss"}><span>NET PROFIT/LOSS</span><b>{current.comparable&&current.result?formatCurrency(current.net,current.result.currency):"Mixed currency — no automatic total"}</b></div></div><div className="panel-body"><Link className="button secondary" href={`/vehicles/${current.v.id}`}>Open Deal Jacket</Link></div></section></div></>}
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><h2>Vehicle Profitability Register</h2></div><div className="table-wrap"><table><thead><tr><th>Stock ID</th><th>Vehicle</th><th>Actual Sale</th><th>ZMW Costs</th><th>USD Costs</th><th>Profit Status</th><th>Net Profit/Loss</th></tr></thead><tbody>{rows.map(r=><tr key={r.v.id}><td><Link href={`/vehicles/${r.v.id}`}><b>{r.v.stockId}</b></Link></td><td>{r.v.make} {r.v.model} {r.v.year}</td><td>{r.sale?formatCurrency(r.sale.sellingPrice,normalizeCurrency(r.sale.currency)):"Not sold"}</td><td>{formatCurrency(r.costs.ZMW,"ZMW")}</td><td>{formatCurrency(r.costs.USD,"USD")}</td><td>{r.comparable?"Comparable":"Mixed currency — review"}</td><td className={r.comparable&&r.net<0?"loss":"profit"}><b>{r.comparable&&r.result?formatCurrency(r.net,r.result.currency):"—"}</b></td></tr>)}</tbody></table></div></section></>;
}
