"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Calculator,CheckCircle2,Save} from "lucide-react";
import {loadVehicles} from "@/lib/vehicle-store";
import {loadSales} from "@/lib/sales-store";
import {loadVehicleExpenses} from "@/lib/ledger-store";
import {loadCostAnalyses,saveCostAnalyses,totalIndirectCost,VehicleCostAnalysis} from "@/lib/cost-analysis-store";
import {formatCurrency} from "@/lib/currency";
import {saleProfitAnalysis,vehicleCostZmw} from "@/lib/financial-analysis";

export default function CostAnalysisPage(){
 const [vehicles,setVehicles]=useState<any[]>([]),[sales,setSales]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[analyses,setAnalyses]=useState<VehicleCostAnalysis[]>([]),[selected,setSelected]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{const v=loadVehicles();setVehicles(v);setSales(loadSales());setExpenses(loadVehicleExpenses());setAnalyses(loadCostAnalyses());if(v.length)setSelected(v[0].id)},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),2800);return()=>clearTimeout(timer)},[notice]);
 const rows=useMemo(()=>vehicles.map(v=>{const sale=sales.find(s=>s.vehicleId===v.id);const analysis=analyses.find(a=>a.vehicleId===v.id);const direct=vehicleCostZmw(v,expenses);const indirect=totalIndirectCost(analysis);const result=sale?saleProfitAnalysis(sale,v,expenses):null;const revenue=result?.revenue||0;const gross=result?.profit||0;const net=sale?gross-indirect:0;return{v,sale,analysis,direct,indirect,revenue,gross,net,status:sale?"Calculated":"Not Sold"}}),[vehicles,sales,expenses,analyses]);
 const current=rows.find(r=>r.v.id===selected);
 const totals=rows.filter(r=>r.sale).reduce((a,r)=>({revenue:a.revenue+r.revenue,direct:a.direct+r.direct,indirect:a.indirect+r.indirect,net:a.net+r.net}),{revenue:0,direct:0,indirect:0,net:0});
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);const item:VehicleCostAnalysis={vehicleId:selected,currency:"ZMW",allocatedOverheads:Number(f.get("allocatedOverheads")||0),salesCommission:Number(f.get("salesCommission")||0),financeCharges:Number(f.get("financeCharges")||0),taxCost:Number(f.get("taxCost")||0),otherIndirectCosts:Number(f.get("otherIndirectCosts")||0),notes:String(f.get("notes")||""),updatedAt:new Date().toISOString()};const next=[item,...analyses.filter(x=>x.vehicleId!==selected)];saveCostAnalyses(next);setAnalyses(next);setNotice("Cost analysis saved.")}
 return <>
  {notice&&<div className="app-toast"><CheckCircle2 size={17}/>{notice}</div>}
  <div className="page-heading"><div><span className="eyebrow dark">PROFITABILITY</span><h1>Vehicle Cost Analysis</h1><p>All profitability is calculated in Zambian Kwacha using the stored ZMW accounting value of each transaction.</p></div></div>
  <div className="cost-summary-grid"><section><span>Sold Vehicles</span><b>{rows.filter(r=>r.sale).length}</b><small>{vehicles.length} total vehicles</small></section><section><span>Accounting Revenue</span><b>{formatCurrency(totals.revenue,"ZMW")}</b></section><section><span>Total Costs</span><b>{formatCurrency(totals.direct+totals.indirect,"ZMW")}</b></section><section><span>Net Profit / Loss</span><b className={totals.net<0?"loss":"profit"}>{formatCurrency(totals.net,"ZMW")}</b></section></div>
  <section className="panel cost-vehicle-picker"><div className="panel-body"><div className="field"><label>Vehicle</label><select className="select" value={selected} onChange={e=>setSelected(e.target.value)}>{vehicles.map(v=><option key={v.id} value={v.id}>{v.stockId} — {v.make} {v.model} {v.year}</option>)}</select></div></div></section>
  {current&&<><div className="cost-current-grid"><section><span>Accounting Revenue</span><b>{current.sale?formatCurrency(current.revenue,"ZMW"):"Not sold"}</b>{current.sale?.currency==="USD"&&<small>Original sale: {current.sale.originalSellingPrice??current.sale.sellingPrice} USD</small>}</section><section><span>Direct Vehicle Cost</span><b>{formatCurrency(current.direct,"ZMW")}</b></section><section><span>Gross Profit / Loss</span><b className={current.gross<0?"loss":"profit"}>{current.sale?formatCurrency(current.gross,"ZMW"):"Not available"}</b></section><section><span>Net Profit / Loss</span><b className={current.net<0?"loss":"profit"}>{current.sale?formatCurrency(current.net,"ZMW"):"Not available"}</b></section></div>
  <div className="grid-2 cost-workspace"><form key={`${selected}-${current.analysis?.updatedAt||"new"}`} className="form-card professional-form" onSubmit={save}><div className="form-heading"><div><h2>Indirect Costs</h2><p>Allocate local costs attributable to this vehicle sale.</p></div></div><div className="form-grid">{[["allocatedOverheads","Operating overheads"],["salesCommission","Sales commission"],["financeCharges","Finance charges"],["taxCost","Tax attributable to sale"],["otherIndirectCosts","Other indirect costs"]].map(([name,label])=><div className="field" key={name}><label>{label} (ZMW)</label><input className="input" type="number" min="0" step="0.01" name={name} defaultValue={Number(current.analysis?.[name as keyof VehicleCostAnalysis]||0)}/></div>)}<div className="field full"><label>Notes</label><textarea className="textarea" name="notes" defaultValue={current.analysis?.notes||""} placeholder="Optional explanation or management note"/></div></div><div className="actions"><button className="button"><Save size={17}/>Save Analysis</button></div></form>
  <section className="panel cost-profit-bridge"><div className="panel-head"><h2>Profit Bridge</h2><Calculator size={19}/></div><div className="ledger-list"><div className="ledger-sale"><span>Accounting Sale Value</span><b>{current.sale?formatCurrency(current.revenue,"ZMW"):"Not sold"}</b></div><div className="ledger-row"><span>Direct Vehicle Costs</span><b>{formatCurrency(current.direct,"ZMW")}</b></div><div className="ledger-row"><span>Indirect Costs</span><b>{formatCurrency(current.indirect,"ZMW")}</b></div><div className={current.sale&&current.net>=0?"ledger-profit":"ledger-loss"}><span>Net Profit / Loss</span><b>{current.sale?formatCurrency(current.net,"ZMW"):"Not available"}</b></div></div><div className="panel-body"><Link className="button secondary" href={`/vehicles/${current.v.id}`}>Open Deal Jacket</Link></div></section></div></>}
  <section className="panel cost-register"><div className="panel-head"><h2>Vehicle Profitability Register</h2></div><div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Accounting Revenue</th><th>Direct Costs</th><th>Indirect Costs</th><th>Status</th><th>Net Profit / Loss</th></tr></thead><tbody>{rows.map(r=><tr key={r.v.id}><td><Link href={`/vehicles/${r.v.id}`}><b>{r.v.stockId}</b></Link><br/><small>{r.v.make} {r.v.model} {r.v.year}</small></td><td>{r.sale?formatCurrency(r.revenue,"ZMW"):"Not sold"}</td><td>{formatCurrency(r.direct,"ZMW")}</td><td>{formatCurrency(r.indirect,"ZMW")}</td><td><span className={`badge ${r.sale?"available":"transit"}`}>{r.status}</span></td><td className={r.sale&&r.net<0?"loss":"profit"}><b>{r.sale?formatCurrency(r.net,"ZMW"):"—"}</b></td></tr>)}</tbody></table></div></section>
 </>;
}
