"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Calculator,Save} from "lucide-react";
import {loadVehicles} from "@/lib/vehicle-store";
import {loadSales} from "@/lib/sales-store";
import {loadVehicleExpenses} from "@/lib/ledger-store";
import {loadCostAnalyses,saveCostAnalyses,totalIndirectCost,VehicleCostAnalysis} from "@/lib/cost-analysis-store";
const money=(n:number)=>new Intl.NumberFormat("en-ZM",{style:"currency",currency:"ZMW",maximumFractionDigits:0}).format(n);
export default function CostAnalysisPage(){
 const [vehicles,setVehicles]=useState<any[]>([]),[sales,setSales]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[analyses,setAnalyses]=useState<VehicleCostAnalysis[]>([]),[selected,setSelected]=useState("");
 useEffect(()=>{const v=loadVehicles();setVehicles(v);setSales(loadSales());setExpenses(loadVehicleExpenses());setAnalyses(loadCostAnalyses());if(v.length)setSelected(v[0].id)},[]);
 const rows=useMemo(()=>vehicles.map(v=>{const sale=sales.find(s=>s.vehicleId===v.id);const direct=expenses.filter(e=>e.vehicleId===v.id).reduce((a,e)=>a+Number(e.amount||0),0);const landed=Number(v.purchasePrice||0)+direct;const gross=sale?Number(sale.sellingPrice||0)-landed:0;const analysis=analyses.find(a=>a.vehicleId===v.id);const indirect=totalIndirectCost(analysis);return{v,sale,direct,landed,gross,indirect,net:sale?gross-indirect:0,analysis}}),[vehicles,sales,expenses,analyses]);
 const current=rows.find(r=>r.v.id===selected);
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);const item:VehicleCostAnalysis={vehicleId:selected,allocatedOverheads:Number(f.get("allocatedOverheads")||0),salesCommission:Number(f.get("salesCommission")||0),financeCharges:Number(f.get("financeCharges")||0),taxCost:Number(f.get("taxCost")||0),otherIndirectCosts:Number(f.get("otherIndirectCosts")||0),notes:String(f.get("notes")||""),updatedAt:new Date().toISOString()};const next=[item,...analyses.filter(x=>x.vehicleId!==selected)];saveCostAnalyses(next);setAnalyses(next)}
 return <><div className="topbar"><div className="title"><h1>Vehicle Cost Analysis</h1><p>Calculate the true net profit or loss for every vehicle sold.</p></div></div>
 <div className="cards"><div className="card"><div className="metric-label">Vehicles Analysed</div><div className="metric-value">{rows.filter(r=>r.analysis).length}</div></div><div className="card"><div className="metric-label">Total Gross Profit</div><div className="metric-value small-money">{money(rows.reduce((a,r)=>a+r.gross,0))}</div></div><div className="card"><div className="metric-label">Total Indirect Costs</div><div className="metric-value small-money">{money(rows.reduce((a,r)=>a+r.indirect,0))}</div></div><div className="card"><div className="metric-label">Total Net Profit/Loss</div><div className="metric-value small-money">{money(rows.reduce((a,r)=>a+r.net,0))}</div></div></div>
 <section className="form-card section-gap"><div className="field"><label>Select Vehicle</label><select className="select" value={selected} onChange={e=>setSelected(e.target.value)}>{vehicles.map(v=><option key={v.id} value={v.id}>{v.stockId} — {v.make} {v.model} {v.year}</option>)}</select></div></section>
 {current&&<><div className="deal-kpis"><div><span>Selling Price</span><b>{current.sale?money(current.sale.sellingPrice):"Not sold"}</b></div><div><span>Total Landed Cost</span><b>{money(current.landed)}</b></div><div className={current.gross>=0?"positive-card":"negative-card"}><span>Gross Profit/Loss</span><b>{current.sale?money(current.gross):"Pending sale"}</b></div><div className={current.net>=0?"positive-card":"negative-card"}><span>Net Profit/Loss</span><b>{current.sale?money(current.net):"Pending sale"}</b></div></div>
 <div className="grid-2"><form className="form-card" onSubmit={save}><h2>Indirect Cost Allocation</h2><div className="form-grid"><div className="field"><label>Allocated operating overheads</label><input className="input" type="number" min="0" step="0.01" name="allocatedOverheads" defaultValue={current.analysis?.allocatedOverheads||0}/></div><div className="field"><label>Sales commission</label><input className="input" type="number" min="0" step="0.01" name="salesCommission" defaultValue={current.analysis?.salesCommission||0}/></div><div className="field"><label>Finance charges</label><input className="input" type="number" min="0" step="0.01" name="financeCharges" defaultValue={current.analysis?.financeCharges||0}/></div><div className="field"><label>Taxes attributable to sale</label><input className="input" type="number" min="0" step="0.01" name="taxCost" defaultValue={current.analysis?.taxCost||0}/></div><div className="field"><label>Other indirect costs</label><input className="input" type="number" min="0" step="0.01" name="otherIndirectCosts" defaultValue={current.analysis?.otherIndirectCosts||0}/></div><div className="field full"><label>Notes</label><textarea className="textarea" name="notes" defaultValue={current.analysis?.notes||""}/></div></div><div className="actions"><button className="button"><Save size={17}/>Save Analysis</button></div></form>
 <section className="panel"><div className="panel-head"><h2>Profit Bridge</h2><Calculator size={20}/></div><div className="ledger-list"><div className="ledger-sale"><span>Selling Price</span><b>{current.sale?money(current.sale.sellingPrice):"Not sold"}</b></div><div className="ledger-row"><span><b>Purchase Price</b></span><b>({money(current.v.purchasePrice)})</b></div><div className="ledger-row"><span><b>Direct Vehicle Expenses</b></span><b>({money(current.direct)})</b></div><div className={current.gross>=0?"ledger-profit":"ledger-loss"}><span>Gross Profit/Loss</span><b>{money(current.gross)}</b></div><div className="ledger-row"><span><b>Allocated Indirect Costs</b></span><b>({money(current.indirect)})</b></div><div className={current.net>=0?"ledger-profit":"ledger-loss"}><span>NET PROFIT/LOSS</span><b>{money(current.net)}</b></div></div><div className="panel-body"><Link className="button secondary" href={`/vehicles/${current.v.id}`}>Open Deal Jacket</Link></div></section></div></>}
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><h2>Vehicle Profitability Register</h2></div><div className="table-wrap"><table><thead><tr><th>Stock ID</th><th>Vehicle</th><th>Selling Price</th><th>Landed Cost</th><th>Gross Profit/Loss</th><th>Indirect Costs</th><th>Net Profit/Loss</th></tr></thead><tbody>{rows.map(r=><tr key={r.v.id}><td><Link href={`/vehicles/${r.v.id}`}><b>{r.v.stockId}</b></Link></td><td>{r.v.make} {r.v.model} {r.v.year}</td><td>{r.sale?money(r.sale.sellingPrice):"Not sold"}</td><td>{money(r.landed)}</td><td className={r.gross>=0?"profit":"loss"}>{r.sale?money(r.gross):"—"}</td><td>{money(r.indirect)}</td><td className={r.net>=0?"profit":"loss"}><b>{r.sale?money(r.net):"—"}</b></td></tr>)}</tbody></table></div></section></>;
}
