"use client";
import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,Plus,Receipt,Route,Wallet,X} from "lucide-react";
import {CollectionTrip,Driver,loadDrivers,loadTrips,nextTripId,saveDrivers,saveTrips,tripSpent} from "@/lib/operations-store";
import {loadVehicles,saveVehicles} from "@/lib/vehicle-store";
import {formatZmw} from "@/lib/currency";
import {Vehicle} from "@/lib/types";
const emptyForm={vehicleStockId:"",driverId:"",collectionPoint:"",destination:"Covenant Motors Yard",departureDate:"",expectedArrival:"",advance:0};
const emptyExpense={category:"Fuel",amount:0,date:"",note:""};
export default function TripsPage(){
 const [trips,setTrips]=useState<CollectionTrip[]>([]),[drivers,setDrivers]=useState<Driver[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[open,setOpen]=useState(false),[expenseTrip,setExpenseTrip]=useState<string|null>(null),[form,setForm]=useState(emptyForm),[expense,setExpense]=useState(emptyExpense);
 useEffect(()=>{setTrips(loadTrips());setDrivers(loadDrivers());setVehicles(loadVehicles())},[]);
 const persistTrips=(next:CollectionTrip[])=>{setTrips(next);saveTrips(next)},persistVehicles=(next:Vehicle[])=>{setVehicles(next);saveVehicles(next)};
 const activeVehicleIds=new Set(trips.filter(t=>t.status!=="Reconciled").map(t=>t.vehicleStockId));
 const eligibleVehicles=vehicles.filter(v=>v.status!=="Sold"&&!activeVehicleIds.has(v.stockId));
 function closeTripForm(){setOpen(false);setForm(emptyForm)}
 function assign(){const d=drivers.find(x=>x.id===form.driverId),v=vehicles.find(x=>x.stockId===form.vehicleStockId);if(!d||!v||!form.departureDate)return alert("Select a vehicle, driver and departure date.");if(activeVehicleIds.has(v.stockId))return alert("This vehicle already has an active collection trip.");const advance=Number(form.advance||0),t:CollectionTrip={id:crypto.randomUUID(),tripId:nextTripId(trips),vehicleStockId:v.stockId,vehicleName:`${v.make} ${v.model} ${v.year}`,driverId:d.id,driverName:d.name,collectionPoint:form.collectionPoint||v.currentLocation,destination:form.destination,departureDate:form.departureDate,expectedArrival:form.expectedArrival,advance,advanceCurrency:"ZMW",advanceExchangeRate:1,originalAdvance:advance,advanceZmw:advance,status:"Assigned",expenses:[]};persistTrips([...trips,t]);const nd=drivers.map(x=>x.id===d.id?{...x,status:"On Trip" as const}:x);setDrivers(nd);saveDrivers(nd);persistVehicles(vehicles.map(x=>x.id===v.id?{...x,status:"Awaiting Collection" as const}:x));closeTripForm()}
 function addExpense(tripId:string){if(!expense.amount||!expense.date)return alert("Enter expense amount and date.");const amount=Number(expense.amount);persistTrips(trips.map(t=>t.id===tripId?{...t,expenses:[...t.expenses,{id:crypto.randomUUID(),category:expense.category,amount,currency:"ZMW",exchangeRate:1,originalAmount:amount,amountZmw:amount,date:expense.date,note:expense.note}]}:t));setExpense(emptyExpense);setExpenseTrip(null)}
 function changeStatus(trip:CollectionTrip,status:CollectionTrip["status"]){if(status==="Reconciled"&&!confirm("Reconcile this trip and close it?"))return;persistTrips(trips.map(t=>t.id===trip.id?{...t,status}:t));if(status==="In Transit")persistVehicles(vehicles.map(v=>v.stockId===trip.vehicleStockId?{...v,status:"In Transit" as const}:v));if(status==="Arrived"||status==="Reconciled")persistVehicles(vehicles.map(v=>v.stockId===trip.vehicleStockId?{...v,status:"Available" as const,currentLocation:trip.destination}:v));if(status==="Reconciled"){const nd=drivers.map(d=>d.id===trip.driverId?{...d,status:"Available" as const}:d);setDrivers(nd);saveDrivers(nd)}}
 const totals=useMemo(()=>({active:trips.filter(t=>t.status!=="Reconciled").length,advance:trips.reduce((s,t)=>s+Number(t.advance||0),0),spent:trips.reduce((s,t)=>s+tripSpent(t),0)}),[trips]);
 return <><div className="topbar"><div className="title"><h1>Collection Trips</h1><p>Assign drivers, record local trip expenses and reconcile collections in Zambian Kwacha.</p></div><button className="button" onClick={()=>open?closeTripForm():setOpen(true)}><Plus size={18}/><span>{open?"Close Form":"Assign Trip"}</span></button></div><div className="cards trip-cards"><div className="card"><div className="metric"><div><div className="metric-label">Active Trips</div><div className="metric-value">{totals.active}</div></div><div className="metric-icon"><Route/></div></div></div><div className="card"><div className="metric"><div><div className="metric-label">Advances Issued</div><div className="metric-value small-value">{formatZmw(totals.advance)}</div></div><div className="metric-icon"><Wallet/></div></div></div><div className="card"><div className="metric"><div><div className="metric-label">Recorded Expenses</div><div className="metric-value small-value">{formatZmw(totals.spent)}</div></div><div className="metric-icon"><Receipt/></div></div></div></div>
 {open&&<div className="form-card section-gap"><div className="form-heading"><h2>Assign Vehicle Collection Trip</h2><button className="icon-button" type="button" onClick={closeTripForm}><X size={18}/></button></div><div className="form-grid"><div className="field"><label>Vehicle</label><select className="select" value={form.vehicleStockId} onChange={e=>setForm({...form,vehicleStockId:e.target.value})}><option value="">Select vehicle</option>{eligibleVehicles.map(v=><option key={v.id} value={v.stockId}>{v.stockId} — {v.make} {v.model}</option>)}</select></div><div className="field"><label>Driver</label><select className="select" value={form.driverId} onChange={e=>setForm({...form,driverId:e.target.value})}><option value="">Select available driver</option>{drivers.filter(d=>d.status==="Available").map(d=><option key={d.id} value={d.id}>{d.driverId} — {d.name}</option>)}</select></div><div className="field"><label>Collection Point</label><input className="input" value={form.collectionPoint} onChange={e=>setForm({...form,collectionPoint:e.target.value})}/></div><div className="field"><label>Destination</label><input className="input" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/></div><div className="field"><label>Departure Date</label><input className="input" type="date" value={form.departureDate} onChange={e=>setForm({...form,departureDate:e.target.value})}/></div><div className="field"><label>Expected Arrival</label><input className="input" type="date" value={form.expectedArrival} onChange={e=>setForm({...form,expectedArrival:e.target.value})}/></div><div className="field"><label>Driver Advance (ZMW)</label><input className="input" type="number" min="0" step="0.01" value={form.advance||""} onChange={e=>setForm({...form,advance:Number(e.target.value)})}/></div></div><div className="actions"><button className="button secondary" type="button" onClick={closeTripForm}>Cancel</button><button className="button" type="button" onClick={assign}>Create Trip</button></div></div>}
 <div className="trip-list">{trips.map(t=>{const spent=tripSpent(t),balance=Number(t.advance||0)-spent;return <div className="panel trip-panel" key={t.id}><div className="panel-head"><div><h2>{t.tripId} · {t.vehicleStockId}</h2><span className="muted">{t.vehicleName}</span></div><span className={`badge ${t.status==="Reconciled"?"available":t.status==="Arrived"?"awaiting":"transit"}`}>{t.status}</span></div><div className="panel-body"><div className="trip-route"><div><small>Driver</small><b>{t.driverName}</b></div><div><small>Route</small><b>{t.collectionPoint} → {t.destination}</b></div><div><small>Departure</small><b>{t.departureDate}</b></div></div><div className="reconcile-grid"><div><span>Advance</span><b>{formatZmw(Number(t.advance||0))}</b></div><div><span>Expenses</span><b>{formatZmw(spent)}</b></div><div className={balance<0?"negative":"positive"}><span>{balance>=0?"Driver Refund":"Owed to Driver"}</span><b>{formatZmw(Math.abs(balance))}</b></div></div>{t.expenses.length>0&&<div className="expense-list">{t.expenses.map(e=><div key={e.id}><span>{e.category}<small>{e.date} · {e.note||"No note"}</small></span><b>{formatZmw(Number(e.amountZmw??e.amount))}</b></div>)}</div>}{expenseTrip===t.id?<div className="expense-form"><select className="select" value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}>{["Fuel","Accommodation","Meals","Tolls","Permit","Repairs","Driver Allowance","Other"].map(x=><option key={x}>{x}</option>)}</select><input className="input" type="number" min="0.01" step="0.01" placeholder="Amount (ZMW)" value={expense.amount||""} onChange={e=>setExpense({...expense,amount:Number(e.target.value)})}/><input className="input" type="date" value={expense.date} onChange={e=>setExpense({...expense,date:e.target.value})}/><input className="input" placeholder="Note" value={expense.note} onChange={e=>setExpense({...expense,note:e.target.value})}/><button className="button secondary" type="button" onClick={()=>{setExpenseTrip(null);setExpense(emptyExpense)}}>Cancel</button><button className="button" type="button" onClick={()=>addExpense(t.id)}>Save Expense</button></div>:<div className="trip-actions">{t.status!=="Reconciled"&&<button className="button secondary" type="button" onClick={()=>setExpenseTrip(t.id)}>Add Expense</button>}{t.status==="Assigned"&&<button className="button secondary" type="button" onClick={()=>changeStatus(t,"In Transit")}>Start Trip</button>}{t.status==="In Transit"&&<button className="button secondary" type="button" onClick={()=>changeStatus(t,"Arrived")}>Mark Arrived</button>}{t.status==="Arrived"&&<button className="button" type="button" onClick={()=>changeStatus(t,"Reconciled")}><CheckCircle2 size={17}/>Reconcile</button>}</div>}</div></div>})}</div></>;
}
