"use client";
import {useEffect,useMemo,useState} from "react";
import {Plus,Route,Wallet,Receipt,CheckCircle2} from "lucide-react";
import {CollectionTrip,Driver,loadDrivers,loadTrips,nextTripId,saveDrivers,saveTrips,tripSpent} from "@/lib/operations-store";
import {loadVehicles} from "@/lib/vehicle-store";
import {Currency,formatCurrency,formatZmw,toZmw} from "@/lib/currency";
export default function TripsPage(){
 const [trips,setTrips]=useState<CollectionTrip[]>([]),[drivers,setDrivers]=useState<Driver[]>([]),[vehicles,setVehicles]=useState<any[]>([]),[open,setOpen]=useState(false),[expenseTrip,setExpenseTrip]=useState<string|null>(null);
 const [form,setForm]=useState({vehicleStockId:"",driverId:"",collectionPoint:"Nakonde Border",destination:"Covenant Motors Yard",departureDate:"",expectedArrival:"",advance:0,advanceCurrency:"ZMW" as Currency,advanceExchangeRate:1});
 const [expense,setExpense]=useState({category:"Fuel",amount:0,currency:"ZMW" as Currency,exchangeRate:1,date:"",note:""});
 useEffect(()=>{setTrips(loadTrips());setDrivers(loadDrivers());setVehicles(loadVehicles())},[]);const persistTrips=(next:CollectionTrip[])=>{setTrips(next);saveTrips(next)};
 const assign=()=>{const d=drivers.find(x=>x.id===form.driverId),v=vehicles.find(x=>x.stockId===form.vehicleStockId);if(!d||!v||!form.departureDate)return alert("Select a vehicle, driver and departure date.");if(form.advanceCurrency==="USD"&&form.advanceExchangeRate<=0)return alert("Enter the USD to ZMW exchange rate.");const advance=toZmw(form.advance,form.advanceCurrency,form.advanceExchangeRate);const t:CollectionTrip={id:crypto.randomUUID(),tripId:nextTripId(trips),vehicleStockId:v.stockId,vehicleName:`${v.make} ${v.model} ${v.year}`,driverId:d.id,driverName:d.name,collectionPoint:form.collectionPoint,destination:form.destination,departureDate:form.departureDate,expectedArrival:form.expectedArrival,advance,advanceCurrency:form.advanceCurrency,advanceExchangeRate:form.advanceExchangeRate,originalAdvance:form.advance,advanceZmw:advance,status:"Assigned",expenses:[]};persistTrips([...trips,t]);const nd=drivers.map(x=>x.id===d.id?{...x,status:"On Trip" as const}:x);setDrivers(nd);saveDrivers(nd);setOpen(false)};
 const addExpense=(tripId:string)=>{if(!expense.amount||!expense.date)return alert("Enter expense amount and date.");if(expense.currency==="USD"&&expense.exchangeRate<=0)return alert("Enter the USD to ZMW exchange rate.");const amount=toZmw(expense.amount,expense.currency,expense.exchangeRate);persistTrips(trips.map(t=>t.id===tripId?{...t,expenses:[...t.expenses,{id:crypto.randomUUID(),category:expense.category,amount,currency:expense.currency,exchangeRate:expense.exchangeRate,originalAmount:expense.amount,amountZmw:amount,date:expense.date,note:expense.note}]}:t));setExpense({category:"Fuel",amount:0,currency:"ZMW",exchangeRate:1,date:"",note:""});setExpenseTrip(null)};
 const setStatus=(trip:CollectionTrip,status:CollectionTrip["status"])=>{persistTrips(trips.map(t=>t.id===trip.id?{...t,status}:t));if(status==="Reconciled"){const nd=drivers.map(d=>d.id===trip.driverId?{...d,status:"Available" as const}:d);setDrivers(nd);saveDrivers(nd)}};
 const totals=useMemo(()=>({active:trips.filter(t=>t.status!=="Reconciled").length,advance:trips.reduce((s,t)=>s+t.advance,0),spent:trips.reduce((s,t)=>s+tripSpent(t),0)}),[trips]);
 return <><div className="topbar"><div className="title"><h1>Collection Trips</h1><p>Assign drivers, control advances and reconcile costs in ZMW or USD.</p></div><button className="button" onClick={()=>setOpen(!open)}><Plus size={18}/><span>Assign Trip</span></button></div>
 <div className="cards trip-cards"><div className="card"><div className="metric"><div><div className="metric-label">Active Trips</div><div className="metric-value">{totals.active}</div></div><div className="metric-icon"><Route/></div></div></div><div className="card"><div className="metric"><div><div className="metric-label">Advances Issued (ZMW)</div><div className="metric-value small-value">{formatZmw(totals.advance)}</div></div><div className="metric-icon"><Wallet/></div></div></div><div className="card"><div className="metric"><div><div className="metric-label">Recorded Expenses (ZMW)</div><div className="metric-value small-value">{formatZmw(totals.spent)}</div></div><div className="metric-icon"><Receipt/></div></div></div></div>
 {open&&<div className="form-card section-gap"><h2>Assign Vehicle Collection Trip</h2><div className="form-grid"><div className="field"><label>Vehicle</label><select className="select" value={form.vehicleStockId} onChange={e=>setForm({...form,vehicleStockId:e.target.value})}><option value="">Select vehicle</option>{vehicles.filter(v=>v.status!=="Sold").map(v=><option key={v.id} value={v.stockId}>{v.stockId} — {v.make} {v.model}</option>)}</select></div><div className="field"><label>Driver</label><select className="select" value={form.driverId} onChange={e=>setForm({...form,driverId:e.target.value})}><option value="">Select available driver</option>{drivers.filter(d=>d.status==="Available").map(d=><option key={d.id} value={d.id}>{d.driverId} — {d.name}</option>)}</select></div><div className="field"><label>Collection point</label><input className="input" value={form.collectionPoint} onChange={e=>setForm({...form,collectionPoint:e.target.value})}/></div><div className="field"><label>Destination</label><input className="input" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/></div><div className="field"><label>Departure date</label><input className="input" type="date" value={form.departureDate} onChange={e=>setForm({...form,departureDate:e.target.value})}/></div><div className="field"><label>Expected arrival</label><input className="input" type="date" value={form.expectedArrival} onChange={e=>setForm({...form,expectedArrival:e.target.value})}/></div><div className="field"><label>Advance Currency</label><select className="select" value={form.advanceCurrency} onChange={e=>setForm({...form,advanceCurrency:e.target.value as Currency})}><option value="ZMW">ZMW</option><option value="USD">USD</option></select></div><div className="field"><label>Driver Advance</label><input className="input" type="number" min="0" step="0.01" value={form.advance||""} onChange={e=>setForm({...form,advance:Number(e.target.value)})}/></div>{form.advanceCurrency==="USD"&&<div className="field"><label>USD to ZMW Rate</label><input className="input" type="number" min="0.0001" step="0.0001" value={form.advanceExchangeRate||""} onChange={e=>setForm({...form,advanceExchangeRate:Number(e.target.value)})}/></div>}</div><div className="actions"><button className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button" onClick={assign}>Create Trip</button></div></div>}
 <div className="trip-list">{trips.map(t=>{const spent=tripSpent(t),balance=t.advance-spent;return <div className="panel trip-panel" key={t.id}><div className="panel-head"><div><h2>{t.tripId} · {t.vehicleStockId}</h2><span className="muted">{t.vehicleName}</span></div><span className={`badge ${t.status==="Reconciled"?"available":t.status==="Arrived"?"awaiting":"transit"}`}>{t.status}</span></div><div className="panel-body"><div className="trip-route"><div><small>Driver</small><b>{t.driverName}</b></div><div><small>Route</small><b>{t.collectionPoint} → {t.destination}</b></div><div><small>Departure</small><b>{t.departureDate}</b></div></div><div className="reconcile-grid"><div><span>Advance</span><b>{formatZmw(t.advance)}</b><small>{formatCurrency(t.originalAdvance??t.advance,t.advanceCurrency||"ZMW")}</small></div><div><span>Expenses</span><b>{formatZmw(spent)}</b></div><div className={balance<0?"negative":"positive"}><span>{balance>=0?"Driver refunds":"Owed to driver"}</span><b>{formatZmw(Math.abs(balance))}</b></div></div>{t.expenses.length>0&&<div className="expense-list">{t.expenses.map(e=><div key={e.id}><span>{e.category}<small>{e.date} · {e.note} · {formatCurrency(e.originalAmount??e.amount,e.currency||"ZMW")}</small></span><b>{formatZmw(e.amount)}</b></div>)}</div>}
 {expenseTrip===t.id?<div className="expense-form"><select className="select" value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}>{["Fuel","Accommodation","Meals","Tolls","Permit","Repairs","Driver Allowance","Other"].map(x=><option key={x}>{x}</option>)}</select><select className="select" value={expense.currency} onChange={e=>setExpense({...expense,currency:e.target.value as Currency})}><option value="ZMW">ZMW</option><option value="USD">USD</option></select><input className="input" type="number" placeholder="Amount" value={expense.amount||""} onChange={e=>setExpense({...expense,amount:Number(e.target.value)})}/>{expense.currency==="USD"&&<input className="input" type="number" placeholder="Exchange rate" value={expense.exchangeRate||""} onChange={e=>setExpense({...expense,exchangeRate:Number(e.target.value)})}/>}<input className="input" type="date" value={expense.date} onChange={e=>setExpense({...expense,date:e.target.value})}/><input className="input" placeholder="Note" value={expense.note} onChange={e=>setExpense({...expense,note:e.target.value})}/><button className="button" onClick={()=>addExpense(t.id)}>Save Expense</button></div>:<div className="trip-actions"><button className="button secondary" onClick={()=>setExpenseTrip(t.id)}>+ Expense</button>{t.status==="Assigned"&&<button className="button secondary" onClick={()=>setStatus(t,"In Transit")}>Start Trip</button>}{t.status==="In Transit"&&<button className="button secondary" onClick={()=>setStatus(t,"Arrived")}>Mark Arrived</button>}{t.status==="Arrived"&&<button className="button" onClick={()=>setStatus(t,"Reconciled")}><CheckCircle2 size={17}/>Reconcile</button>}</div>}</div></div>})}</div></>;
}
