"use client";
import {FormEvent,useEffect,useState} from "react";
import {Banknote,Building2,Plus,Receipt,WalletCards} from "lucide-react";
import {accountBalance,Account,FinanceEntry,loadAccounts,loadFinanceEntries,saveAccounts,saveFinanceEntries} from "@/lib/finance-store";
import {loadSales,Sale,saveSales} from "@/lib/sales-store";
import {loadTrips,tripSpent,CollectionTrip} from "@/lib/operations-store";
import {loadVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
const money=(n:number)=>new Intl.NumberFormat("en-ZM",{style:"currency",currency:"ZMW",maximumFractionDigits:0}).format(n);
type Tab="cashbook"|"customers"|"suppliers"|"advances"|"accounts";
type CashRow=FinanceEntry&{balance:number};
export default function FinancePage(){
 const [accounts,setAccounts]=useState<Account[]>([]);const [entries,setEntries]=useState<FinanceEntry[]>([]);const [sales,setSales]=useState<Sale[]>([]);const [trips,setTrips]=useState<CollectionTrip[]>([]);const [vehicles,setVehicles]=useState<Vehicle[]>([]);const [tab,setTab]=useState<Tab>("cashbook");const [showEntry,setShowEntry]=useState(false);const [showAccount,setShowAccount]=useState(false);
 useEffect(()=>{setAccounts(loadAccounts());setEntries(loadFinanceEntries());setSales(loadSales());setTrips(loadTrips());setVehicles(loadVehicles())},[]);
 const cash=accounts.reduce((sum,a)=>sum+accountBalance(a,entries),0);
 const receivables=sales.reduce((sum,s)=>sum+s.balance,0);
 const supplierPaid=(vehicleId:string)=>entries.filter(e=>e.type==="Supplier Payment"&&e.relatedId===vehicleId).reduce((sum,e)=>sum+e.moneyOut,0);
 const payables=vehicles.reduce((sum,v)=>sum+Math.max(0,v.purchasePrice-supplierPaid(v.id)),0);
 const advances=trips.filter(t=>t.status!=="Reconciled").reduce((sum,t)=>sum+Math.max(0,t.advance-tripSpent(t)),0);
 function addEntry(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const type=String(f.get("type")) as FinanceEntry["type"];const amount=Number(f.get("amount"));const relatedId=String(f.get("relatedId")||"");if(amount<=0)return;const incoming=type==="Customer Payment"||type==="Capital"||type==="Other Income";const item:FinanceEntry={id:crypto.randomUUID(),date:String(f.get("date")),type,reference:String(f.get("reference")||""),description:String(f.get("description")),accountId:String(f.get("accountId")),moneyIn:incoming?amount:0,moneyOut:incoming?0:amount,createdAt:new Date().toISOString()};if(relatedId)item.relatedId=relatedId;const next=[item,...entries];saveFinanceEntries(next);setEntries(next);if(type==="Customer Payment"&&relatedId){const updated:Sale[]=sales.map(s=>{if(s.id!==relatedId)return s;const paid=Math.min(s.sellingPrice,s.amountPaid+amount);return {...s,amountPaid:paid,balance:s.sellingPrice-paid,status:paid>=s.sellingPrice?"Fully Paid":"Partially Paid"}});saveSales(updated);setSales(updated)}setShowEntry(false);e.currentTarget.reset()}
 function addAccount(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item:Account={id:crypto.randomUUID(),name:String(f.get("name")),type:String(f.get("type")) as Account["type"],openingBalance:Number(f.get("openingBalance")||0)};const next=[...accounts,item];saveAccounts(next);setAccounts(next);setShowAccount(false);e.currentTarget.reset()}
 let runningBalance=accounts.reduce((sum,a)=>sum+a.openingBalance,0);const chronological=[...entries].sort((a,b)=>a.date.localeCompare(b.date));const rows:CashRow[]=chronological.map(e=>{runningBalance+=e.moneyIn-e.moneyOut;return {...e,balance:runningBalance}}).reverse();
 return <><div className="topbar"><div className="title"><h1>Finance & Accounting</h1><p>Cash position, customer balances, suppliers and driver advances.</p></div><button className="button" onClick={()=>setShowEntry(v=>!v)}><Plus size={18}/><span>New Transaction</span></button></div>
 <div className="cards"><div className="card metric"><div><div className="metric-label">Cash & Bank</div><div className="metric-value small-money">{money(cash)}</div></div><div className="metric-icon"><Banknote/></div></div><div className="card metric"><div><div className="metric-label">Customer Balances</div><div className="metric-value small-money">{money(receivables)}</div></div><div className="metric-icon"><WalletCards/></div></div><div className="card metric"><div><div className="metric-label">Supplier Balances</div><div className="metric-value small-money">{money(payables)}</div></div><div className="metric-icon"><Building2/></div></div><div className="card metric"><div><div className="metric-label">Unreconciled Advances</div><div className="metric-value small-money">{money(advances)}</div></div><div className="metric-icon"><Receipt/></div></div></div>
 {showEntry&&<form className="form-card section-gap" onSubmit={addEntry}><h2>Record Finance Transaction</h2><div className="form-grid"><div className="field"><label>Transaction Type</label><select className="select" name="type" required><option>Customer Payment</option><option>Supplier Payment</option><option>General Expense</option><option>Capital</option><option>Other Income</option></select></div><div className="field"><label>Account</label><select className="select" name="accountId" required>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></div><div className="field"><label>Related Sale or Vehicle</label><select className="select" name="relatedId"><option value="">Not linked</option><optgroup label="Customer Sales">{sales.filter(s=>s.balance>0).map(s=><option value={s.id} key={s.id}>{s.saleId} — {s.customerName} ({money(s.balance)})</option>)}</optgroup><optgroup label="Supplier Vehicles">{vehicles.map(v=><option value={v.id} key={v.id}>{v.stockId} — {v.supplier}</option>)}</optgroup></select></div><div className="field"><label>Amount</label><input className="input" name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Date</label><input className="input" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Reference</label><input className="input" name="reference" placeholder="Receipt, bank or mobile reference"/></div><div className="field full"><label>Description</label><input className="input" name="description" required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowEntry(false)}>Cancel</button><button className="button">Save Transaction</button></div></form>}
 <div className="deal-tabs"><button className={tab==="cashbook"?"active":""} onClick={()=>setTab("cashbook")}>Cash Book</button><button className={tab==="customers"?"active":""} onClick={()=>setTab("customers")}>Customer Balances</button><button className={tab==="suppliers"?"active":""} onClick={()=>setTab("suppliers")}>Supplier Balances</button><button className={tab==="advances"?"active":""} onClick={()=>setTab("advances")}>Driver Advances</button><button className={tab==="accounts"?"active":""} onClick={()=>setTab("accounts")}>Accounts</button></div>
 {tab==="cashbook"&&<section className="panel"><div className="panel-head"><h2>Cash Book</h2><span className="badge available">{entries.length} entries</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Account</th><th>Money In</th><th>Money Out</th><th>Balance</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.reference||"—"}</td><td><b>{e.type}</b><br/><small>{e.description}</small></td><td>{accounts.find(a=>a.id===e.accountId)?.name||"Unknown"}</td><td className="profit">{e.moneyIn?money(e.moneyIn):"—"}</td><td className="loss">{e.moneyOut?money(e.moneyOut):"—"}</td><td><b>{money(e.balance)}</b></td></tr>)}</tbody></table>{!entries.length&&<div className="empty">No finance transactions recorded.</div>}</div></section>}
 {tab==="customers"&&<section className="panel"><div className="panel-head"><h2>Customer Receivables</h2></div><div className="table-wrap"><table><thead><tr><th>Sale</th><th>Customer</th><th>Vehicle</th><th>Selling Price</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td><b>{s.saleId}</b></td><td>{s.customerName}</td><td>{s.stockId}</td><td>{money(s.sellingPrice)}</td><td>{money(s.amountPaid)}</td><td className={s.balance>0?"loss":"profit"}>{money(s.balance)}</td><td><span className={`badge ${s.status==="Fully Paid"?"available":"awaiting"}`}>{s.status}</span></td></tr>)}</tbody></table></div></section>}
 {tab==="suppliers"&&<section className="panel"><div className="panel-head"><h2>Supplier Payables</h2></div><div className="table-wrap"><table><thead><tr><th>Stock ID</th><th>Supplier</th><th>Vehicle</th><th>Purchase Price</th><th>Paid</th><th>Balance</th></tr></thead><tbody>{vehicles.map(v=>{const paid=supplierPaid(v.id),balance=Math.max(0,v.purchasePrice-paid);return <tr key={v.id}><td><b>{v.stockId}</b></td><td>{v.supplier}</td><td>{v.make} {v.model}</td><td>{money(v.purchasePrice)}</td><td>{money(paid)}</td><td className={balance>0?"loss":"profit"}>{money(balance)}</td></tr>})}</tbody></table></div></section>}
 {tab==="advances"&&<section className="panel"><div className="panel-head"><h2>Driver Advance Reconciliation</h2></div><div className="table-wrap"><table><thead><tr><th>Trip</th><th>Driver</th><th>Vehicle</th><th>Advance</th><th>Expenses</th><th>Balance</th><th>Status</th></tr></thead><tbody>{trips.map(t=>{const spent=tripSpent(t),balance=t.advance-spent;return <tr key={t.id}><td><b>{t.tripId}</b></td><td>{t.driverName}</td><td>{t.vehicleStockId}</td><td>{money(t.advance)}</td><td>{money(spent)}</td><td className={balance<0?"loss":"profit"}>{balance>=0?`${money(balance)} refund`:`${money(Math.abs(balance))} owed`}</td><td><span className={`badge ${t.status==="Reconciled"?"available":"awaiting"}`}>{t.status}</span></td></tr>})}</tbody></table></div></section>}
 {tab==="accounts"&&<><div className="section-actions"><div><h2>Bank, Cash & Mobile Accounts</h2><p>Balances update automatically from cash-book entries.</p></div><button className="button" onClick={()=>setShowAccount(v=>!v)}><Plus size={17}/>Add Account</button></div>{showAccount&&<form className="form-card section-gap" onSubmit={addAccount}><div className="form-grid"><div className="field"><label>Account Name</label><input className="input" name="name" required/></div><div className="field"><label>Type</label><select className="select" name="type"><option>Bank</option><option>Cash</option><option>Mobile Money</option></select></div><div className="field"><label>Opening Balance</label><input className="input" type="number" step="0.01" name="openingBalance" defaultValue="0"/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowAccount(false)}>Cancel</button><button className="button">Save Account</button></div></form>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:14}}>{accounts.map(a=><div className="card" key={a.id}><div className="metric-label">{a.type}</div><h3>{a.name}</h3><div className="metric-value small-money">{money(accountBalance(a,entries))}</div></div>)}</div></>}
 </>;
}