"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Banknote,Building2,Plus,Receipt,WalletCards} from "lucide-react";
import {accountBalance,Account,FinanceEntry,loadAccounts,loadFinanceEntries,saveAccounts,saveFinanceEntries} from "@/lib/finance-store";
import {loadSales,Sale,saveSales} from "@/lib/sales-store";
import {loadVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {Currency,formatCurrency,normalizeCurrency} from "@/lib/currency";

type Tab="cashbook"|"customers"|"suppliers"|"accounts";
type CashRow=FinanceEntry&{balance:number};

export default function FinancePage(){
 const [accounts,setAccounts]=useState<Account[]>([]);
 const [entries,setEntries]=useState<FinanceEntry[]>([]);
 const [sales,setSales]=useState<Sale[]>([]);
 const [vehicles,setVehicles]=useState<Vehicle[]>([]);
 const [tab,setTab]=useState<Tab>("cashbook");
 const [showEntry,setShowEntry]=useState(false);
 const [showAccount,setShowAccount]=useState(false);
 const [selectedAccount,setSelectedAccount]=useState("");
 const [cashbookAccount,setCashbookAccount]=useState("All");
 const [message,setMessage]=useState("");

 useEffect(()=>{const a=loadAccounts();setAccounts(a);setSelectedAccount(a[0]?.id||"");setEntries(loadFinanceEntries());setSales(loadSales());setVehicles(loadVehicles())},[]);
 const selected=accounts.find(a=>a.id===selectedAccount);
 const typeTotal=(type:Account["type"],currency:Currency)=>accounts.filter(a=>a.type===type&&normalizeCurrency(a.currency)===currency).reduce((sum,a)=>sum+accountBalance(a,entries),0);
 const receivable=(currency:Currency)=>sales.filter(s=>normalizeCurrency(s.currency)===currency).reduce((sum,s)=>sum+Number(s.balance||0),0);
 const supplierPaid=(vehicleId:string,currency:Currency)=>entries.filter(e=>e.type==="Supplier Payment"&&e.relatedId===vehicleId&&normalizeCurrency(e.currency)===currency).reduce((sum,e)=>sum+Number(e.moneyOut||0),0);
 const notify=(text:string)=>{setMessage(text);window.setTimeout(()=>setMessage(""),2800)};

 function addEntry(e:FormEvent<HTMLFormElement>){
  e.preventDefault();const f=new FormData(e.currentTarget);const target=accounts.find(a=>a.id===String(f.get("accountId")));if(!target)return;
  const type=String(f.get("type")) as FinanceEntry["type"],amount=Number(f.get("amount")),relatedId=String(f.get("relatedId")||""),currency=normalizeCurrency(target.currency);if(amount<=0)return;
  if(type==="Customer Payment"&&relatedId){const sale=sales.find(s=>s.id===relatedId);if(sale&&normalizeCurrency(sale.currency)!==currency){notify(`Use a ${normalizeCurrency(sale.currency)} account for this payment.`);return}}
  const incoming=type==="Customer Payment"||type==="Capital"||type==="Other Income";
  const base:FinanceEntry={id:crypto.randomUUID(),date:String(f.get("date")),type,reference:String(f.get("reference")||""),description:String(f.get("description")),accountId:target.id,moneyIn:incoming?amount:0,moneyOut:incoming?0:amount,currency,originalAmount:amount,createdAt:new Date().toISOString()};
  const item:FinanceEntry=relatedId?{...base,relatedId}:base;
  const next=[item,...entries];saveFinanceEntries(next);setEntries(next);
  if(type==="Customer Payment"&&relatedId){const updated:Sale[]=sales.map(s=>{if(s.id!==relatedId)return s;const paid=Math.min(s.sellingPrice,s.amountPaid+amount);return {...s,amountPaid:paid,balance:s.sellingPrice-paid,status:paid>=s.sellingPrice?"Fully Paid":"Partially Paid"}});saveSales(updated);setSales(updated)}
  setShowEntry(false);notify(`Posted to ${target.name}.`);e.currentTarget.reset();setSelectedAccount(accounts[0]?.id||"");
 }
 function addAccount(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const opening=Number(f.get("openingBalance")||0);const item:Account={id:crypto.randomUUID(),name:String(f.get("name")),type:String(f.get("type")) as Account["type"],openingBalance:opening,currency:String(f.get("currency")||"ZMW") as Currency,originalOpeningBalance:opening};const next=[...accounts,item];saveAccounts(next);setAccounts(next);setShowAccount(false);notify(`${item.name} created.`);e.currentTarget.reset()}

 const rows=useMemo(()=>{const selectedAccounts=cashbookAccount==="All"?accounts:accounts.filter(a=>a.id===cashbookAccount);const result:CashRow[]=[];selectedAccounts.forEach(a=>{let balance=Number(a.openingBalance||0);entries.filter(e=>e.accountId===a.id).sort((x,y)=>x.date.localeCompare(y.date)).forEach(e=>{balance+=Number(e.moneyIn||0)-Number(e.moneyOut||0);result.push({...e,balance})})});return result.sort((a,b)=>b.date.localeCompare(a.date))},[accounts,entries,cashbookAccount]);
 const Summary=({type,title,icon}:{type:Account["type"];title:string;icon:React.ReactNode})=><section className="finance-type-card"><div>{icon}<span><small>{title}</small><b>{accounts.filter(a=>a.type===type).length} account(s)</b></span></div><p><span>ZMW</span><b>{formatCurrency(typeTotal(type,"ZMW"),"ZMW")}</b></p><p><span>USD</span><b>{formatCurrency(typeTotal(type,"USD"),"USD")}</b></p></section>;

 return <>
 {message&&<div className="app-toast"><span>✓</span>{message}</div>}
 <div className="page-heading"><div><span className="eyebrow dark">FINANCE</span><h1>Finance & Accounting</h1><p>Cash, bank and mobile-money balances are maintained separately.</p></div><button className="button" onClick={()=>setShowEntry(v=>!v)}><Plus size={18}/>New Transaction</button></div>
 <div className="finance-account-summary"><Summary type="Cash" title="Cash" icon={<Banknote/>}/><Summary type="Bank" title="Bank" icon={<Building2/>}/><Summary type="Mobile Money" title="Mobile Money" icon={<WalletCards/>}/><section className="finance-type-card"><div><Receipt/><span><small>Receivables</small><b>Customer balances</b></span></div><p><span>ZMW</span><b>{formatCurrency(receivable("ZMW"),"ZMW")}</b></p><p><span>USD</span><b>{formatCurrency(receivable("USD"),"USD")}</b></p></section></div>
 {showEntry&&<form className="form-card professional-form" onSubmit={addEntry}><div className="form-heading"><h2>Record Transaction</h2></div><div className="form-grid"><div className="field"><label>Transaction Type</label><select className="select" name="type"><option>Customer Payment</option><option>Supplier Payment</option><option>General Expense</option><option>Capital</option><option>Other Income</option></select></div><div className="field"><label>Post To Account</label><select className="select" name="accountId" value={selectedAccount} onChange={e=>setSelectedAccount(e.target.value)} required>{accounts.map(a=><option value={a.id} key={a.id}>{a.name} · {a.type} · {normalizeCurrency(a.currency)}</option>)}</select></div><div className="field"><label>Account Currency</label><input className="input" readOnly value={selected?normalizeCurrency(selected.currency):""}/></div><div className="field"><label>Related Sale or Vehicle</label><select className="select" name="relatedId"><option value="">Not linked</option><optgroup label="Customer Sales">{sales.filter(s=>s.balance>0).map(s=><option value={s.id} key={s.id}>{s.saleId} — {s.customerName}</option>)}</optgroup><optgroup label="Supplier Vehicles">{vehicles.map(v=><option value={v.id} key={v.id}>{v.stockId} — {v.supplier}</option>)}</optgroup></select></div><div className="field"><label>Amount</label><input className="input" name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Date</label><input className="input" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Reference</label><input className="input" name="reference"/></div><div className="field full"><label>Description</label><input className="input" name="description" required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowEntry(false)}>Cancel</button><button className="button">Save Transaction</button></div></form>}
 <div className="deal-tabs"><button className={tab==="cashbook"?"active":""} onClick={()=>setTab("cashbook")}>Cash Book</button><button className={tab==="customers"?"active":""} onClick={()=>setTab("customers")}>Customer Balances</button><button className={tab==="suppliers"?"active":""} onClick={()=>setTab("suppliers")}>Supplier Balances</button><button className={tab==="accounts"?"active":""} onClick={()=>setTab("accounts")}>Accounts</button></div>
 {tab==="cashbook"&&<section className="panel"><div className="panel-head"><h2>Cash Book</h2><select className="select compact-select" value={cashbookAccount} onChange={e=>setCashbookAccount(e.target.value)}><option value="All">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.type} · {normalizeCurrency(a.currency)}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Account</th><th>Type</th><th>Money In</th><th>Money Out</th><th>Balance</th></tr></thead><tbody>{rows.map(e=>{const a=accounts.find(x=>x.id===e.accountId),c=normalizeCurrency(e.currency);return <tr key={e.id}><td>{e.date}</td><td><b>{a?.name||"Unknown"}</b><br/><small>{a?.type} · {c}</small></td><td>{e.type}<br/><small>{e.description}</small></td><td className="profit">{e.moneyIn?formatCurrency(e.moneyIn,c):"—"}</td><td className="loss">{e.moneyOut?formatCurrency(e.moneyOut,c):"—"}</td><td><b>{formatCurrency(e.balance,c)}</b></td></tr>})}</tbody></table>{!rows.length&&<div className="empty">No transactions for the selected account.</div>}</div></section>}
 {tab==="customers"&&<section className="panel"><div className="panel-head"><h2>Customer Receivables</h2></div><div className="table-wrap"><table><thead><tr><th>Sale</th><th>Customer</th><th>Currency</th><th>Price</th><th>Paid</th><th>Balance</th></tr></thead><tbody>{sales.map(s=>{const c=normalizeCurrency(s.currency);return <tr key={s.id}><td><b>{s.saleId}</b></td><td>{s.customerName}</td><td>{c}</td><td>{formatCurrency(s.sellingPrice,c)}</td><td>{formatCurrency(s.amountPaid,c)}</td><td>{formatCurrency(s.balance,c)}</td></tr>})}</tbody></table></div></section>}
 {tab==="suppliers"&&<section className="panel"><div className="panel-head"><h2>Supplier Payables</h2></div><div className="table-wrap"><table><thead><tr><th>Stock ID</th><th>Supplier</th><th>Currency</th><th>Purchase Price</th><th>Paid</th><th>Balance</th></tr></thead><tbody>{vehicles.map(v=>{const c=normalizeCurrency(v.purchaseCurrency),paid=supplierPaid(v.id,c),balance=Math.max(0,v.purchasePrice-paid);return <tr key={v.id}><td><b>{v.stockId}</b></td><td>{v.supplier}</td><td>{c}</td><td>{formatCurrency(v.purchasePrice,c)}</td><td>{formatCurrency(paid,c)}</td><td>{formatCurrency(balance,c)}</td></tr>})}</tbody></table></div></section>}
 {tab==="accounts"&&<><div className="section-actions"><div><h2>Financial Accounts</h2><p>Each account keeps its own balance and currency.</p></div><button className="button" onClick={()=>setShowAccount(v=>!v)}><Plus size={17}/>Add Account</button></div>{showAccount&&<form className="form-card" onSubmit={addAccount}><div className="form-grid"><div className="field"><label>Account Name</label><input className="input" name="name" required/></div><div className="field"><label>Type</label><select className="select" name="type"><option>Bank</option><option>Cash</option><option>Mobile Money</option></select></div><div className="field"><label>Currency</label><select className="select" name="currency"><option>ZMW</option><option>USD</option></select></div><div className="field"><label>Opening Balance</label><input className="input" name="openingBalance" type="number" step="0.01" defaultValue="0"/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowAccount(false)}>Cancel</button><button className="button">Save Account</button></div></form>}<div className="account-grid">{accounts.map(a=><div className="card" key={a.id}><div className="metric-label">{a.type} · {normalizeCurrency(a.currency)}</div><h3>{a.name}</h3><div className="metric-value small-money">{formatCurrency(accountBalance(a,entries),normalizeCurrency(a.currency))}</div></div>)}</div></>}
 </>;
}
