"use client";
import {useEffect,useMemo,useState} from "react";
import {Download,FileBarChart2,Printer} from "lucide-react";
import {loadVehicles} from "@/lib/vehicle-store";
import {loadSales} from "@/lib/sales-store";
import {loadTrips,tripSpent} from "@/lib/operations-store";
import {loadVehicleExpenses} from "@/lib/ledger-store";
import {loadFinanceEntries,loadAccounts} from "@/lib/finance-store";
import {loadTaxReturns} from "@/lib/tax-store";
import {formatCurrency,normalizeCurrency,toZmw} from "@/lib/currency";
import {saleProfitAnalysis,vehicleAccountingCostZmw} from "@/lib/financial-analysis";
type Report="vehicle-profit"|"sales"|"stock"|"cashbook"|"customers"|"suppliers"|"drivers"|"tax";
type Row=Record<string,string|number>;
const titles:Record<Report,string>={"vehicle-profit":"Vehicle Profit","sales":"Sales Register","stock":"Vehicle Stock","cashbook":"Cash Book","customers":"Customer Balances","suppliers":"Supplier Balances","drivers":"Driver Performance","tax":"Tax Returns"};
const originalSale=(s:any)=>formatCurrency(Number(s.originalSellingPrice??s.sellingPrice||0),normalizeCurrency(s.currency));
const saleZmw=(s:any)=>Number(s.sellingPriceZmw??toZmw(Number(s.originalSellingPrice??s.sellingPrice||0),s.currency||"ZMW",s.exchangeRate));
const paidZmw=(s:any)=>Number(s.amountPaidZmw??toZmw(Number(s.originalAmountPaid??s.amountPaid||0),s.currency||"ZMW",s.exchangeRate));
const balanceZmw=(s:any)=>Number(s.balanceZmw??Math.max(0,saleZmw(s)-paidZmw(s)));
export default function ReportsPage(){
 const [report,setReport]=useState<Report>("vehicle-profit"),[vehicles,setVehicles]=useState<any[]>([]),[sales,setSales]=useState<any[]>([]),[trips,setTrips]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[finance,setFinance]=useState<any[]>([]),[accounts,setAccounts]=useState<any[]>([]),[tax,setTax]=useState<any[]>([]);
 useEffect(()=>{setVehicles(loadVehicles());setSales(loadSales());setTrips(loadTrips());setExpenses(loadVehicleExpenses());setFinance(loadFinanceEntries());setAccounts(loadAccounts());setTax(loadTaxReturns())},[]);
 const rows=useMemo<Row[]>(()=>{
  if(report==="vehicle-profit")return sales.map(s=>{const a=saleProfitAnalysis(s,vehicles.find(v=>v.id===s.vehicleId),expenses);return {"Stock ID":s.stockId,Vehicle:s.vehicleName,Customer:s.customerName,"Original Sale":originalSale(s),"Accounting Revenue (ZMW)":saleZmw(s),"Total Cost (ZMW)":a.cost,"Gross Profit (ZMW)":a.profit,Status:s.status}});
  if(report==="sales")return sales.map(s=>({"Sale ID":s.saleId,Date:s.saleDate,"Stock ID":s.stockId,Customer:s.customerName,"Original Sale":originalSale(s),"Sale Exchange Rate":Number(s.exchangeRate||1),"Accounting Revenue (ZMW)":saleZmw(s),"Paid (ZMW)":paidZmw(s),"Balance (ZMW)":balanceZmw(s),Status:s.status}));
  if(report==="stock")return vehicles.map(v=>({"Stock ID":v.stockId,Vehicle:`${v.make} ${v.model} ${v.year}`,VIN:v.vin,Supplier:v.supplier,Location:v.currentLocation,"Original Purchase":formatCurrency(Number(v.originalPurchasePrice??v.purchasePrice||0),normalizeCurrency(v.purchaseCurrency)),"Purchase Exchange Rate":Number(v.purchaseExchangeRate||1),"Accounting Cost (ZMW)":Number(v.purchasePriceZmw??toZmw(Number(v.originalPurchasePrice??v.purchasePrice||0),v.purchaseCurrency||"ZMW",v.purchaseExchangeRate)),"Estimated Value (ZMW)":Number(v.estimatedSellingPriceZmw??toZmw(Number(v.estimatedSellingPrice||0),v.estimatedSellingCurrency||"ZMW",v.estimatedSellingExchangeRate)),Status:v.status}));
  if(report==="cashbook")return finance.map(x=>({Date:x.date,Account:accounts.find(a=>a.id===x.accountId)?.name||"Unknown",Type:x.type,Reference:x.reference||"",Description:x.description,"Money In (ZMW)":Number(x.moneyIn||0),"Money Out (ZMW)":Number(x.moneyOut||0)}));
  if(report==="customers")return sales.map(s=>({Customer:s.customerName,"Sale ID":s.saleId,Vehicle:s.stockId,"Original Sale":originalSale(s),"Accounting Revenue (ZMW)":saleZmw(s),"Paid (ZMW)":paidZmw(s),"Balance (ZMW)":balanceZmw(s),Status:s.status}));
  if(report==="suppliers")return vehicles.map(v=>{const price=Number(v.purchasePriceZmw??toZmw(Number(v.originalPurchasePrice??v.purchasePrice||0),v.purchaseCurrency||"ZMW",v.purchaseExchangeRate));const paid=finance.filter(x=>x.type==="Supplier Payment"&&x.relatedId===v.id).reduce((a:number,b:any)=>a+Number(b.moneyOut||0),0);return {Supplier:v.supplier,"Stock ID":v.stockId,Vehicle:`${v.make} ${v.model}`,"Original Purchase":formatCurrency(Number(v.originalPurchasePrice??v.purchasePrice||0),normalizeCurrency(v.purchaseCurrency)),"Accounting Cost (ZMW)":price,"Paid (ZMW)":paid,"Balance (ZMW)":Math.max(0,price-paid)}});
  if(report==="drivers")return trips.map(t=>{const spent=tripSpent(t);return {Driver:t.driverName,"Trip ID":t.tripId,Vehicle:t.vehicleStockId,Route:`${t.collectionPoint} to ${t.destination}`,"Advance (ZMW)":Number(t.advanceZmw??t.advance||0),"Expenses (ZMW)":spent,"Balance (ZMW)":Number(t.advanceZmw??t.advance||0)-spent,Status:t.status}});
  return tax.map(t=>({Type:t.type,Period:t.period,"Taxable Amount (ZMW)":t.taxableAmount,"Tax Due (ZMW)":t.taxDue,"Due Date":t.dueDate,Status:t.status,Reference:t.reference||""}));
 },[report,vehicles,sales,trips,expenses,finance,accounts,tax]);
 const revenue=sales.reduce((sum,s)=>sum+saleZmw(s),0),outstanding=sales.reduce((sum,s)=>sum+balanceZmw(s),0),profit=sales.reduce((sum,s)=>sum+saleProfitAnalysis(s,vehicles.find(v=>v.id===s.vehicleId),expenses).profit,0);
 function exportCsv(){if(!rows.length)return alert("There is no data to export.");const h=Object.keys(rows[0]);const csv=[h.join(","),...rows.map(r=>h.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`covenant-motors-${report}.csv`;a.click();URL.revokeObjectURL(url)}
 const headers=rows.length?Object.keys(rows[0]):[];
 return <><div className="topbar"><div className="title"><h1>Reports & Analytics</h1><p>All accounting reports use ZMW. Original USD purchase and sale values remain visible for reference.</p></div><div className="quick-actions"><button className="button secondary" onClick={()=>window.print()}><Printer size={17}/>Print</button><button className="button" onClick={exportCsv}><Download size={17}/>Export CSV</button></div></div>
 <div className="cards"><div className="card metric"><div><div className="metric-label">Report Records</div><div className="metric-value">{rows.length}</div></div><div className="metric-icon"><FileBarChart2/></div></div><div className="card"><div className="metric-label">Sales Revenue (ZMW)</div><div className="metric-value small-money">{formatCurrency(revenue,"ZMW")}</div></div><div className="card"><div className="metric-label">Gross Profit (ZMW)</div><div className="metric-value small-money">{formatCurrency(profit,"ZMW")}</div></div><div className="card"><div className="metric-label">Outstanding (ZMW)</div><div className="metric-value small-money">{formatCurrency(outstanding,"ZMW")}</div></div></div>
 <div className="deal-tabs">{(Object.keys(titles) as Report[]).map(k=><button key={k} className={report===k?"active":""} onClick={()=>setReport(k)}>{titles[k]}</button>)}</div><section className="panel report-print"><div className="panel-head"><div><h2>{titles[report]} Report</h2><small className="muted">Generated {new Date().toLocaleString("en-ZM")}</small></div><span className="badge available">{rows.length} records</span></div><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{headers.map(h=><td key={h}>{String(r[h]??"")}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">No data is available for this report yet.</div>}</div></section></>;
}