"use client";
import {FormEvent,useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {loadVehicles,saveVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";

export default function EditVehiclePage(){
 const params=useParams<{id:string}>(),router=useRouter();
 const [vehicle,setVehicle]=useState<Vehicle|null>(null),[error,setError]=useState("");
 useEffect(()=>setVehicle(loadVehicles().find(x=>x.id===params.id)||null),[params.id]);
 if(!vehicle)return <div className="panel"><div className="empty">Vehicle not found.</div></div>;
 function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();const f=new FormData(e.currentTarget),all=loadVehicles(),vin=String(f.get("vin")||"").trim().toUpperCase();
  if(all.some(v=>v.id!==vehicle.id&&v.vin.toUpperCase()===vin))return setError("This chassis/VIN is already registered.");
  const purchasePrice=Number(f.get("purchasePrice")||0),estimatedSellingPrice=Number(f.get("estimatedSellingPrice")||0),oldPurchase=Number(vehicle.purchasePriceZmw??vehicle.purchasePrice??0),existingExtras=Math.max(0,Number(vehicle.totalCost||0)-oldPurchase);
  const updated:Vehicle={...vehicle,vin,engineNumber:String(f.get("engineNumber")||""),registrationNumber:String(f.get("registrationNumber")||""),make:String(f.get("make")||""),model:String(f.get("model")||""),year:Number(f.get("year")),colour:String(f.get("colour")||""),supplier:String(f.get("supplier")||""),purchasePrice,purchaseCurrency:"ZMW",originalPurchasePrice:purchasePrice,purchaseExchangeRate:1,purchasePriceZmw:purchasePrice,totalCost:purchasePrice+existingExtras,estimatedSellingPrice,estimatedSellingCurrency:"ZMW",estimatedSellingExchangeRate:1,estimatedSellingPriceZmw:estimatedSellingPrice,purchaseDate:String(f.get("purchaseDate")||""),currentLocation:String(f.get("location")||"")};
  saveVehicles(all.map(v=>v.id===vehicle.id?updated:v));router.push(`/vehicles/${vehicle.id}`);
 }
 return <><div className="topbar"><div className="title"><h1>Edit Vehicle</h1><p>Update the vehicle record while preserving its expenses, documents, trips and sale history.</p></div></div><form className="form-card" onSubmit={submit}>{error&&<div className="summary-item" style={{marginBottom:16,color:"#b91c1c"}}>{error}</div>}<div className="form-grid"><div className="field"><label>Stock ID</label><input className="input" value={vehicle.stockId} readOnly/></div><div className="field"><label>Chassis/VIN *</label><input className="input" name="vin" defaultValue={vehicle.vin} required/></div><div className="field"><label>Engine Number *</label><input className="input" name="engineNumber" defaultValue={vehicle.engineNumber} required/></div><div className="field"><label>Registration Number</label><input className="input" name="registrationNumber" defaultValue={vehicle.registrationNumber||""}/></div><div className="field"><label>Make *</label><input className="input" name="make" defaultValue={vehicle.make} required/></div><div className="field"><label>Model *</label><input className="input" name="model" defaultValue={vehicle.model} required/></div><div className="field"><label>Manufacture Year *</label><input className="input" name="year" type="number" min="1950" max="2035" defaultValue={vehicle.year} required/></div><div className="field"><label>Colour</label><input className="input" name="colour" defaultValue={vehicle.colour}/></div><div className="field"><label>Supplier *</label><input className="input" name="supplier" defaultValue={vehicle.supplier} required/></div><div className="field"><label>Cost Price (ZMW)</label><input className="input" name="purchasePrice" type="number" min="0" step="0.01" defaultValue={vehicle.purchasePriceZmw??vehicle.purchasePrice} required/></div><div className="field"><label>Estimated Selling Price (ZMW)</label><input className="input" name="estimatedSellingPrice" type="number" min="0" step="0.01" defaultValue={vehicle.estimatedSellingPriceZmw??vehicle.estimatedSellingPrice??0} required/></div><div className="field"><label>Purchase Date</label><input className="input" name="purchaseDate" type="date" defaultValue={vehicle.purchaseDate} required/></div><div className="field"><label>Current Location</label><input className="input" name="location" defaultValue={vehicle.currentLocation} required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>router.back()}>Cancel</button><button className="button">Save Changes</button></div></form></>;
}
