"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowUpDown,BadgeCheck,ContactRound,MapPin,Phone,Plus,Search,UsersRound,X} from "lucide-react";
import {Customer,loadCustomers,nextCustomerId,saveCustomers} from "@/lib/customer-store";
import {loadSales} from "@/lib/sales-store";
import {formatCurrency,groupCurrencyAmounts,normalizeCurrency} from "@/lib/currency";

type SortKey="newest"|"name"|"purchases";
export default function CustomersPage(){
 const [items,setItems]=useState<Customer[]>([]),[show,setShow]=useState(false),[q,setQ]=useState(""),[sales,setSales]=useState<any[]>([]),[sort,setSort]=useState<SortKey>("newest"),[message,setMessage]=useState("");
 useEffect(()=>{setItems(loadCustomers());setSales(loadSales())},[]);
 const purchaseCount=(id:string)=>sales.filter(s=>s.customerId===id).length;
 const filtered=useMemo(()=>items.filter(x=>`${x.customerId} ${x.name} ${x.phone} ${x.nrcOrTpin} ${x.address}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="purchases"?purchaseCount(b.id)-purchaseCount(a.id):new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()),[items,q,sort,sales]);
 const activeBuyers=new Set(sales.map(s=>s.customerId)).size;
 const outstanding=groupCurrencyAmounts(sales,s=>Number(s.balance||0),s=>normalizeCurrency(s.currency));
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const next:Customer={id:crypto.randomUUID(),customerId:nextCustomerId(items),name:String(f.get("name")).trim(),phone:String(f.get("phone")).trim(),nrcOrTpin:String(f.get("nrcOrTpin")).trim(),address:String(f.get("address")).trim(),createdAt:new Date().toISOString()};const all=[next,...items];saveCustomers(all);setItems(all);setShow(false);setMessage(`${next.name} was added successfully.`);window.setTimeout(()=>setMessage(""),3500);e.currentTarget.reset()}
 return <div className="customers-clean-page">
 {message&&<div className="toast-message"><BadgeCheck size={18}/><span>{message}</span><button type="button" onClick={()=>setMessage("")} aria-label="Dismiss"><X size={16}/></button></div>}
 <div className="page-heading"><div><h1>Customers</h1><p>Buyer contacts and sales history.</p></div><button type="button" className="button" onClick={()=>setShow(!show)}><Plus size={18}/><span>{show?"Close Form":"Add Customer"}</span></button></div>
 {show&&<form className="form-card professional-form customer-form-clean" onSubmit={submit}><div className="form-heading"><div><h2>New Customer</h2></div><button type="button" className="icon-button" onClick={()=>setShow(false)} aria-label="Close"><X size={18}/></button></div><div className="form-grid"><div className="field"><label>Full name</label><input className="input" name="name" required placeholder="Customer or business name" autoFocus/></div><div className="field"><label>Phone number</label><input className="input" name="phone" required placeholder="e.g. 0977 000 000"/></div><div className="field"><label>NRC / TPIN</label><input className="input" name="nrcOrTpin" required placeholder="Enter NRC or TPIN"/></div><div className="field"><label>Address</label><input className="input" name="address" required placeholder="Town, area or full address"/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShow(false)}>Cancel</button><button type="submit" className="button">Save Customer</button></div></form>}
 <div className="customer-summary-strip"><span><small>Customers</small><b>{items.length}</b></span><span><small>With Sales</small><b>{activeBuyers}</b></span><span><small>Sales</small><b>{sales.length}</b></span><span className="customer-outstanding"><small>Outstanding</small><b>{formatCurrency(outstanding.ZMW,"ZMW")}</b><b>{formatCurrency(outstanding.USD,"USD")}</b></span></div>
 <section className="panel register-panel customer-register-clean"><div className="inventory-toolbar"><div className="search-control"><Search size={17}/><input placeholder="Search customers" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button type="button" className="clear-search" onClick={()=>setQ("")} aria-label="Clear search"><X size={15}/></button>}</div><div className="filter-control"><ArrowUpDown size={16}/><select value={sort} onChange={e=>setSort(e.target.value as SortKey)}><option value="newest">Newest first</option><option value="name">Name A–Z</option><option value="purchases">Most purchases</option></select></div><span className="result-count">{filtered.length} of {items.length}</span></div><div className="desktop-customer-table table-wrap"><table><thead><tr><th>Customer</th><th>Contact</th><th>NRC / TPIN</th><th>Address</th><th>Purchases</th></tr></thead><tbody>{filtered.map(x=>{const count=purchaseCount(x.id);return <tr key={x.id}><td><div className="vehicle-cell"><div className="vehicle-thumb"><ContactRound size={18}/></div><span><b>{x.name}</b><small>{x.customerId}</small></span></div></td><td><span className="location-cell"><Phone size={14}/>{x.phone}</span></td><td className="mono-text">{x.nrcOrTpin}</td><td><span className="location-cell"><MapPin size={14}/>{x.address}</span></td><td><span className={`badge ${count?"available":"awaiting"}`}>{count}</span></td></tr>})}</tbody></table></div><div className="mobile-customer-list">{filtered.map(x=>{const count=purchaseCount(x.id);return <article className="mobile-record-card" key={x.id}><div className="mobile-record-head"><div className="vehicle-thumb"><ContactRound size={18}/></div><div><b>{x.name}</b><small>{x.customerId}</small></div><span className={`badge ${count?"available":"awaiting"}`}>{count} sale{count===1?"":"s"}</span></div><div className="mobile-record-meta"><span><Phone size={14}/>{x.phone}</span><span><BadgeCheck size={14}/>{x.nrcOrTpin}</span><span><MapPin size={14}/>{x.address}</span></div></article>})}</div>{!filtered.length&&<div className="empty"><UsersRound size={30}/><h3>No customers found</h3><p>{q?"Try another search.":"Add the first customer to begin."}</p></div>}</section>
 </div>;
}
