"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowUpDown,BadgeCheck,ContactRound,MapPin,PenLine,Phone,Plus,Search,UsersRound,X} from "lucide-react";
import {Customer,loadCustomers,nextCustomerId,saveCustomers} from "@/lib/customer-store";
import {loadSales} from "@/lib/sales-store";
import {formatCurrency} from "@/lib/currency";

type SortKey="newest"|"name"|"purchases";
export default function CustomersPage(){
 const [items,setItems]=useState<Customer[]>([]),[show,setShow]=useState(false),[editing,setEditing]=useState<Customer|null>(null),[q,setQ]=useState(""),[sales,setSales]=useState<any[]>([]),[sort,setSort]=useState<SortKey>("newest"),[message,setMessage]=useState("");
 useEffect(()=>{setItems(loadCustomers());setSales(loadSales())},[]);
 const purchaseCount=(id:string)=>sales.filter(s=>s.customerId===id).length;
 const customerBalance=(id:string)=>sales.filter(s=>s.customerId===id).reduce((sum,s)=>sum+Number(s.balanceZmw??s.balance??0),0);
 const filtered=useMemo(()=>items.filter(x=>`${x.customerId} ${x.name} ${x.phone} ${x.nrcOrTpin} ${x.address}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="purchases"?purchaseCount(b.id)-purchaseCount(a.id):new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()),[items,q,sort,sales]);
 const activeBuyers=new Set(sales.map(s=>s.customerId)).size;
 const outstanding=sales.reduce((sum,s)=>sum+Number(s.balanceZmw??s.balance??0),0);
 const closeForm=()=>{setShow(false);setEditing(null)};
 function startEdit(customer:Customer){setEditing(customer);setShow(true);window.scrollTo({top:0,behavior:"smooth"})}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const customer:Customer={id:editing?.id||crypto.randomUUID(),customerId:editing?.customerId||nextCustomerId(items),name:String(f.get("name")).trim(),phone:String(f.get("phone")).trim(),nrcOrTpin:String(f.get("nrcOrTpin")).trim(),address:String(f.get("address")).trim(),createdAt:editing?.createdAt||new Date().toISOString()};const all=editing?items.map(x=>x.id===editing.id?customer:x):[customer,...items];saveCustomers(all);setItems(all);closeForm();setMessage(`${customer.name} was ${editing?"updated":"added"} successfully.`);window.setTimeout(()=>setMessage(""),3500)}
 return <>
 {message&&<div className="toast-message"><BadgeCheck size={18}/><span>{message}</span><button onClick={()=>setMessage("")} aria-label="Dismiss"><X size={16}/></button></div>}
 <div className="page-heading"><div><span className="eyebrow dark">SALES · CUSTOMER RELATIONSHIPS</span><h1>Customers</h1><p>Maintain buyer records, contact details and outstanding payments.</p></div><button className="button" onClick={()=>{if(show)closeForm();else setShow(true)}}><Plus size={18}/><span>{show?"Close Form":"Add Customer"}</span></button></div>
 <div className="inventory-summary"><div className="mini-stat"><UsersRound/><div><small>Total Customers</small><b>{items.length}</b></div></div><div className="mini-stat"><BadgeCheck/><div><small>Customers with Sales</small><b>{activeBuyers}</b></div></div><div className="mini-stat"><ContactRound/><div><small>Recorded Sales</small><b>{sales.length}</b></div></div><div className="mini-stat"><Phone/><div><small>Outstanding</small><b>{formatCurrency(outstanding,"ZMW")}</b></div></div></div>
 {show&&<form key={editing?.id||"new"} className="form-card section-gap professional-form" onSubmit={submit}><div className="form-heading"><div><span className="eyebrow dark">{editing?"EDIT CUSTOMER":"NEW CUSTOMER"}</span><h2>{editing?editing.name:"Register customer"}</h2><p>Capture the details required for sales and follow-up.</p></div></div><div className="form-section"><div className="form-grid"><div className="field"><label>Full name</label><input className="input" name="name" required defaultValue={editing?.name||""} autoFocus/></div><div className="field"><label>Phone number</label><input className="input" name="phone" required defaultValue={editing?.phone||""}/></div><div className="field"><label>NRC / TPIN</label><input className="input" name="nrcOrTpin" required defaultValue={editing?.nrcOrTpin||""}/></div><div className="field"><label>Address</label><input className="input" name="address" required defaultValue={editing?.address||""}/></div></div></div><div className="actions"><button type="button" className="button secondary" onClick={closeForm}>Cancel</button><button className="button">{editing?"Save Changes":"Save Customer"}</button></div></form>}
 <section className="panel register-panel"><div className="inventory-toolbar"><div className="search-control"><Search size={17}/><input placeholder="Search name, ID, phone, NRC/TPIN or address" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button className="clear-search" type="button" onClick={()=>setQ("")} aria-label="Clear search"><X size={15}/></button>}</div><div className="filter-control"><ArrowUpDown size={16}/><select value={sort} onChange={e=>setSort(e.target.value as SortKey)}><option value="newest">Newest first</option><option value="name">Name A–Z</option><option value="purchases">Most purchases</option></select></div><span className="result-count">{filtered.length} of {items.length}</span></div><div className="desktop-customer-table table-wrap"><table><thead><tr><th>Customer</th><th>Contact</th><th>NRC / TPIN</th><th>Address</th><th>Purchases</th><th>Outstanding</th><th>Action</th></tr></thead><tbody>{filtered.map(x=>{const count=purchaseCount(x.id);return <tr key={x.id}><td><div className="vehicle-cell"><div className="vehicle-thumb"><ContactRound size={18}/></div><span><b>{x.name}</b><small>{x.customerId}</small></span></div></td><td><span className="location-cell"><Phone size={14}/>{x.phone}</span></td><td className="mono-text">{x.nrcOrTpin}</td><td><span className="location-cell"><MapPin size={14}/>{x.address}</span></td><td><span className={`badge ${count?"available":"awaiting"}`}>{count} sale{count===1?"":"s"}</span></td><td><b>{formatCurrency(customerBalance(x.id),"ZMW")}</b></td><td><button className="button secondary compact-button" type="button" onClick={()=>startEdit(x)}><PenLine size={14}/>Edit</button></td></tr>})}</tbody></table></div><div className="mobile-customer-list">{filtered.map(x=>{const count=purchaseCount(x.id);return <article className="mobile-record-card" key={x.id}><div className="mobile-record-head"><div className="vehicle-thumb"><ContactRound size={18}/></div><div><b>{x.name}</b><small>{x.customerId}</small></div><span className={`badge ${count?"available":"awaiting"}`}>{count} sale{count===1?"":"s"}</span></div><div className="mobile-record-meta"><span><Phone size={14}/>{x.phone}</span><span><BadgeCheck size={14}/>{x.nrcOrTpin}</span><span><MapPin size={14}/>{x.address}</span><span>Outstanding: <b>{formatCurrency(customerBalance(x.id),"ZMW")}</b></span></div><div className="mobile-card-actions"><button className="button secondary compact-button" type="button" onClick={()=>startEdit(x)}><PenLine size={14}/>Edit Customer</button></div></article>})}</div>{!filtered.length&&<div className="empty"><UsersRound size={34}/><h3>No customers found</h3><p>{q?"Try another search term.":"Register the first customer to begin."}</p></div>}</section>
 </>;
}
