"use client";
import {useEffect,useMemo,useState} from "react";
import {CalendarClock,CheckCircle2,IdCard,PenLine,Phone,Plus,Search,Trash2,Truck,UserRound,UsersRound} from "lucide-react";
import {Driver,loadDrivers,nextDriverId,saveDrivers} from "@/lib/operations-store";
import {AppDialog} from "@/components/app-dialog";

const emptyForm={name:"",phone:"",licence:"",licenceExpiry:""};
type DialogState={open:boolean;title:string;message:string;tone?:"default"|"danger"|"warning";confirmLabel?:string;driver?:Driver|null};
const emptyDialog:DialogState={open:false,title:"",message:"",driver:null};
export default function DriversPage(){
 const [drivers,setDrivers]=useState<Driver[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<Driver|null>(null),[form,setForm]=useState(emptyForm),[dialog,setDialog]=useState<DialogState>(emptyDialog);
 useEffect(()=>setDrivers(loadDrivers()),[]);
 const closeForm=()=>{setOpen(false);setEditing(null);setForm(emptyForm)};
 const closeDialog=()=>setDialog(emptyDialog);
 const showInfo=(title:string,message:string,tone:"default"|"warning"="default")=>setDialog({open:true,title,message,tone,confirmLabel:"OK",driver:null});
 const startEdit=(driver:Driver)=>{setEditing(driver);setForm({name:driver.name,phone:driver.phone,licence:driver.licence,licenceExpiry:driver.licenceExpiry||""});setOpen(true);window.scrollTo({top:0,behavior:"smooth"})};
 const save=()=>{if(!form.name||!form.phone||!form.licence)return showInfo("Complete driver details","Enter the driver's name, phone number and licence number before saving.","warning");const driver:Driver=editing?{...editing,...form}:{id:crypto.randomUUID(),driverId:nextDriverId(drivers),...form,status:"Available"};const next=editing?drivers.map(d=>d.id===editing.id?driver:d):[driver,...drivers];setDrivers(next);saveDrivers(next);closeForm()};
 const requestDelete=(driver:Driver)=>{if(driver.status==="On Trip")return showInfo("Driver cannot be deleted",`${driver.name} is assigned to an active collection trip. Complete or reconcile the trip before deleting this driver.`,"warning");setDialog({open:true,title:"Delete driver?",message:`Delete ${driver.name} from the driver register? This action cannot be undone.`,tone:"danger",confirmLabel:"Delete Driver",driver})};
 const confirmDelete=()=>{const driver=dialog.driver;if(!driver)return closeDialog();const next=drivers.filter(d=>d.id!==driver.id);setDrivers(next);saveDrivers(next);if(editing?.id===driver.id)closeForm();closeDialog()};
 const shown=useMemo(()=>drivers.filter(d=>`${d.driverId} ${d.name} ${d.phone} ${d.licence}`.toLowerCase().includes(q.toLowerCase())),[drivers,q]);
 const available=drivers.filter(d=>d.status==="Available").length,onTrip=drivers.filter(d=>d.status==="On Trip").length,expiring=drivers.filter(d=>d.licenceExpiry&&new Date(d.licenceExpiry).getTime()-Date.now()<90*86400000).length;
 return <>
 <AppDialog open={dialog.open} title={dialog.title} message={dialog.message} tone={dialog.tone} confirmLabel={dialog.confirmLabel} onConfirm={dialog.driver?confirmDelete:undefined} onClose={closeDialog}/>
 <div className="page-heading"><div><span className="eyebrow dark">OPERATIONS · DRIVER MANAGEMENT</span><h1>Drivers</h1><p>Maintain driver contact, licence and availability records.</p></div><button className="button" onClick={()=>open?closeForm():setOpen(true)}><Plus size={18}/><span>{open?"Close Form":"Add Driver"}</span></button></div>
 <div className="inventory-summary"><div className="mini-stat"><UsersRound/><div><small>Total Drivers</small><b>{drivers.length}</b></div></div><div className="mini-stat"><CheckCircle2/><div><small>Available</small><b>{available}</b></div></div><div className="mini-stat"><Truck/><div><small>On Collection Trips</small><b>{onTrip}</b></div></div><div className="mini-stat"><CalendarClock/><div><small>Licence Attention</small><b>{expiring}</b></div></div></div>
 {open&&<div className="form-card section-gap professional-form"><div className="form-heading"><div><span className="eyebrow dark">{editing?"EDIT DRIVER":"NEW DRIVER"}</span><h2>{editing?editing.name:"Register driver"}</h2><p>Capture identity, contact and licence information.</p></div></div><div className="form-grid"><div className="field"><label>Full name</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Phone number</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Licence number</label><input className="input" value={form.licence} onChange={e=>setForm({...form,licence:e.target.value})}/></div><div className="field"><label>Licence expiry</label><input className="input" type="date" value={form.licenceExpiry} onChange={e=>setForm({...form,licenceExpiry:e.target.value})}/></div></div><div className="actions"><button className="button secondary" type="button" onClick={closeForm}>Cancel</button><button className="button" type="button" onClick={save}>{editing?"Save Changes":"Save Driver"}</button></div></div>}
 <section className="panel register-panel"><div className="inventory-toolbar"><div className="search-control"><Search size={17}/><input placeholder="Search driver ID, name, phone or licence" value={q} onChange={e=>setQ(e.target.value)}/></div><span className="result-count">{shown.length} of {drivers.length} drivers</span></div><div className="driver-grid professional-driver-grid">{shown.map(d=><article className="driver-card professional-driver-card" key={d.id}><div className="avatar"><UserRound/></div><div className="driver-main"><div className="row-between"><div><b className="record-title">{d.name}</b><small>{d.driverId}</small></div><span className={`badge ${d.status==="Available"?"available":d.status==="On Trip"?"transit":"sold"}`}>{d.status}</span></div><div className="record-meta"><span><Phone size={15}/>{d.phone}</span><span><IdCard size={15}/>{d.licence}</span></div><div className="record-footer"><span>Licence expiry</span><b>{d.licenceExpiry||"Not captured"}</b></div><div className="mobile-card-actions"><button className="button secondary compact-button" type="button" onClick={()=>startEdit(d)} disabled={d.status==="On Trip"}><PenLine size={14}/>{d.status==="On Trip"?"On Active Trip":"Edit"}</button><button className="button secondary compact-button loss" type="button" onClick={()=>requestDelete(d)} disabled={d.status==="On Trip"}><Trash2 size={14}/>Delete</button></div></div></article>)}</div>{!shown.length&&<div className="empty"><UsersRound size={34}/><h3>No drivers found</h3><p>Adjust the search or register a new driver.</p></div>}</section>
 </>;
}
