"use client";
import {useEffect,useMemo,useState} from "react";
import {CalendarClock,CheckCircle2,IdCard,Phone,Plus,Search,Truck,UserRound,UsersRound} from "lucide-react";
import {Driver,loadDrivers,nextDriverId,saveDrivers} from "@/lib/operations-store";

export default function DriversPage(){
 const [drivers,setDrivers]=useState<Driver[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false);
 const [form,setForm]=useState({name:"",phone:"",licence:"",licenceExpiry:""});
 useEffect(()=>setDrivers(loadDrivers()),[]);
 const add=()=>{if(!form.name||!form.phone||!form.licence)return alert("Complete name, phone and licence number.");const d:Driver={id:crypto.randomUUID(),driverId:nextDriverId(drivers),...form,status:"Available"};const next=[...drivers,d];setDrivers(next);saveDrivers(next);setForm({name:"",phone:"",licence:"",licenceExpiry:""});setOpen(false)};
 const shown=useMemo(()=>drivers.filter(d=>`${d.driverId} ${d.name} ${d.phone} ${d.licence}`.toLowerCase().includes(q.toLowerCase())),[drivers,q]);
 const available=drivers.filter(d=>d.status==="Available").length;
 const onTrip=drivers.filter(d=>d.status==="On Trip").length;
 const expiring=drivers.filter(d=>d.licenceExpiry&&new Date(d.licenceExpiry).getTime()-Date.now()<90*86400000).length;
 return <>
 <div className="page-heading"><div><span className="eyebrow dark">OPERATIONS · DRIVER MANAGEMENT</span><h1>Drivers</h1><p>Maintain a reliable driver register, monitor collection availability and keep licence records visible.</p></div><button className="button" onClick={()=>setOpen(!open)}><Plus size={18}/><span>Add Driver</span></button></div>
 <div className="inventory-summary"><div className="mini-stat"><UsersRound/><div><small>Total Drivers</small><b>{drivers.length}</b></div></div><div className="mini-stat"><CheckCircle2/><div><small>Available</small><b>{available}</b></div></div><div className="mini-stat"><Truck/><div><small>On Collection Trips</small><b>{onTrip}</b></div></div><div className="mini-stat"><CalendarClock/><div><small>Licence Attention</small><b>{expiring}</b></div></div></div>
 {open&&<div className="form-card section-gap professional-form"><div className="form-heading"><div><span className="eyebrow dark">NEW DRIVER</span><h2>Register driver</h2><p>Capture identity, contact and licence information.</p></div></div><div className="form-grid"><div className="field"><label>Full name</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Enter full name"/></div><div className="field"><label>Phone number</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="e.g. 0977 000 000"/></div><div className="field"><label>Licence number</label><input className="input" value={form.licence} onChange={e=>setForm({...form,licence:e.target.value})} placeholder="Enter licence number"/></div><div className="field"><label>Licence expiry</label><input className="input" type="date" value={form.licenceExpiry} onChange={e=>setForm({...form,licenceExpiry:e.target.value})}/></div></div><div className="actions"><button className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button" onClick={add}>Save Driver</button></div></div>}
 <section className="panel register-panel"><div className="inventory-toolbar"><div className="search-control"><Search size={17}/><input placeholder="Search driver ID, name, phone or licence" value={q} onChange={e=>setQ(e.target.value)}/></div><span className="result-count">{shown.length} of {drivers.length} drivers</span></div><div className="driver-grid professional-driver-grid">{shown.map(d=><article className="driver-card professional-driver-card" key={d.id}><div className="avatar"><UserRound/></div><div className="driver-main"><div className="row-between"><div><b className="record-title">{d.name}</b><small>{d.driverId}</small></div><span className={`badge ${d.status==="Available"?"available":d.status==="On Trip"?"transit":"sold"}`}>{d.status}</span></div><div className="record-meta"><span><Phone size={15}/>{d.phone}</span><span><IdCard size={15}/>{d.licence}</span></div><div className="record-footer"><span>Licence expiry</span><b>{d.licenceExpiry||"Not captured"}</b></div></div></article>)}</div>{!shown.length&&<div className="empty"><UsersRound size={34}/><h3>No drivers found</h3><p>Adjust the search or register a new driver.</p></div>}</section>
 </>;
}
