"use client";
import {useEffect,useState} from "react";
import {Plus,Search,UserRound,Phone,IdCard} from "lucide-react";
import {Driver,loadDrivers,nextDriverId,saveDrivers} from "@/lib/operations-store";
export default function DriversPage(){
 const [drivers,setDrivers]=useState<Driver[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false);
 const [form,setForm]=useState({name:"",phone:"",licence:"",licenceExpiry:""});
 useEffect(()=>setDrivers(loadDrivers()),[]);
 const add=()=>{if(!form.name||!form.phone||!form.licence)return alert("Complete name, phone and licence number.");const d:Driver={id:crypto.randomUUID(),driverId:nextDriverId(drivers),...form,status:"Available"};const next=[...drivers,d];setDrivers(next);saveDrivers(next);setForm({name:"",phone:"",licence:"",licenceExpiry:""});setOpen(false)};
 const shown=drivers.filter(d=>`${d.driverId} ${d.name} ${d.phone} ${d.licence}`.toLowerCase().includes(q.toLowerCase()));
 return <><div className="topbar"><div className="title"><h1>Drivers</h1><p>Register drivers and monitor collection availability.</p></div><button className="button" onClick={()=>setOpen(!open)}><Plus size={18}/><span>Add Driver</span></button></div>
 {open&&<div className="form-card section-gap"><div className="form-grid"><div className="field"><label>Full name</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Phone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Licence number</label><input className="input" value={form.licence} onChange={e=>setForm({...form,licence:e.target.value})}/></div><div className="field"><label>Licence expiry</label><input className="input" type="date" value={form.licenceExpiry} onChange={e=>setForm({...form,licenceExpiry:e.target.value})}/></div></div><div className="actions"><button className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button" onClick={add}>Save Driver</button></div></div>}
 <div className="panel"><div className="panel-head"><h2>Driver Register</h2><span className="muted">{drivers.length} drivers</span></div><div className="panel-body"><div className="toolbar"><div className="searchbox"><Search size={17}/><input className="input" placeholder="Search driver, phone or licence" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="driver-grid">{shown.map(d=><div className="driver-card" key={d.id}><div className="avatar"><UserRound/></div><div className="driver-main"><div className="row-between"><div><b>{d.name}</b><small>{d.driverId}</small></div><span className={`badge ${d.status==="Available"?"available":d.status==="On Trip"?"transit":"sold"}`}>{d.status}</span></div><p><Phone size={15}/>{d.phone}</p><p><IdCard size={15}/>{d.licence}</p><div className="muted tiny">Licence expiry: {d.licenceExpiry||"Not set"}</div></div></div>)}</div>{!shown.length&&<div className="empty">No drivers found.</div>}</div></div></>;
}
