"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {ArrowRight,Car,Clock3,FileWarning,MapPin,Receipt,Route,ShoppingCart,Truck,Users,Wallet} from "lucide-react";
import {loadVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {loadTrips,CollectionTrip} from "@/lib/operations-store";
import {loadSales,Sale} from "@/lib/sales-store";
import {loadVehicleDocuments,loadVehicleExpenses,VehicleDocument,VehicleExpense} from "@/lib/ledger-store";
import {CurrencyTotals,formatCurrency,groupCurrencyAmounts,normalizeCurrency} from "@/lib/currency";
import {saleProfitAnalysis} from "@/lib/financial-analysis";

const badge=(status:string)=>status==="Available"?"available":status==="In Transit"?"transit":status==="Sold"?"sold":"awaiting";

export default function Dashboard(){
 const [vehicles,setVehicles]=useState<Vehicle[]>([]),[trips,setTrips]=useState<CollectionTrip[]>([]),[sales,setSales]=useState<Sale[]>([]),[expenses,setExpenses]=useState<VehicleExpense[]>([]),[documents,setDocuments]=useState<VehicleDocument[]>([]);
 useEffect(()=>{setVehicles(loadVehicles());setTrips(loadTrips());setSales(loadSales());setExpenses(loadVehicleExpenses());setDocuments(loadVehicleDocuments())},[]);
 const stats=useMemo(()=>{const unsold=vehicles.filter(v=>v.status!=="Sold");const stock=groupCurrencyAmounts(unsold,v=>Number(v.estimatedSellingPrice||0),v=>v.estimatedSellingCurrency);const revenue=groupCurrencyAmounts(sales,s=>s.sellingPrice,s=>s.currency);const outstanding=groupCurrencyAmounts(sales,s=>s.balance,s=>s.currency);const profit:CurrencyTotals={ZMW:0,USD:0};let mixedProfit=0;sales.forEach(s=>{const a=saleProfitAnalysis(s,vehicles.find(v=>v.id===s.vehicleId),expenses);if(a.mixed)mixedProfit++;else profit[a.currency]+=a.profit});return {total:vehicles.length,available:vehicles.filter(v=>v.status==="Available").length,transit:vehicles.filter(v=>v.status==="In Transit").length,awaiting:vehicles.filter(v=>v.status==="Awaiting Collection").length,sold:vehicles.filter(v=>v.status==="Sold").length,activeTrips:trips.filter(t=>t.status!=="Reconciled").length,missingDocs:vehicles.filter(v=>!documents.some(d=>d.vehicleId===v.id&&d.type==="Purchase Invoice")).length,stock,revenue,outstanding,profit,mixedProfit};},[vehicles,trips,sales,expenses,documents]);
 const activity=useMemo(()=>[...vehicles.map(v=>({date:v.createdAt,title:"Vehicle registered",detail:`${v.stockId} · ${v.make} ${v.model}`,kind:"vehicle"})),...expenses.map(x=>{const v=vehicles.find(v=>v.id===x.vehicleId);return {date:x.createdAt,title:"Expense recorded",detail:`${v?.stockId||"Vehicle"} · ${formatCurrency(x.amount,normalizeCurrency(x.currency))}`,kind:"expense"}}),...trips.map(t=>({date:t.departureDate,title:"Collection trip updated",detail:`${t.tripId} · ${t.driverName}`,kind:"trip"})),...sales.map(s=>({date:s.createdAt,title:"Vehicle sold",detail:`${s.stockId} · ${formatCurrency(s.sellingPrice,normalizeCurrency(s.currency))}`,kind:"sale"}))].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()).slice(0,6),[vehicles,expenses,trips,sales]);
 const recent=vehicles.slice().sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()).slice(0,5);
 const MoneyRows=({values}:{values:CurrencyTotals})=><div className="clean-money"><span><small>ZMW</small><b>{formatCurrency(values.ZMW,"ZMW")}</b></span><span><small>USD</small><b>{formatCurrency(values.USD,"USD")}</b></span></div>;
 return <>
  <div className="clean-dashboard-head"><div><span className="eyebrow dark">BUSINESS OVERVIEW</span><h1>Dashboard</h1><p>A clear view of inventory, sales, operations and items requiring attention.</p></div></div>
  <div className="clean-dashboard-grid">
   <section className="clean-overview-card"><div className="clean-card-title"><Car/><div><small>Inventory</small><b>{stats.total} vehicles</b></div></div><div className="clean-stat-list"><span><em>Available</em><b>{stats.available}</b></span><span><em>In transit</em><b>{stats.transit}</b></span><span><em>Awaiting collection</em><b>{stats.awaiting}</b></span><span><em>Sold</em><b>{stats.sold}</b></span></div><Link href="/vehicles">View vehicle stock <ArrowRight size={15}/></Link></section>
   <section className="clean-overview-card"><div className="clean-card-title"><ShoppingCart/><div><small>Sales</small><b>{sales.length} recorded</b></div></div><div className="clean-metric-block"><small>Revenue</small><MoneyRows values={stats.revenue}/></div><div className="clean-metric-block"><small>Outstanding</small><MoneyRows values={stats.outstanding}/></div><Link href="/sales">Open sales register <ArrowRight size={15}/></Link></section>
   <section className="clean-overview-card"><div className="clean-card-title"><Route/><div><small>Operations</small><b>{stats.activeTrips} active trips</b></div></div><div className="clean-stat-list"><span><em>Missing purchase invoices</em><b>{stats.missingDocs}</b></span><span><em>Drivers and trips</em><b><Users size={16}/></b></span></div><Link href="/trips">Manage collection trips <ArrowRight size={15}/></Link></section>
   <section className="clean-overview-card"><div className="clean-card-title"><Wallet/><div><small>Finance</small><b>Stock valuation</b></div></div><div className="clean-metric-block"><MoneyRows values={stats.stock}/></div><div className="clean-metric-block"><small>Gross profit</small><MoneyRows values={stats.profit}/></div>{stats.mixedProfit>0&&<small className="clean-warning">{stats.mixedProfit} sale(s) need currency review</small>}<Link href="/cost-analysis">Open cost analysis <ArrowRight size={15}/></Link></section>
  </div>
  {(stats.activeTrips>0||stats.missingDocs>0||stats.outstanding.ZMW>0||stats.outstanding.USD>0)&&<section className="panel clean-attention"><div className="panel-head"><h2>Needs Attention</h2></div><div className="clean-attention-list">{stats.activeTrips>0&&<Link href="/trips"><Route/><span><b>{stats.activeTrips} active collection trip(s)</b><small>Review progress and reconciliation.</small></span><ArrowRight/></Link>}{stats.missingDocs>0&&<Link href="/vehicles"><FileWarning/><span><b>{stats.missingDocs} vehicle(s) missing purchase invoices</b><small>Complete the vehicle Deal Jacket.</small></span><ArrowRight/></Link>}{(stats.outstanding.ZMW>0||stats.outstanding.USD>0)&&<Link href="/sales"><Receipt/><span><b>Customer balances outstanding</b><small>{formatCurrency(stats.outstanding.ZMW,"ZMW")} · {formatCurrency(stats.outstanding.USD,"USD")}</small></span><ArrowRight/></Link>}</div></section>}
  <div className="clean-dashboard-lower">
   <section className="panel"><div className="panel-head"><h2>Recent Vehicles</h2><Link href="/vehicles">View all <ArrowRight size={15}/></Link></div><div className="clean-vehicle-list">{recent.map(v=><Link href={`/vehicles/${v.id}`} key={v.id}><div className="vehicle-thumb"><Car size={18}/></div><span><b>{v.make} {v.model} {v.year}</b><small>{v.stockId} · {v.currentLocation}</small></span><span className={`badge ${badge(v.status)}`}>{v.status}</span></Link>)}{!recent.length&&<div className="empty"><Car size={30}/><h3>No vehicles yet</h3><p>Add a vehicle to begin.</p></div>}</div></section>
   <section className="panel"><div className="panel-head"><h2>Recent Activity</h2></div><div className="activity-list clean-activity">{activity.map((x,i)=><div key={`${x.date}-${i}`}><div className={`activity-dot ${x.kind}`}/><span><b>{x.title}</b><small>{x.detail}</small></span><time>{new Date(x.date).toLocaleDateString("en-ZM",{day:"2-digit",month:"short"})}</time></div>)}{!activity.length&&<div className="empty"><Clock3 size={30}/><h3>No activity yet</h3></div>}</div></section>
  </div>
 </>;
}
