export type Driver={id:string;driverId:string;name:string;phone:string;licence:string;licenceExpiry:string;status:"Available"|"On Trip"|"Inactive"};
export type TripExpense={id:string;category:string;amount:number;date:string;note:string};
export type CollectionTrip={id:string;tripId:string;vehicleStockId:string;vehicleName:string;driverId:string;driverName:string;collectionPoint:string;destination:string;departureDate:string;expectedArrival:string;advance:number;status:"Assigned"|"In Transit"|"Arrived"|"Reconciled";expenses:TripExpense[]};
const DRIVERS="cm_drivers_v1",TRIPS="cm_trips_v1";
const starterDrivers:Driver[]=[{id:"d1",driverId:"DRV-0001",name:"John Banda",phone:"0977000001",licence:"DL-102943",licenceExpiry:"2027-04-30",status:"On Trip"},{id:"d2",driverId:"DRV-0002",name:"Peter Phiri",phone:"0966000002",licence:"DL-208811",licenceExpiry:"2028-01-15",status:"Available"}];
const starterTrips:CollectionTrip[]=[{id:"t1",tripId:"TRP-2026-0001",vehicleStockId:"CM-2026-0002",vehicleName:"Mazda CX-5 2019",driverId:"d1",driverName:"John Banda",collectionPoint:"Nakonde Border",destination:"Covenant Motors Yard",departureDate:"2026-08-02",expectedArrival:"2026-08-04",advance:8000,status:"In Transit",expenses:[{id:"e1",category:"Fuel",amount:3500,date:"2026-08-02",note:"Initial fuel"},{id:"e2",category:"Accommodation",amount:1200,date:"2026-08-02",note:"One night"}]}];
export const loadDrivers=():Driver[]=>{if(typeof window==="undefined")return starterDrivers;const raw=localStorage.getItem(DRIVERS);if(!raw){localStorage.setItem(DRIVERS,JSON.stringify(starterDrivers));return starterDrivers}return JSON.parse(raw)};
export const saveDrivers=(v:Driver[])=>localStorage.setItem(DRIVERS,JSON.stringify(v));
export const loadTrips=():CollectionTrip[]=>{if(typeof window==="undefined")return starterTrips;const raw=localStorage.getItem(TRIPS);if(!raw){localStorage.setItem(TRIPS,JSON.stringify(starterTrips));return starterTrips}return JSON.parse(raw)};
export const saveTrips=(v:CollectionTrip[])=>localStorage.setItem(TRIPS,JSON.stringify(v));
export const nextDriverId=(drivers:Driver[])=>`DRV-${String(drivers.length+1).padStart(4,"0")}`;
export const nextTripId=(trips:CollectionTrip[])=>`TRP-${new Date().getFullYear()}-${String(trips.length+1).padStart(4,"0")}`;
export const tripSpent=(t:CollectionTrip)=>t.expenses.reduce((s,e)=>s+Number(e.amount),0);
