"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {loadVehicles,nextStockId,saveVehicles} from "@/lib/vehicle-store";
import {Vehicle,VehicleStatus} from "@/lib/types";
import {Currency} from "@/lib/currency";
export default function AddVehiclePage(){
 const router=useRouter();const [stockId,setStockId]=useState("");const [error,setError]=useState("");
 useEffect(()=>setStockId(nextStockId(loadVehicles())),[]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const vehicles=loadVehicles();const vin=String(data.get("vin")||"").trim().toUpperCase();if(vehicles.some(v=>v.vin.toUpperCase()===vin)){setError("This chassis/VIN is already registered.");return;}const purchasePrice=Number(data.get("purchasePrice")||0);const purchaseCurrency=String(data.get("purchaseCurrency")||"ZMW") as Currency;const estimatedSellingPrice=Number(data.get("estimatedSellingPrice")||0);const estimatedSellingCurrency=String(data.get("estimatedSellingCurrency")||purchaseCurrency) as Currency;const collectionRequired=data.get("collectionRequired")==="yes";const vehicle:Vehicle={id:crypto.randomUUID(),stockId:nextStockId(vehicles),vin,engineNumber:String(data.get("engineNumber")||""),registrationNumber:String(data.get("registrationNumber")||""),make:String(data.get("make")||""),model:String(data.get("model")||""),year:Number(data.get("year")||new Date().getFullYear()),colour:String(data.get("colour")||""),purchasePrice,purchaseCurrency,totalCost:purchasePrice,estimatedSellingPrice,estimatedSellingCurrency,currentLocation:String(data.get("location")||""),status:(collectionRequired?"Awaiting Collection":"Available") as VehicleStatus,supplier:String(data.get("supplier")||""),purchaseDate:String(data.get("purchaseDate")||""),createdAt:new Date().toISOString()};saveVehicles([vehicle,...vehicles]);router.push(`/vehicles/${vehicle.id}`);}
 return <><div className="topbar"><div className="title"><h1>Add Vehicle</h1><p>The system will assign stock ID <b>{stockId||"CM-YYYY-0001"}</b>.</p></div></div><form className="form-card" onSubmit={submit}>{error&&<div className="summary-item" style={{marginBottom:16,color:"#b91c1c"}}>{error}</div>}<div className="form-grid"><div className="field"><label>Chassis/VIN *</label><input className="input" name="vin" required/></div><div className="field"><label>Engine Number *</label><input className="input" name="engineNumber" required/></div><div className="field"><label>Registration Number</label><input className="input" name="registrationNumber"/></div><div className="field"><label>Make *</label><input className="input" name="make" required/></div><div className="field"><label>Model *</label><input className="input" name="model" required/></div><div className="field"><label>Manufacture Year *</label><input className="input" name="year" type="number" min="1950" max="2035" required/></div><div className="field"><label>Colour</label><input className="input" name="colour"/></div><div className="field"><label>Supplier *</label><input className="input" name="supplier" required/></div><div className="field"><label>Purchase Currency *</label><select className="select" name="purchaseCurrency" defaultValue="ZMW"><option value="ZMW">Zambian Kwacha (ZMW)</option><option value="USD">US Dollar (USD)</option></select></div><div className="field"><label>Purchase Price *</label><input className="input" name="purchasePrice" type="number" min="0" step="0.01" required/></div><div className="field"><label>Estimated Selling Currency *</label><select className="select" name="estimatedSellingCurrency" defaultValue="ZMW"><option value="ZMW">Zambian Kwacha (ZMW)</option><option value="USD">US Dollar (USD)</option></select></div><div className="field"><label>Estimated Selling Price *</label><input className="input" name="estimatedSellingPrice" type="number" min="0" step="0.01" required/></div><div className="field"><label>Purchase Date *</label><input className="input" name="purchaseDate" type="date" required/></div><div className="field"><label>Current / Collection Location *</label><input className="input" name="location" placeholder="e.g. Nakonde Border" required/></div><div className="field"><label>Collection Required?</label><select className="select" name="collectionRequired"><option value="yes">Yes</option><option value="no">No</option></select></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>router.back()}>Cancel</button><button className="button" type="submit">Register Vehicle</button></div></form></>;
}
