"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Car,ChevronRight,FileText,Filter,MapPin,PenLine,Plus,Search,ShoppingCart,Wallet,X} from "lucide-react";
import {loadVehicles,saveVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {Currency,formatCurrency,normalizeCurrency} from "@/lib/currency";

type SortOption="newest"|"stock"|"vehicle"|"value-high"|"value-low";

export default function VehiclesPage(){
 const [vehicles,setVehicles]=useState<Vehicle[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("All"),[currency,setCurrency]=useState("All"),[sort,setSort]=useState<SortOption>("newest"),[editing,setEditing]=useState<Vehicle|null>(null),[notice,setNotice]=useState("");
 useEffect(()=>setVehicles(loadVehicles()),[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),2800);return()=>clearTimeout(timer)},[notice]);
 const filtered=useMemo(()=>vehicles.filter(v=>{const text=`${v.stockId} ${v.vin} ${v.registrationNumber||""} ${v.make} ${v.model} ${v.supplier} ${v.currentLocation}`.toLowerCase();const matchesText=text.includes(query.toLowerCase());const matchesStatus=status==="All"||v.status===status;const matchesCurrency=currency==="All"||normalizeCurrency(v.estimatedSellingCurrency)===currency;return matchesText&&matchesStatus&&matchesCurrency}).sort((a,b)=>{if(sort==="stock")return a.stockId.localeCompare(b.stockId);if(sort==="vehicle")return `${a.make} ${a.model}`.localeCompare(`${b.make} ${b.model}`);if(sort==="value-high")return Number(b.estimatedSellingPrice||0)-Number(a.estimatedSellingPrice||0);if(sort==="value-low")return Number(a.estimatedSellingPrice||0)-Number(b.estimatedSellingPrice||0);return new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()}),[vehicles,query,status,currency,sort]);
 const activeStock=vehicles.filter(v=>v.status!=="Sold"),available=vehicles.filter(v=>v.status==="Available").length,transit=vehicles.filter(v=>v.status==="In Transit").length;
 const zmwValue=activeStock.filter(v=>normalizeCurrency(v.estimatedSellingCurrency)==="ZMW").reduce((s,v)=>s+Number(v.estimatedSellingPrice||0),0),usdValue=activeStock.filter(v=>normalizeCurrency(v.estimatedSellingCurrency)==="USD").reduce((s,v)=>s+Number(v.estimatedSellingPrice||0),0);
 const badge=(s:string)=>s==="Available"?"available":s==="In Transit"?"transit":s==="Sold"?"sold":"awaiting";
 function saveValuation(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),estimatedSellingPrice=Number(f.get("estimatedSellingPrice")||0),estimatedSellingCurrency=String(f.get("estimatedSellingCurrency")||"ZMW") as Currency;const next=vehicles.map(v=>v.id===editing.id?{...v,estimatedSellingPrice,estimatedSellingCurrency}:v);saveVehicles(next);setVehicles(next);setNotice(`${editing.stockId} valuation updated`);setEditing(null)}
 const clearFilters=()=>{setQuery("");setStatus("All");setCurrency("All");setSort("newest")};
 return <>
  {notice&&<div className="app-toast"><span>✓</span>{notice}</div>}
  <div className="page-heading"><div><span className="eyebrow dark">INVENTORY MANAGEMENT</span><h1>Vehicle Stock</h1><p>Manage vehicle availability, landed cost, estimated selling value and deal jackets from one register.</p></div><Link className="button" href="/vehicles/new"><Plus size={18}/><span>Add Vehicle</span></Link></div>
  <div className="inventory-summary"><div className="mini-stat"><Car/><span><small>Total vehicles</small><b>{vehicles.length}</b></span></div><div className="mini-stat"><MapPin/><span><small>Available</small><b>{available}</b></span></div><div className="mini-stat"><Car/><span><small>In transit</small><b>{transit}</b></span></div><div className="mini-stat dual-value-stat"><Wallet/><span><small>Estimated stock value</small><b>{formatCurrency(zmwValue,"ZMW")}</b><b>{formatCurrency(usdValue,"USD")}</b></span></div></div>
  {editing&&<form className="form-card section-gap professional-form valuation-editor" onSubmit={saveValuation}><div className="form-heading"><div><span className="eyebrow dark">STOCK VALUATION</span><h2>{editing.stockId} · {editing.make} {editing.model}</h2><p>Update the expected selling amount. Purchase cost and completed sales remain unchanged.</p></div><button type="button" className="icon-button" onClick={()=>setEditing(null)} aria-label="Close"><X size={18}/></button></div><div className="form-grid"><div className="field"><label>Currency</label><select className="select" name="estimatedSellingCurrency" defaultValue={normalizeCurrency(editing.estimatedSellingCurrency)}><option value="ZMW">Zambian Kwacha (ZMW)</option><option value="USD">US Dollar (USD)</option></select></div><div className="field"><label>Estimated selling price</label><input className="input" name="estimatedSellingPrice" type="number" min="0" step="0.01" defaultValue={editing.estimatedSellingPrice||0} required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="button">Save Valuation</button></div></form>}
  <section className="panel inventory-panel"><div className="inventory-toolbar advanced-toolbar"><div className="search-control"><Search size={18}/><input placeholder="Search stock ID, VIN, vehicle, supplier or location" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-control"><Filter size={17}/><select aria-label="Status filter" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Awaiting Collection</option><option>In Transit</option><option>Available</option><option>Reserved</option><option>Under Repair</option><option>Sold</option></select></div><div className="filter-control"><select aria-label="Valuation currency filter" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="All">All currencies</option><option value="ZMW">ZMW</option><option value="USD">USD</option></select></div><div className="filter-control"><select aria-label="Sort vehicles" value={sort} onChange={e=>setSort(e.target.value as SortOption)}><option value="newest">Newest first</option><option value="stock">Stock ID</option><option value="vehicle">Vehicle name</option><option value="value-high">Highest value</option><option value="value-low">Lowest value</option></select></div><span className="result-count">{filtered.length} of {vehicles.length}</span>{(query||status!=="All"||currency!=="All"||sort!=="newest")&&<button className="clear-filter" type="button" onClick={clearFilters}>Clear</button>}</div>
   <div className="desktop-stock-table table-wrap"><table><thead><tr><th>Stock ID</th><th>Vehicle</th><th>Status</th><th>Landed Cost</th><th>Estimated Selling</th><th>Actions</th></tr></thead><tbody>{filtered.map(v=>{const purchaseCurrency=normalizeCurrency(v.purchaseCurrency),valuationCurrency=normalizeCurrency(v.estimatedSellingCurrency);return <tr key={v.id}><td><Link className="stock-link" href={`/vehicles/${v.id}`}>{v.stockId}</Link><small>{v.registrationNumber||"Not registered"}</small></td><td><div className="vehicle-cell"><div className="vehicle-thumb"><Car size={19}/></div><span><b>{v.make} {v.model}</b><small>{v.year} · {v.currentLocation}</small></span></div></td><td><span className={`badge ${badge(v.status)}`}>{v.status}</span></td><td><b>{formatCurrency(v.totalCost,purchaseCurrency)}</b><small>{purchaseCurrency}</small></td><td><b>{v.estimatedSellingPrice?formatCurrency(v.estimatedSellingPrice,valuationCurrency):"Not valued"}</b><small>{valuationCurrency}</small></td><td><div className="row-actions"><button className="button secondary compact-button" type="button" onClick={()=>setEditing(v)}><PenLine size={14}/>Value</button><Link className="button secondary compact-button" href={`/vehicles/${v.id}`}><FileText size={14}/>Deal Jacket</Link>{v.status!=="Sold"&&<Link className="row-action" title="Record sale" href="/sales"><ShoppingCart size={16}/></Link>}<Link className="row-action" title="Open vehicle" href={`/vehicles/${v.id}`}><ChevronRight size={18}/></Link></div></td></tr>})}</tbody></table></div>
   <div className="mobile-stock-list">{filtered.map(v=>{const purchaseCurrency=normalizeCurrency(v.purchaseCurrency),valuationCurrency=normalizeCurrency(v.estimatedSellingCurrency);return <article className="mobile-stock-card" key={v.id}><Link href={`/vehicles/${v.id}`} className="mobile-stock-top"><div className="vehicle-thumb"><Car size={19}/></div><div><b>{v.make} {v.model} {v.year}</b><small>{v.stockId} · {v.registrationNumber||"Not registered"}</small></div><ChevronRight size={18}/></Link><div className="mobile-stock-meta"><span><small>Status</small><b className={`badge ${badge(v.status)}`}>{v.status}</b></span><span><small>Landed cost</small><b>{formatCurrency(v.totalCost,purchaseCurrency)}</b></span><span><small>Estimated selling</small><b>{v.estimatedSellingPrice?formatCurrency(v.estimatedSellingPrice,valuationCurrency):"Not valued"}</b></span></div><div className="mobile-card-actions"><button className="button secondary compact-button" type="button" onClick={()=>setEditing(v)}><PenLine size={15}/>Edit Value</button><Link className="button secondary compact-button" href={`/vehicles/${v.id}`}><FileText size={15}/>Deal Jacket</Link></div></article>})}</div>
   {filtered.length===0&&<div className="empty"><Search size={32}/><h3>No matching vehicles</h3><p>Change the search or filters to view other stock.</p><button className="button secondary" type="button" onClick={clearFilters}>Reset filters</button></div>}
  </section>
 </>;
}
