"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Car,ChevronRight,Filter,MapPin,Plus,Search,Wallet} from "lucide-react";
import {loadVehicles,saveVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {Currency,formatCurrency,normalizeCurrency} from "@/lib/currency";
export default function VehiclesPage(){
 const [vehicles,setVehicles]=useState<Vehicle[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("All"),[editing,setEditing]=useState<Vehicle|null>(null);
 useEffect(()=>setVehicles(loadVehicles()),[]);
 const filtered=useMemo(()=>vehicles.filter(v=>{const text=`${v.stockId} ${v.vin} ${v.registrationNumber||""} ${v.make} ${v.model}`.toLowerCase();return text.includes(query.toLowerCase())&&(status==="All"||v.status===status)}),[vehicles,query,status]);
 const activeStock=vehicles.filter(v=>v.status!=="Sold"),available=vehicles.filter(v=>v.status==="Available").length,transit=vehicles.filter(v=>v.status==="In Transit").length;
 const zmwStock=activeStock.filter(v=>normalizeCurrency(v.estimatedSellingCurrency)==="ZMW"),usdStock=activeStock.filter(v=>normalizeCurrency(v.estimatedSellingCurrency)==="USD");
 const zmwValue=zmwStock.reduce((s,v)=>s+Number(v.estimatedSellingPrice||0),0),usdValue=usdStock.reduce((s,v)=>s+Number(v.estimatedSellingPrice||0),0);
 const badge=(s:string)=>s==="Available"?"available":s==="In Transit"?"transit":s==="Sold"?"sold":"awaiting";
 function saveValuation(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),estimatedSellingPrice=Number(f.get("estimatedSellingPrice")||0),estimatedSellingCurrency=String(f.get("estimatedSellingCurrency")||"ZMW") as Currency;const next=vehicles.map(v=>v.id===editing.id?{...v,estimatedSellingPrice,estimatedSellingCurrency}:v);saveVehicles(next);setVehicles(next);setEditing(null)}
 return <>
  <div className="page-heading"><div><span className="eyebrow dark">INVENTORY MANAGEMENT</span><h1>Vehicle Stock</h1><p>Track landed cost and editable estimated selling value before the actual sale.</p></div><Link className="button" href="/vehicles/new"><Plus size={18}/><span>Add Vehicle</span></Link></div>
  <div className="inventory-summary"><div className="mini-stat"><Car/><span><small>Total vehicles</small><b>{vehicles.length}</b></span></div><div className="mini-stat"><MapPin/><span><small>Available</small><b>{available}</b></span></div><div className="mini-stat"><Car/><span><small>In transit</small><b>{transit}</b></span></div><div className="mini-stat"><Wallet/><span><small>Estimated stock selling value</small><b>{formatCurrency(zmwValue,"ZMW")}</b><small>{formatCurrency(usdValue,"USD")}</small></span></div></div>
  {editing&&<form className="form-card section-gap" onSubmit={saveValuation}><div className="form-heading"><div><span className="eyebrow dark">STOCK VALUATION</span><h2>{editing.stockId} · {editing.make} {editing.model}</h2><p>Change the estimated selling amount or currency. This does not alter purchase cost or an actual sale.</p></div></div><div className="form-grid"><div className="field"><label>Estimated Selling Currency</label><select className="select" name="estimatedSellingCurrency" defaultValue={normalizeCurrency(editing.estimatedSellingCurrency)}><option value="ZMW">ZMW</option><option value="USD">USD</option></select></div><div className="field"><label>Estimated Selling Price</label><input className="input" name="estimatedSellingPrice" type="number" min="0" step="0.01" defaultValue={editing.estimatedSellingPrice||0} required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="button">Save Valuation</button></div></form>}
  <section className="panel inventory-panel"><div className="inventory-toolbar"><div className="search-control"><Search size={18}/><input placeholder="Search stock ID, VIN, registration, make or model" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-control"><Filter size={17}/><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Awaiting Collection</option><option>In Transit</option><option>Available</option><option>Reserved</option><option>Under Repair</option><option>Sold</option></select></div><span className="result-count">{filtered.length} result{filtered.length===1?"":"s"}</span></div>
   <div className="desktop-stock-table table-wrap"><table><thead><tr><th>Stock ID</th><th>Vehicle</th><th>Status</th><th>Landed Cost</th><th>Estimated Selling Price</th><th>Valuation Currency</th><th/></tr></thead><tbody>{filtered.map(v=>{const purchaseCurrency=normalizeCurrency(v.purchaseCurrency),valuationCurrency=normalizeCurrency(v.estimatedSellingCurrency);return <tr key={v.id}><td><Link className="stock-link" href={`/vehicles/${v.id}`}>{v.stockId}</Link></td><td><div className="vehicle-cell"><div className="vehicle-thumb"><Car size={19}/></div><span><b>{v.make} {v.model}</b><small>{v.year} · {v.currentLocation}</small></span></div></td><td><span className={`badge ${badge(v.status)}`}>{v.status}</span></td><td><b>{formatCurrency(v.totalCost,purchaseCurrency)}</b><small>{purchaseCurrency}</small></td><td><b>{v.estimatedSellingPrice?formatCurrency(v.estimatedSellingPrice,valuationCurrency):"Not valued"}</b></td><td><b>{valuationCurrency}</b></td><td><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><button className="button secondary compact-button" onClick={()=>setEditing(v)}>Edit Value</button><Link className="row-action" href={`/vehicles/${v.id}`}><ChevronRight size={18}/></Link></div></td></tr>})}</tbody></table></div>
   <div className="mobile-stock-list">{filtered.map(v=>{const purchaseCurrency=normalizeCurrency(v.purchaseCurrency),valuationCurrency=normalizeCurrency(v.estimatedSellingCurrency);return <div className="mobile-stock-card" key={v.id}><Link href={`/vehicles/${v.id}`} className="mobile-stock-top"><div className="vehicle-thumb"><Car size={19}/></div><div><b>{v.make} {v.model} {v.year}</b><small>{v.stockId} · {v.registrationNumber||"Not registered"}</small></div><ChevronRight size={18}/></Link><div className="mobile-stock-meta"><span><small>Status</small><b className={`badge ${badge(v.status)}`}>{v.status}</b></span><span><small>Landed cost</small><b>{formatCurrency(v.totalCost,purchaseCurrency)}</b></span><span><small>Estimated selling</small><b>{v.estimatedSellingPrice?formatCurrency(v.estimatedSellingPrice,valuationCurrency):"Not valued"}</b></span></div><button className="button secondary compact-button" style={{marginTop:10,width:"100%",justifyContent:"center"}} onClick={()=>setEditing(v)}>Edit Estimated Value</button></div>})}</div>
   {filtered.length===0&&<div className="empty"><Search size={32}/><h3>No matching vehicles</h3><p>Try changing the search term or status filter.</p></div>}
  </section>
 </>;
}
