"use client";
import {FormEvent,useEffect,useState} from "react";
import {BadgeCheck,Building2,Hash,Save,Settings2,ShieldCheck} from "lucide-react";
type Settings={companyName:string;tradingName:string;phone:string;email:string;address:string;defaultCurrency:"ZMW"|"USD";stockPrefix:string;salePrefix:string};
const defaults:Settings={companyName:"Covenant Motors",tradingName:"Covenant Motors",phone:"",email:"",address:"Lusaka, Zambia",defaultCurrency:"ZMW",stockPrefix:"CM",salePrefix:"SAL"};
export default function SettingsPage(){
 const [settings,setSettings]=useState<Settings>(defaults),[saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem("cm_settings");if(raw)setSettings({...defaults,...JSON.parse(raw)})}catch{}},[]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();localStorage.setItem("cm_settings",JSON.stringify(settings));setSaved(true);setTimeout(()=>setSaved(false),2800)}
 return <>
 {saved&&<div className="toast-message"><BadgeCheck size={18}/><span>Settings saved successfully.</span></div>}
 <div className="page-heading"><div><span className="eyebrow dark">ADMINISTRATION</span><h1>Settings</h1><p>Manage company identity, transaction defaults and document numbering.</p></div></div>
 <form className="settings-workspace" onSubmit={submit}>
  <section className="panel settings-section"><div className="panel-head"><div><h2><Building2 size={18}/>Company Profile</h2><p>Information used across the workspace and future reports.</p></div></div><div className="panel-body form-grid"><div className="field"><label>Registered company name</label><input className="input" value={settings.companyName} onChange={e=>setSettings({...settings,companyName:e.target.value})}/></div><div className="field"><label>Trading name</label><input className="input" value={settings.tradingName} onChange={e=>setSettings({...settings,tradingName:e.target.value})}/></div><div className="field"><label>Phone number</label><input className="input" value={settings.phone} onChange={e=>setSettings({...settings,phone:e.target.value})}/></div><div className="field"><label>Email address</label><input className="input" type="email" value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})}/></div><div className="field full"><label>Business address</label><input className="input" value={settings.address} onChange={e=>setSettings({...settings,address:e.target.value})}/></div></div></section>
  <section className="panel settings-section"><div className="panel-head"><div><h2><Settings2 size={18}/>Transaction Defaults</h2><p>Defaults only assist data entry; users may still select the actual transaction currency.</p></div></div><div className="panel-body form-grid"><div className="field"><label>Default entry currency</label><select className="select" value={settings.defaultCurrency} onChange={e=>setSettings({...settings,defaultCurrency:e.target.value as "ZMW"|"USD"})}><option value="ZMW">Zambian Kwacha (ZMW)</option><option value="USD">US Dollar (USD)</option></select></div><div className="settings-note"><ShieldCheck size={18}/><span>Original transaction currencies remain unchanged. The system does not automatically convert USD and ZMW.</span></div></div></section>
  <section className="panel settings-section"><div className="panel-head"><div><h2><Hash size={18}/>Numbering</h2><p>Prefixes used when new stock and sales references are generated.</p></div></div><div className="panel-body form-grid"><div className="field"><label>Stock ID prefix</label><input className="input" maxLength={8} value={settings.stockPrefix} onChange={e=>setSettings({...settings,stockPrefix:e.target.value.toUpperCase()})}/></div><div className="field"><label>Sale ID prefix</label><input className="input" maxLength={8} value={settings.salePrefix} onChange={e=>setSettings({...settings,salePrefix:e.target.value.toUpperCase()})}/></div></div></section>
  <div className="settings-save"><button className="button" type="submit"><Save size={17}/>Save Settings</button></div>
 </form>
 </>;
}
