"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {BadgeCheck,FileText,Filter,PenLine,Plus,Search,ShoppingCart,X} from "lucide-react";
import {loadCustomers,Customer} from "@/lib/customer-store";
import {loadVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {formatCurrency} from "@/lib/currency";
import {loadQuotations,nextQuotationId,Quotation,QuotationStatus,saveQuotations} from "@/lib/quotation-store";

const money=(n:number)=>formatCurrency(n,"ZMW");
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const effectiveStatus=(q:Quotation):QuotationStatus=>q.status!=="Converted"&&q.status!=="Accepted"&&q.validUntil<today()?"Expired":q.status;

export default function QuotationsPage(){
 const [items,setItems]=useState<Quotation[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[show,setShow]=useState(false),[editing,setEditing]=useState<Quotation|null>(null),[vehicleId,setVehicleId]=useState(""),[price,setPrice]=useState(""),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState("All"),[message,setMessage]=useState("");
 useEffect(()=>{setItems(loadQuotations());setVehicles(loadVehicles());setCustomers(loadCustomers())},[]);
 const available=useMemo(()=>vehicles.filter(v=>v.status!=="Sold"||v.id===editing?.vehicleId),[vehicles,editing]);
 const filtered=useMemo(()=>items.filter(q=>`${q.quotationId} ${q.stockId} ${q.vehicleName} ${q.customerName}`.toLowerCase().includes(query.toLowerCase())&&(statusFilter==="All"||effectiveStatus(q)===statusFilter)),[items,query,statusFilter]);
 const totals={all:items.length,open:items.filter(q=>["Draft","Sent"].includes(effectiveStatus(q))).length,accepted:items.filter(q=>effectiveStatus(q)==="Accepted").length,converted:items.filter(q=>q.status==="Converted").length};
 const notify=(text:string)=>{setMessage(text);window.setTimeout(()=>setMessage(""),3000)};
 function resetForm(){setShow(false);setEditing(null);setVehicleId("");setPrice("")}
 function chooseVehicle(id:string){setVehicleId(id);if(editing)return;const v=vehicles.find(x=>x.id===id);if(v)setPrice(String(v.estimatedSellingPriceZmw??v.estimatedSellingPrice??""))}
 function startEdit(q:Quotation){if(q.status==="Converted")return;setEditing(q);setShow(true);setVehicleId(q.vehicleId);setPrice(String(q.quotedPrice));window.scrollTo({top:0,behavior:"smooth"})}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),vehicle=vehicles.find(v=>v.id===vehicleId),customer=customers.find(c=>c.id===String(f.get("customerId")));if(!vehicle||!customer)return notify("Select a vehicle and customer.");const quotedPrice=Number(price||0);if(quotedPrice<=0)return notify("Enter a valid quoted price.");const status=String(f.get("status")) as QuotationStatus;const quote:Quotation={...(editing||{} as Quotation),id:editing?.id||crypto.randomUUID(),quotationId:editing?.quotationId||nextQuotationId(items),vehicleId:vehicle.id,stockId:vehicle.stockId,vehicleName:`${vehicle.make} ${vehicle.model} ${vehicle.year}`,customerId:customer.id,customerName:customer.name,quotationDate:String(f.get("quotationDate")),validUntil:String(f.get("validUntil")),quotedPrice,status,paymentTerms:String(f.get("paymentTerms")||""),notes:String(f.get("notes")||""),createdAt:editing?.createdAt||new Date().toISOString()};const next=editing?items.map(x=>x.id===editing.id?quote:x):[quote,...items];saveQuotations(next);setItems(next);notify(editing?`${quote.quotationId} updated.`:`${quote.quotationId} created.`);resetForm()}
 function updateStatus(q:Quotation,status:QuotationStatus){if(q.status==="Converted")return;const next=items.map(x=>x.id===q.id?{...x,status}:x);saveQuotations(next);setItems(next);notify(`${q.quotationId} marked ${status}.`)}
 const badge=(s:QuotationStatus)=>s==="Accepted"||s==="Converted"?"available":s==="Expired"?"sold":"awaiting";
 return <>{message&&<div className="app-toast"><span>✓</span>{message}</div>}
 <div className="page-heading"><div><span className="eyebrow dark">SALES · PRE-SALE</span><h1>Quotations</h1><p>Create customer quotations, track acceptance and convert approved quotes into sales.</p></div><button className="button" type="button" onClick={()=>show?resetForm():setShow(true)}><Plus size={18}/>{show?"Close Form":"New Quotation"}</button></div>
 <div className="inventory-summary"><div className="mini-stat"><FileText/><span><small>Total Quotations</small><b>{totals.all}</b></span></div><div className="mini-stat"><FileText/><span><small>Open</small><b>{totals.open}</b></span></div><div className="mini-stat"><BadgeCheck/><span><small>Accepted</small><b>{totals.accepted}</b></span></div><div className="mini-stat"><ShoppingCart/><span><small>Converted to Sale</small><b>{totals.converted}</b></span></div></div>
 {show&&<form key={editing?.id||"new"} className="form-card professional-form quotation-form" onSubmit={submit}><div className="form-heading"><div><span className="eyebrow dark">{editing?"EDIT QUOTATION":"NEW QUOTATION"}</span><h2>{editing?editing.quotationId:"Create Quotation"}</h2><p>A quotation does not sell or reserve the vehicle until it is converted to a sale.</p></div><button type="button" className="icon-button" onClick={resetForm}><X size={18}/></button></div><div className="form-grid"><div className="field"><label>Vehicle</label><select className="select" required value={vehicleId} onChange={e=>chooseVehicle(e.target.value)} disabled={!!editing}><option value="">Select vehicle</option>{available.map(v=><option value={v.id} key={v.id}>{v.stockId} — {v.make} {v.model}</option>)}</select></div><div className="field"><label>Customer</label><select className="select" name="customerId" required defaultValue={editing?.customerId||""}><option value="">Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.customerId} — {c.name}</option>)}</select></div><div className="field"><label>Quoted Price (ZMW)</label><input className="input" type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></div><div className="field"><label>Status</label><select className="select" name="status" defaultValue={editing?.status||"Draft"}><option>Draft</option><option>Sent</option><option>Accepted</option></select></div><div className="field"><label>Quotation Date</label><input className="input" name="quotationDate" type="date" defaultValue={editing?.quotationDate||today()} required/></div><div className="field"><label>Valid Until</label><input className="input" name="validUntil" type="date" defaultValue={editing?.validUntil||plusDays(7)} required/></div><div className="field full"><label>Payment Terms</label><input className="input" name="paymentTerms" defaultValue={editing?.paymentTerms||"Payment as agreed before vehicle handover"} placeholder="e.g. 50% deposit, balance before handover"/></div><div className="field full"><label>Notes / Terms</label><textarea className="input quotation-notes" name="notes" defaultValue={editing?.notes||""} placeholder="Optional quotation notes or conditions"/></div></div><div className="actions"><button className="button secondary" type="button" onClick={resetForm}>Cancel</button><button className="button">{editing?"Save Changes":"Create Quotation"}</button></div></form>}
 <section className="panel quotation-register"><div className="panel-head"><h2>Quotation Register</h2><span className="badge sold">{items.length} quote{items.length===1?"":"s"}</span></div><div className="inventory-toolbar"><div className="search-control"><Search size={17}/><input placeholder="Search quotation ID, stock ID, vehicle or customer" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-control"><Filter size={16}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>All</option><option>Draft</option><option>Sent</option><option>Accepted</option><option>Expired</option><option>Converted</option></select></div></div><div className="desktop-quotation-table table-wrap"><table><thead><tr><th>Quotation ID</th><th>Stock ID</th><th>Vehicle</th><th>Customer</th><th>Quoted Price</th><th>Valid Until</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(q=>{const status=effectiveStatus(q);return <tr key={q.id}><td><b>{q.quotationId}</b><small>{q.quotationDate}</small></td><td><b>{q.stockId}</b></td><td>{q.vehicleName}</td><td>{q.customerName}</td><td><b>{money(q.quotedPrice)}</b></td><td>{q.validUntil}</td><td><select className={`status-select badge ${badge(status)}`} value={status} disabled={status==="Expired"||q.status==="Converted"} onChange={e=>updateStatus(q,e.target.value as QuotationStatus)}><option>Draft</option><option>Sent</option><option>Accepted</option>{status==="Expired"&&<option>Expired</option>}{q.status==="Converted"&&<option>Converted</option>}</select></td><td><div className="row-actions"><Link className="button secondary compact-button" href={`/quotations/${q.id}`}><FileText size={14}/>View</Link>{q.status!=="Converted"&&status!=="Expired"&&<button className="button secondary compact-button" type="button" onClick={()=>startEdit(q)}><PenLine size={14}/>Edit</button>}{status==="Accepted"&&<Link className="button compact-button" href={`/sales?quotation=${q.id}&vehicle=${q.vehicleId}&customer=${q.customerId}&price=${q.quotedPrice}`}><ShoppingCart size={14}/>Convert</Link>}</div></td></tr>})}</tbody></table></div>
 <div className="mobile-quotation-list">{filtered.map(q=>{const status=effectiveStatus(q);return <article className="mobile-record-card mobile-quotation-card" key={q.id}><div className="mobile-record-head"><div><b>{q.quotationId}</b><small>{q.quotationDate}</small></div><span className={`badge ${badge(status)}`}>{status}</span></div><div className="mobile-quote-grid"><span><small>Stock ID</small><b>{q.stockId}</b></span><span><small>Vehicle</small><b>{q.vehicleName}</b></span><span><small>Customer</small><b>{q.customerName}</b></span><span><small>Quoted Price</small><b>{money(q.quotedPrice)}</b></span><span><small>Valid Until</small><b>{q.validUntil}</b></span></div><div className="mobile-card-actions"><Link className="button secondary compact-button" href={`/quotations/${q.id}`}><FileText size={14}/>View</Link>{q.status!=="Converted"&&status!=="Expired"&&<button className="button secondary compact-button" type="button" onClick={()=>startEdit(q)}><PenLine size={14}/>Edit</button>}{status==="Accepted"&&<Link className="button compact-button" href={`/sales?quotation=${q.id}&vehicle=${q.vehicleId}&customer=${q.customerId}&price=${q.quotedPrice}`}><ShoppingCart size={14}/>Convert to Sale</Link>}</div></article>})}</div>
 {!filtered.length&&<div className="empty"><FileText size={34}/><h3>No quotations found</h3><p>{items.length?"Change the search or status filter.":"Create the first customer quotation to begin."}</p></div>}</section></>;
}
