"use client";
import {useEffect,useMemo,useState} from "react";
import {Plus,Receipt} from "lucide-react";
import {loadVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {loadVehicleExpenses,saveVehicleExpenses,VehicleExpense} from "@/lib/ledger-store";
import {Currency,formatCurrency,groupCurrencyAmounts,normalizeCurrency} from "@/lib/currency";
const categories=["Duty","Clearing","Border Charges","Transport","Fuel","Accommodation","Meals","Driver Allowance","Repairs","Parts","Registration","Insurance","Car Wash","Advertising","Other"];
export default function ExpensesPage(){const [vehicles,setVehicles]=useState<Vehicle[]>([]);const [items,setItems]=useState<VehicleExpense[]>([]);const [open,setOpen]=useState(false);useEffect(()=>{setVehicles(loadVehicles());setItems(loadVehicleExpenses())},[]);const totals=useMemo(()=>groupCurrencyAmounts(items,x=>x.amount,x=>x.currency),[items]);
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const expense:VehicleExpense={id:crypto.randomUUID(),vehicleId:String(f.get("vehicleId")),category:String(f.get("category")),description:String(f.get("description")),amount:Number(f.get("amount")),currency:String(f.get("currency")||"ZMW") as Currency,date:String(f.get("date")),reference:String(f.get("reference")||""),createdAt:new Date().toISOString()};const next=[expense,...items];saveVehicleExpenses(next);setItems(next);setOpen(false);e.currentTarget.reset()}
 return <><div className="topbar"><div className="title"><h1>Vehicle Expenses</h1><p>Record every cost exactly as paid in ZMW or USD. No automatic conversion is applied.</p></div><button className="button" onClick={()=>setOpen(!open)}><Plus size={18}/><span>Add Expense</span></button></div><div className="cards"><div className="card metric"><div><div className="metric-label">Vehicle Expenses — ZMW</div><div className="metric-value">{formatCurrency(totals.ZMW,"ZMW")}</div></div><div className="metric-icon"><Receipt/></div></div><div className="card"><div className="metric-label">Vehicle Expenses — USD</div><div className="metric-value">{formatCurrency(totals.USD,"USD")}</div></div><div className="card"><div className="metric-label">Expense Entries</div><div className="metric-value">{items.length}</div></div></div>
 {open&&<form className="form-card section-gap" onSubmit={submit}><div className="form-grid"><div className="field"><label>Vehicle</label><select className="select" name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.stockId} — {v.make} {v.model}</option>)}</select></div><div className="field"><label>Category</label><select className="select" name="category" required>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Currency</label><select className="select" name="currency" defaultValue="ZMW"><option value="ZMW">ZMW</option><option value="USD">USD</option></select></div><div className="field"><label>Amount</label><input className="input" name="amount" type="number" min="0" step="0.01" required/></div><div className="field"><label>Date</label><input className="input" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Reference</label><input className="input" name="reference" placeholder="Receipt or invoice number"/></div><div className="field"><label>Description</label><input className="input" name="description" required placeholder="What was paid for?"/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button">Save Expense</button></div></form>}
 <section className="panel"><div className="panel-head"><h2>Vehicle Expense Ledger</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Stock ID</th><th>Category</th><th>Description</th><th>Reference</th><th>Currency</th><th>Amount</th></tr></thead><tbody>{items.map(x=>{const v=vehicles.find(y=>y.id===x.vehicleId);const currency=normalizeCurrency(x.currency);return <tr key={x.id}><td>{x.date}</td><td><b>{v?.stockId||"Unknown"}</b></td><td>{x.category}</td><td>{x.description}</td><td>{x.reference||"—"}</td><td><b>{currency}</b></td><td><b>{formatCurrency(x.amount,currency)}</b></td></tr>})}</tbody></table>{!items.length&&<div className="empty">No vehicle expenses recorded.</div>}</div></section></>;
}
