"use client";
import {useEffect,useMemo,useState} from "react";
import {Car,Filter,Plus,Receipt,Search,X} from "lucide-react";
import {loadVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {loadVehicleExpenses,saveVehicleExpenses,VehicleExpense} from "@/lib/ledger-store";
import {formatCurrency} from "@/lib/currency";

const categories=["Duty","Clearing","Border Charges","Transport","Fuel","Accommodation","Meals","Driver Allowance","Repairs","Parts","Registration","Insurance","Car Wash","Advertising","Other"];
const amountValue=(x:VehicleExpense)=>Number(x.amountZmw??x.amount??0);

export default function ExpensesPage(){
 const [vehicles,setVehicles]=useState<Vehicle[]>([]),[items,setItems]=useState<VehicleExpense[]>([]),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[message,setMessage]=useState("");
 useEffect(()=>{setVehicles(loadVehicles());setItems(loadVehicleExpenses())},[]);
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(""),2800);return()=>clearTimeout(timer)},[message]);
 const vehicleFor=(id:string)=>vehicles.find(v=>v.id===id);
 const total=useMemo(()=>items.reduce((sum,x)=>sum+amountValue(x),0),[items]);
 const vehiclesWithExpenses=new Set(items.map(x=>x.vehicleId)).size;
 const filtered=useMemo(()=>items.filter(x=>{const v=vehicleFor(x.vehicleId),text=`${v?.stockId||""} ${v?.make||""} ${v?.model||""} ${x.category} ${x.description} ${x.reference||""}`.toLowerCase();return text.includes(query.toLowerCase())&&(category==="All"||x.category===category)}),[items,vehicles,query,category]);
 function closeForm(){setOpen(false)}
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),amount=Number(f.get("amount")||0);const expense:VehicleExpense={id:crypto.randomUUID(),vehicleId:String(f.get("vehicleId")),category:String(f.get("category")),description:String(f.get("description")),amount,currency:"ZMW",amountZmw:amount,date:String(f.get("date")),reference:String(f.get("reference")||""),createdAt:new Date().toISOString()};const next=[expense,...items];saveVehicleExpenses(next);setItems(next);closeForm();setMessage("Expense saved successfully.");form.reset()}
 return <>
 {message&&<div className="app-toast"><span>✓</span>{message}</div>}
 <div className="page-heading"><div><span className="eyebrow dark">VEHICLE COSTS</span><h1>Vehicle Expenses</h1><p>Record and review costs that contribute to each vehicle's total cost.</p></div><button className="button" type="button" onClick={()=>open?closeForm():setOpen(true)}><Plus size={18}/>{open?"Close Form":"Add Expense"}</button></div>
 <div className="inventory-summary expense-summary"><div className="mini-stat"><Receipt/><span><small>Total Vehicle Expenses</small><b>{formatCurrency(total,"ZMW")}</b></span></div><div className="mini-stat"><Receipt/><span><small>Expense Entries</small><b>{items.length}</b></span></div><div className="mini-stat"><Car/><span><small>Vehicles with Expenses</small><b>{vehiclesWithExpenses}</b></span></div></div>
 {open&&<form className="form-card section-gap professional-form" onSubmit={submit}><div className="form-heading"><div><span className="eyebrow dark">NEW EXPENSE</span><h2>Record Vehicle Expense</h2><p>Select the vehicle and capture the cost in Zambian Kwacha.</p></div><button type="button" className="icon-button" onClick={closeForm} aria-label="Close"><X size={18}/></button></div><div className="form-grid"><div className="field"><label>Vehicle</label><select className="select" name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.stockId} — {v.make} {v.model}</option>)}</select></div><div className="field"><label>Category</label><select className="select" name="category" required>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Amount (ZMW)</label><input className="input" name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Date</label><input className="input" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Reference</label><input className="input" name="reference" placeholder="Receipt or invoice number"/></div><div className="field full"><label>Description</label><input className="input" name="description" required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={closeForm}>Cancel</button><button className="button">Save Expense</button></div></form>}
 <section className="panel expense-register"><div className="panel-head"><div><h2>Expense Register</h2><small className="muted">{filtered.length} of {items.length} expense entr{items.length===1?"y":"ies"}</small></div></div><div className="inventory-toolbar expense-toolbar"><div className="search-control"><Search size={17}/><input placeholder="Search stock ID, vehicle, category, description or reference" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="clear-search" type="button" onClick={()=>setQuery("")} aria-label="Clear search"><X size={15}/></button>}</div><div className="filter-control"><Filter size={16}/><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filter by category"><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div></div>
 <div className="desktop-expense-table table-wrap"><table><thead><tr><th>Date</th><th>Stock ID</th><th>Vehicle</th><th>Category</th><th>Description</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{filtered.map(x=>{const v=vehicleFor(x.vehicleId);return <tr key={x.id}><td>{x.date}</td><td><b>{v?.stockId||"Unknown"}</b></td><td>{v?<><b>{v.make} {v.model}</b><br/><small>{v.year}</small></>:"Vehicle unavailable"}</td><td>{x.category}</td><td>{x.description}</td><td>{x.reference||"—"}</td><td><b>{formatCurrency(amountValue(x),"ZMW")}</b></td></tr>})}</tbody></table></div>
 <div className="mobile-expense-list">{filtered.map(x=>{const v=vehicleFor(x.vehicleId);return <article className="mobile-record-card mobile-expense-card" key={x.id}><div className="mobile-record-head"><div><b>{v?.stockId||"Unknown"}</b><small>{v?`${v.make} ${v.model} ${v.year}`:"Vehicle unavailable"}</small></div><span className="badge awaiting">{x.category}</span></div><div className="mobile-expense-details"><span><small>Date</small><b>{x.date}</b></span><span><small>Amount</small><b>{formatCurrency(amountValue(x),"ZMW")}</b></span><span className="full"><small>Description</small><b>{x.description}</b></span><span className="full"><small>Reference</small><b>{x.reference||"—"}</b></span></div></article>})}</div>
 {!filtered.length&&<div className="empty"><Receipt size={34}/><h3>{items.length?"No matching expenses":"No vehicle expenses recorded"}</h3><p>{items.length?"Change the search or category filter to view other entries.":"Add the first expense to begin building each vehicle's true cost."}</p></div>}</section>
 </>;
}
