"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {Car,FileText,History,Plus,Receipt,Route,ShieldCheck,ShoppingCart,UserRound} from "lucide-react";
import {loadVehicles,saveVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {loadVehicleDocuments,loadVehicleExpenses,saveVehicleDocuments,saveVehicleExpenses,VehicleDocument,VehicleExpense} from "@/lib/ledger-store";
import {CollectionTrip,loadTrips,tripSpent} from "@/lib/operations-store";
import {loadSales,Sale} from "@/lib/sales-store";

const money=(n:number)=>new Intl.NumberFormat("en-ZM",{style:"currency",currency:"ZMW",maximumFractionDigits:0}).format(n);
const expenseCategories=["Duty","Clearing","Border Charges","Transport","Fuel","Accommodation","Meals","Driver Allowance","Repairs","Parts","Registration","Insurance","Car Wash","Advertising","Other"];
const documentTypes=["Purchase Invoice","Export Certificate","Bill of Lading","Clearing Document","ZRA Receipt","Insurance","Registration","Road Tax","Driver Receipt","Repair Invoice","Vehicle Photo","Other"];
type Tab="overview"|"ledger"|"expenses"|"documents"|"timeline"|"collection"|"sales"|"audit";

export default function VehicleDetailsPage(){
 const params=useParams<{id:string}>();
 const [vehicle,setVehicle]=useState<Vehicle|null>(null),[expenses,setExpenses]=useState<VehicleExpense[]>([]),[documents,setDocuments]=useState<VehicleDocument[]>([]),[trips,setTrips]=useState<CollectionTrip[]>([]),[sales,setSales]=useState<Sale[]>([]),[tab,setTab]=useState<Tab>("overview"),[showExpense,setShowExpense]=useState(false),[showDocument,setShowDocument]=useState(false);
 useEffect(()=>{setVehicle(loadVehicles().find(v=>v.id===params.id)||null);setExpenses(loadVehicleExpenses());setDocuments(loadVehicleDocuments());setTrips(loadTrips());setSales(loadSales())},[params.id]);
 const vehicleExpenses=useMemo(()=>expenses.filter(x=>x.vehicleId===params.id),[expenses,params.id]);
 const vehicleDocs=useMemo(()=>documents.filter(x=>x.vehicleId===params.id),[documents,params.id]);
 const trip=useMemo(()=>vehicle?trips.find(t=>t.vehicleStockId===vehicle.stockId):undefined,[trips,vehicle]);
 const sale=useMemo(()=>sales.find(s=>s.vehicleId===params.id),[sales,params.id]);
 const additional=vehicleExpenses.reduce((s,x)=>s+x.amount,0);
 const landedCost=(vehicle?.purchasePrice||0)+additional;
 const profit=sale?sale.sellingPrice-landedCost:0;
 if(!vehicle)return <div className="panel"><div className="empty">Vehicle not found. <Link href="/vehicles"><b>Return to vehicle stock</b></Link></div></div>;
 function addExpense(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const amount=Number(f.get("amount"));const item:VehicleExpense={id:crypto.randomUUID(),vehicleId:vehicle.id,category:String(f.get("category")),description:String(f.get("description")),amount,date:String(f.get("date")),reference:String(f.get("reference")||""),createdAt:new Date().toISOString()};const next=[item,...expenses];saveVehicleExpenses(next);setExpenses(next);const all=loadVehicles().map(v=>v.id===vehicle.id?{...v,totalCost:v.purchasePrice+vehicleExpenses.reduce((s,x)=>s+x.amount,0)+amount}:v);saveVehicles(all);setVehicle(all.find(v=>v.id===vehicle.id)||vehicle);setShowExpense(false);e.currentTarget.reset()}
 function addDocument(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item:VehicleDocument={id:crypto.randomUUID(),vehicleId:vehicle.id,type:String(f.get("type")),name:String(f.get("name")),reference:String(f.get("reference")||""),date:String(f.get("date")),createdAt:new Date().toISOString()};const next=[item,...documents];saveVehicleDocuments(next);setDocuments(next);setShowDocument(false);e.currentTarget.reset()}
 const tabs:[Tab,string,any][]=[["overview","Overview",Car],["ledger","Ledger",Receipt],["expenses","Expenses",Plus],["documents","Documents",FileText],["timeline","Timeline",History],["collection","Collection",Route],["sales","Sales",ShoppingCart],["audit","Audit",ShieldCheck]];
 const timeline=[{date:vehicle.createdAt,title:`Vehicle registered as ${vehicle.stockId}`,detail:`Purchased from ${vehicle.supplier}`},...vehicleExpenses.map(x=>({date:x.createdAt,title:`${x.category} expense added`,detail:`${money(x.amount)} · ${x.description}`})),...vehicleDocs.map(x=>({date:x.createdAt,title:`${x.type} recorded`,detail:x.name})),...(trip?[{date:trip.departureDate,title:`Collection trip ${trip.tripId}`,detail:`${trip.driverName} · ${trip.collectionPoint} to ${trip.destination}`}]:[]),...(sale?[{date:sale.createdAt,title:`Vehicle sold under ${sale.saleId}`,detail:`${sale.customerName} · ${money(sale.sellingPrice)}`}]:[])].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());
 return <>
 <div className="deal-hero"><div><Link className="back-link" href="/vehicles">← Vehicle stock</Link><div className="deal-title"><div className="vehicle-mark"><Car/></div><div><h1>{vehicle.stockId}</h1><p>{vehicle.make} {vehicle.model} {vehicle.year} · {vehicle.vin}</p></div></div></div><div className="deal-actions"><span className={`badge ${vehicle.status==="Available"?"available":vehicle.status==="In Transit"?"transit":vehicle.status==="Sold"?"sold":"awaiting"}`}>{vehicle.status}</span><button className="button" onClick={()=>{setTab("expenses");setShowExpense(true)}}><Plus size={17}/>Add Expense</button></div></div>
 <div className="deal-kpis"><div><span>Purchase Price</span><b>{money(vehicle.purchasePrice)}</b></div><div><span>Total Landed Cost</span><b>{money(landedCost)}</b></div><div><span>Selling Price</span><b>{sale?money(sale.sellingPrice):"Not sold"}</b></div><div className={sale?(profit>=0?"positive-card":"negative-card"):""}><span>Gross Profit</span><b>{sale?money(profit):"Pending sale"}</b></div></div>
 <div className="deal-tabs">{tabs.map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={tab===key?"active":""}><Icon size={16}/>{label}</button>)}</div>
 {tab==="overview"&&<div className="deal-grid"><section className="panel"><div className="panel-head"><h2>Vehicle Overview</h2></div><div className="panel-body"><div className="summary-grid"><div className="summary-item"><span>Make & Model</span><strong>{vehicle.make} {vehicle.model}</strong></div><div className="summary-item"><span>Year</span><strong>{vehicle.year}</strong></div><div className="summary-item"><span>Colour</span><strong>{vehicle.colour||"Not captured"}</strong></div><div className="summary-item"><span>Engine Number</span><strong>{vehicle.engineNumber}</strong></div><div className="summary-item"><span>Registration</span><strong>{vehicle.registrationNumber||"Not registered"}</strong></div><div className="summary-item"><span>Current Location</span><strong>{vehicle.currentLocation}</strong></div><div className="summary-item"><span>Supplier</span><strong>{vehicle.supplier}</strong></div><div className="summary-item"><span>Purchase Date</span><strong>{vehicle.purchaseDate}</strong></div><div className="summary-item"><span>Documents</span><strong>{vehicleDocs.length} recorded</strong></div></div></div></section><aside className="panel"><div className="panel-head"><h2>Deal Jacket Health</h2></div><div className="panel-body health-list"><div><span>Financial ledger</span><b className="ok">Ready</b></div><div><span>Collection record</span><b className={trip?"ok":"warn"}>{trip?trip.status:"Missing"}</b></div><div><span>Purchase invoice</span><b className={vehicleDocs.some(d=>d.type==="Purchase Invoice")?"ok":"warn"}>{vehicleDocs.some(d=>d.type==="Purchase Invoice")?"Filed":"Missing"}</b></div><div><span>Sale record</span><b className={sale?"ok":"muted"}>{sale?sale.status:"Not sold"}</b></div></div></aside></div>}
 {tab==="ledger"&&<section className="panel"><div className="panel-head"><h2>Vehicle Financial Ledger</h2><strong>{money(landedCost)}</strong></div><div className="ledger-list"><div className="ledger-row base"><span><b>Purchase Price</b><small>{vehicle.purchaseDate} · {vehicle.supplier}</small></span><b>{money(vehicle.purchasePrice)}</b></div>{vehicleExpenses.map(x=><div className="ledger-row" key={x.id}><span><b>{x.category}</b><small>{x.date} · {x.description}{x.reference?` · ${x.reference}`:""}</small></span><b>{money(x.amount)}</b></div>)}<div className="ledger-total"><span>Total Landed Cost</span><b>{money(landedCost)}</b></div>{sale&&<><div className="ledger-sale"><span>Selling Price</span><b>{money(sale.sellingPrice)}</b></div><div className={profit>=0?"ledger-profit":"ledger-loss"}><span>Gross Profit</span><b>{money(profit)}</b></div></>}</div></section>}
 {tab==="expenses"&&<><div className="section-actions"><div><h2>Vehicle Expenses</h2><p>Every entry automatically updates this vehicle's landed cost.</p></div><button className="button" onClick={()=>setShowExpense(!showExpense)}><Plus size={17}/>Add Expense</button></div>{showExpense&&<form className="form-card section-gap" onSubmit={addExpense}><div className="form-grid"><div className="field"><label>Category</label><select className="select" name="category">{expenseCategories.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Amount</label><input className="input" name="amount" type="number" min="0" step="0.01" required/></div><div className="field"><label>Date</label><input className="input" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Receipt / Reference</label><input className="input" name="reference"/></div><div className="field full"><label>Description</label><input className="input" name="description" required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowExpense(false)}>Cancel</button><button className="button">Save Expense</button></div></form>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{vehicleExpenses.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.category}</b></td><td>{x.description}</td><td>{x.reference||"—"}</td><td><b>{money(x.amount)}</b></td></tr>)}</tbody></table>{!vehicleExpenses.length&&<div className="empty">No additional vehicle expenses recorded.</div>}</div></section></>}
 {tab==="documents"&&<><div className="section-actions"><div><h2>Vehicle Documents</h2><p>Digital records for the complete deal jacket.</p></div><button className="button" onClick={()=>setShowDocument(!showDocument)}><Plus size={17}/>Add Document</button></div>{showDocument&&<form className="form-card section-gap" onSubmit={addDocument}><div className="form-grid"><div className="field"><label>Document Type</label><select className="select" name="type">{documentTypes.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Document Name</label><input className="input" name="name" required placeholder="e.g. Purchase invoice"/></div><div className="field"><label>Reference</label><input className="input" name="reference"/></div><div className="field"><label>Date</label><input className="input" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowDocument(false)}>Cancel</button><button className="button">Save Document</button></div></form>}<div className="document-grid">{vehicleDocs.map(d=><div className="document-card" key={d.id}><div className="document-icon"><FileText/></div><div><b>{d.type}</b><p>{d.name}</p><small>{d.date}{d.reference?` · ${d.reference}`:""}</small></div></div>)}{!vehicleDocs.length&&<div className="panel empty">No documents recorded for this vehicle.</div>}</div></>}
 {tab==="timeline"&&<section className="panel"><div className="panel-head"><h2>Vehicle Timeline</h2></div><div className="timeline">{timeline.map((x,i)=><div className="timeline-item" key={`${x.date}-${i}`}><div className="timeline-dot"/><div><small>{new Date(x.date).toLocaleString("en-ZM")}</small><b>{x.title}</b><p>{x.detail}</p></div></div>)}</div></section>}
 {tab==="collection"&&<section className="panel"><div className="panel-head"><h2>Collection & Driver Assignment</h2></div>{trip?<div className="panel-body"><div className="summary-grid"><div className="summary-item"><span>Trip ID</span><strong>{trip.tripId}</strong></div><div className="summary-item"><span>Driver</span><strong>{trip.driverName}</strong></div><div className="summary-item"><span>Status</span><strong>{trip.status}</strong></div><div className="summary-item"><span>Route</span><strong>{trip.collectionPoint} → {trip.destination}</strong></div><div className="summary-item"><span>Advance</span><strong>{money(trip.advance)}</strong></div><div className="summary-item"><span>Trip Expenses</span><strong>{money(tripSpent(trip))}</strong></div></div><div className="ledger-list compact">{trip.expenses.map(e=><div className="ledger-row" key={e.id}><span><b>{e.category}</b><small>{e.date} · {e.note}</small></span><b>{money(e.amount)}</b></div>)}</div></div>:<div className="empty">No collection trip is linked to this vehicle.</div>}</section>}
 {tab==="sales"&&<section className="panel"><div className="panel-head"><h2>Sale & Customer</h2></div>{sale?<div className="panel-body"><div className="customer-banner"><div className="avatar"><UserRound/></div><div><small>Customer</small><h3>{sale.customerName}</h3><p>{sale.saleId} · {sale.saleDate}</p></div><span className={`badge ${sale.status==="Fully Paid"?"available":"awaiting"}`}>{sale.status}</span></div><div className="summary-grid"><div className="summary-item"><span>Selling Price</span><strong>{money(sale.sellingPrice)}</strong></div><div className="summary-item"><span>Amount Paid</span><strong>{money(sale.amountPaid)}</strong></div><div className="summary-item"><span>Balance</span><strong>{money(sale.balance)}</strong></div><div className="summary-item"><span>Payment Method</span><strong>{sale.paymentMethod}</strong></div><div className="summary-item"><span>Landed Cost</span><strong>{money(landedCost)}</strong></div><div className="summary-item"><span>Gross Profit</span><strong className={profit>=0?"profit":"loss"}>{money(profit)}</strong></div></div></div>:<div className="empty">This vehicle has not been sold.</div>}</section>}
 {tab==="audit"&&<section className="panel"><div className="panel-head"><h2>Audit Trail</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Action</th><th>Record</th><th>User</th></tr></thead><tbody>{timeline.map((x,i)=><tr key={i}><td>{new Date(x.date).toLocaleString("en-ZM")}</td><td>{x.title}</td><td>{x.detail}</td><td>Administrator</td></tr>)}</tbody></table></div></section>}
 </>;
}