"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {Car,Download,ExternalLink,FileText,History,PenLine,Plus,Receipt,Route,ShieldCheck,ShoppingCart,Trash2,Upload} from "lucide-react";
import {AppDialog} from "@/components/app-dialog";
import {loadVehicles,saveVehicles} from "@/lib/vehicle-store";
import {Vehicle,VehicleStatus} from "@/lib/types";
import {loadVehicleDocuments,loadVehicleExpenses,saveVehicleDocuments,saveVehicleExpenses,VehicleDocument,VehicleExpense} from "@/lib/ledger-store";
import {CollectionTrip,loadTrips,tripSpent} from "@/lib/operations-store";
import {loadSales,Sale} from "@/lib/sales-store";
import {formatCurrency} from "@/lib/currency";
import {vehicleCostZmw} from "@/lib/financial-analysis";

const expenseCategories=["Duty","Clearing","Border Charges","Transport","Fuel","Accommodation","Meals","Driver Allowance","Repairs","Parts","Registration","Insurance","Car Wash","Advertising","Other"];
const documentTypes=["Purchase Invoice","Export Certificate","Bill of Lading","Clearing Document","ZRA Receipt","Insurance","Registration","Road Tax","Driver Receipt","Repair Invoice","Vehicle Photo","Other"];
const manualStatuses:VehicleStatus[]=["Awaiting Collection","Available","Reserved","Under Repair"];
type Tab="overview"|"ledger"|"expenses"|"documents"|"timeline"|"collection"|"sales"|"audit";
type DialogState={open:boolean;title:string;message:string;tone?:"default"|"danger"|"warning";confirmLabel?:string;action?:"delete-document"|"status-change";targetId?:string;nextStatus?:VehicleStatus;reason?:string};
const money=(n:number)=>formatCurrency(n,"ZMW");
const fileSize=(n?:number)=>!n?"No file":n<1024?`${n} B`:n<1024*1024?`${(n/1024).toFixed(1)} KB`:`${(n/1024/1024).toFixed(1)} MB`;
const toDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});
const closedDialog:DialogState={open:false,title:"",message:""};

export default function VehicleDetailsPage(){
 const params=useParams<{id:string}>();
 const [vehicle,setVehicle]=useState<Vehicle|null>(null),[expenses,setExpenses]=useState<VehicleExpense[]>([]),[documents,setDocuments]=useState<VehicleDocument[]>([]),[trips,setTrips]=useState<CollectionTrip[]>([]),[sales,setSales]=useState<Sale[]>([]),[tab,setTab]=useState<Tab>("overview"),[showExpense,setShowExpense]=useState(false),[showDocument,setShowDocument]=useState(false),[showStatus,setShowStatus]=useState(false),[savingFile,setSavingFile]=useState(false),[notice,setNotice]=useState(""),[dialog,setDialog]=useState<DialogState>(closedDialog);
 useEffect(()=>{setVehicle(loadVehicles().find(v=>v.id===params.id)||null);setExpenses(loadVehicleExpenses());setDocuments(loadVehicleDocuments());setTrips(loadTrips());setSales(loadSales())},[params.id]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),2800);return()=>clearTimeout(timer)},[notice]);
 const vehicleExpenses=useMemo(()=>expenses.filter(x=>x.vehicleId===params.id),[expenses,params.id]);
 const vehicleDocs=useMemo(()=>documents.filter(x=>x.vehicleId===params.id),[documents,params.id]);
 const trip=useMemo(()=>vehicle?trips.find(t=>t.vehicleStockId===vehicle.stockId):undefined,[trips,vehicle]);
 const sale=useMemo(()=>sales.find(s=>s.vehicleId===params.id),[sales,params.id]);
 if(!vehicle)return <div className="panel"><div className="empty">Vehicle not found. <Link href="/vehicles"><b>Return to vehicle stock</b></Link></div></div>;
 const costPrice=Number(vehicle.purchasePriceZmw??vehicle.purchasePrice??0),expenseTotal=vehicleExpenses.reduce((sum,x)=>sum+Number(x.amountZmw??x.amount??0),0),totalVehicleCost=vehicleCostZmw(vehicle,expenses);
 const sellingPrice=sale?Number(sale.sellingPriceZmw??sale.sellingPrice??0):0,amountPaid=sale?Number(sale.amountPaidZmw??sale.amountPaid??0):0,outstanding=sale?Number(sale.balanceZmw??Math.max(0,sellingPrice-amountPaid)):0,grossProfit=sale?sellingPrice-totalVehicleCost:0;
 function addExpense(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),amount=Number(f.get("amount")||0);if(amount<=0)return;const item:VehicleExpense={id:crypto.randomUUID(),vehicleId:vehicle.id,category:String(f.get("category")),description:String(f.get("description")),amount,currency:"ZMW",amountZmw:amount,date:String(f.get("date")),reference:String(f.get("reference")||""),createdAt:new Date().toISOString()};const next=[item,...expenses];saveVehicleExpenses(next);setExpenses(next);const total=vehicleCostZmw(vehicle,next),updated={...vehicle,totalCost:total};saveVehicles(loadVehicles().map(v=>v.id===vehicle.id?updated:v));setVehicle(updated);setShowExpense(false);setNotice("Expense saved");form.reset()}
 function applyStatus(nextStatus:VehicleStatus,reason:string){const updated:Vehicle={...vehicle,status:nextStatus,statusHistory:[{id:crypto.randomUUID(),from:vehicle.status,to:nextStatus,reason,changedAt:new Date().toISOString()},...(vehicle.statusHistory||[])]};saveVehicles(loadVehicles().map(v=>v.id===vehicle.id?updated:v));setVehicle(updated);setShowStatus(false);setNotice(`Status changed to ${nextStatus}`)}
 function updateStatus(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(vehicle.status==="Sold")return;const f=new FormData(e.currentTarget),nextStatus=String(f.get("status")) as VehicleStatus,reason=String(f.get("reason")||"").trim();if(nextStatus===vehicle.status){setShowStatus(false);return}if(!manualStatuses.includes(nextStatus)){setDialog({open:true,title:"Status not available",message:"In Transit and Sold are controlled by the collection and sales workflows.",tone:"warning"});return}setDialog({open:true,title:"Confirm status change",message:`Change ${vehicle.stockId} from ${vehicle.status} to ${nextStatus}?${reason?` Note: ${reason}`:""}`,tone:"default",confirmLabel:"Change Status",action:"status-change",nextStatus,reason})}
 async function addDocument(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),file=f.get("file") as File;if(!file||!file.size){setDialog({open:true,title:"Select a document",message:"Choose a file before uploading it to the vehicle Deal Jacket.",tone:"warning"});return}if(file.size>2*1024*1024){setDialog({open:true,title:"File is too large",message:"Documents are currently limited to 2 MB per file. Choose a smaller file and try again.",tone:"warning"});return}setSavingFile(true);try{const item:VehicleDocument={id:crypto.randomUUID(),vehicleId:vehicle.id,type:String(f.get("type")),name:String(f.get("name")||file.name),reference:String(f.get("reference")||""),date:String(f.get("date")),createdAt:new Date().toISOString(),fileName:file.name,fileType:file.type||"application/octet-stream",fileSize:file.size,fileData:await toDataUrl(file)};const next=[item,...documents];saveVehicleDocuments(next);setDocuments(next);setShowDocument(false);setNotice("Document uploaded");form.reset()}finally{setSavingFile(false)}}
 function requestDeleteDocument(document:VehicleDocument){setDialog({open:true,title:"Delete document?",message:`Remove ${document.name||document.fileName||document.type} from ${vehicle.stockId}'s Deal Jacket? This cannot be undone.`,tone:"danger",confirmLabel:"Delete Document",action:"delete-document",targetId:document.id})}
 function handleDialogConfirm(){if(dialog.action==="delete-document"&&dialog.targetId){const next=documents.filter(d=>d.id!==dialog.targetId);saveVehicleDocuments(next);setDocuments(next);setNotice("Document deleted")}else if(dialog.action==="status-change"&&dialog.nextStatus){applyStatus(dialog.nextStatus,dialog.reason||"")}setDialog(closedDialog)}
 const tabs:[Tab,string,any][]=[["overview","Overview",Car],["ledger","Cost Record",Receipt],["expenses","Expenses",Plus],["documents","Documents",FileText],["timeline","Timeline",History],["collection","Collection",Route],["sales","Sale",ShoppingCart],["audit","Audit",ShieldCheck]];
 const timeline=[{date:vehicle.createdAt,title:`Vehicle registered as ${vehicle.stockId}`,detail:`Supplier: ${vehicle.supplier}`},...(vehicle.statusHistory||[]).map(x=>({date:x.changedAt,title:`Status changed from ${x.from} to ${x.to}`,detail:x.reason||"Status updated"})),...vehicleExpenses.map(x=>({date:x.createdAt,title:`${x.category} expense added`,detail:`${money(Number(x.amountZmw??x.amount))} · ${x.description}`})),...vehicleDocs.map(x=>({date:x.createdAt,title:`${x.type} uploaded`,detail:x.fileName||x.name})),...(trip?[{date:trip.departureDate,title:`Collection trip ${trip.tripId}`,detail:`${trip.driverName} · ${trip.collectionPoint} to ${trip.destination}`}]:[]),...(sale?[{date:sale.createdAt,title:`Vehicle sold under ${sale.saleId}`,detail:`${sale.customerName} · ${money(sellingPrice)}`}]:[])].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());
 return <>{notice&&<div className="app-toast"><span>✓</span>{notice}</div>}
 <AppDialog open={dialog.open} title={dialog.title} message={dialog.message} tone={dialog.tone} confirmLabel={dialog.confirmLabel} onClose={()=>setDialog(closedDialog)} onConfirm={dialog.action?handleDialogConfirm:undefined}/>
 <div className="deal-hero"><div><Link className="back-link" href="/vehicles">← Vehicle stock</Link><div className="deal-title"><div className="vehicle-mark"><Car/></div><div><h1>{vehicle.stockId}</h1><p>{vehicle.make} {vehicle.model} {vehicle.year} · {vehicle.vin}</p></div></div></div><div className="deal-actions"><span className={`badge ${vehicle.status==="Available"?"available":vehicle.status==="In Transit"?"transit":vehicle.status==="Sold"?"sold":"awaiting"}`}>{vehicle.status}</span>{vehicle.status!=="Sold"&&<button className="button secondary" type="button" onClick={()=>setShowStatus(v=>!v)}>Change Status</button>}<Link className="button secondary" href={`/vehicles/${vehicle.id}/edit`}><PenLine size={16}/>Edit Vehicle</Link><button className="button" onClick={()=>{setTab("expenses");setShowExpense(true)}}><Plus size={17}/>Add Expense</button></div></div>
 {showStatus&&<form className="form-card section-gap" onSubmit={updateStatus}><div className="form-heading"><div><h2>Update Vehicle Status</h2><p>In Transit and Sold are updated through the collection and sales workflows.</p></div></div><div className="form-grid"><div className="field"><label>New Status</label><select className="select" name="status" defaultValue={manualStatuses.includes(vehicle.status)?vehicle.status:"Available"}>{manualStatuses.map(x=><option key={x}>{x}</option>)}</select></div><div className="field full"><label>Reason / Note</label><input className="input" name="reason" placeholder="Why is the status changing?"/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowStatus(false)}>Cancel</button><button className="button">Save Status</button></div></form>}
 <div className="deal-kpis"><div><span>Cost Price</span><b>{money(costPrice)}</b></div><div><span>Total Vehicle Cost</span><b>{money(totalVehicleCost)}</b><small>Includes {money(expenseTotal)} expenses</small></div><div><span>Selling Price</span><b>{sale?money(sellingPrice):"Not sold"}</b></div><div className={sale?(grossProfit>=0?"positive-card":"negative-card"):""}><span>Gross Profit</span><b>{sale?money(grossProfit):"Pending sale"}</b></div></div>
 <div className="deal-tabs">{tabs.map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={tab===key?"active":""}><Icon size={16}/>{label}</button>)}</div>
 {tab==="overview"&&<div className="deal-grid"><section className="panel"><div className="panel-head"><h2>Vehicle Details</h2></div><div className="panel-body"><div className="summary-grid">{[["Make & Model",`${vehicle.make} ${vehicle.model}`],["Year",vehicle.year],["Colour",vehicle.colour||"Not captured"],["Engine Number",vehicle.engineNumber],["Registration",vehicle.registrationNumber||"Not registered"],["Current Location",vehicle.currentLocation],["Supplier",vehicle.supplier],["Purchase Date",vehicle.purchaseDate],["Uploaded Documents",vehicleDocs.filter(d=>d.fileData).length]].map(([k,v])=><div className="summary-item" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div></div></section><aside className="panel"><div className="panel-head"><h2>Record Check</h2></div><div className="panel-body health-list"><div><span>Cost record</span><b className="ok">Ready</b></div><div><span>Collection trip</span><b className={trip?"ok":"muted"}>{trip?trip.status:"Not required / not linked"}</b></div><div><span>Purchase invoice</span><b className={vehicleDocs.some(d=>d.type==="Purchase Invoice"&&d.fileData)?"ok":"warn"}>{vehicleDocs.some(d=>d.type==="Purchase Invoice"&&d.fileData)?"Uploaded":"Missing"}</b></div><div><span>Sale record</span><b className={sale?"ok":"muted"}>{sale?sale.status:"Not sold"}</b></div></div></aside></div>}
 {tab==="ledger"&&<section className="panel"><div className="panel-head"><h2>Vehicle Cost Record</h2><strong>{money(totalVehicleCost)}</strong></div><div className="ledger-list"><div className="ledger-row base"><span><b>Cost Price</b><small>{vehicle.purchaseDate} · {vehicle.supplier}</small></span><b>{money(costPrice)}</b></div>{vehicleExpenses.map(x=><div className="ledger-row" key={x.id}><span><b>{x.category}</b><small>{x.date} · {x.description}{x.reference?` · ${x.reference}`:""}</small></span><b>{money(Number(x.amountZmw??x.amount))}</b></div>)}<div className="ledger-total"><span>Total Vehicle Cost</span><b>{money(totalVehicleCost)}</b></div>{sale&&<><div className="ledger-sale"><span><b>Selling Price</b><small>{sale.saleDate} · {sale.customerName}</small></span><b>{money(sellingPrice)}</b></div><div className={grossProfit>=0?"ledger-profit":"ledger-loss"}><span>Gross Profit / Loss</span><b>{money(grossProfit)}</b></div></>}</div></section>}
 {tab==="expenses"&&<><div className="section-actions"><div><h2>Vehicle Expenses</h2><p>Each expense automatically increases the total vehicle cost.</p></div><button className="button" onClick={()=>setShowExpense(!showExpense)}><Plus size={17}/>Add Expense</button></div>{showExpense&&<form className="form-card section-gap" onSubmit={addExpense}><div className="form-grid"><div className="field"><label>Category</label><select className="select" name="category">{expenseCategories.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Amount (ZMW)</label><input className="input" name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Date</label><input className="input" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Receipt / Reference</label><input className="input" name="reference"/></div><div className="field full"><label>Description</label><input className="input" name="description" required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowExpense(false)}>Cancel</button><button className="button">Save Expense</button></div></form>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{vehicleExpenses.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.category}</b></td><td>{x.description}</td><td>{x.reference||"—"}</td><td><b>{money(Number(x.amountZmw??x.amount))}</b></td></tr>)}</tbody></table>{!vehicleExpenses.length&&<div className="empty">No vehicle expenses recorded.</div>}</div></section></>}
 {tab==="documents"&&<><div className="section-actions"><div><h2>Vehicle Documents</h2><p>Invoices, receipts, certificates, registration records and vehicle photos.</p></div><button className="button" onClick={()=>setShowDocument(!showDocument)}><Upload size={17}/>Upload Document</button></div>{showDocument&&<form className="form-card section-gap" onSubmit={addDocument}><div className="form-grid"><div className="field"><label>Document Type</label><select className="select" name="type">{documentTypes.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Document Name</label><input className="input" name="name"/></div><div className="field"><label>Reference</label><input className="input" name="reference"/></div><div className="field"><label>Document Date</label><input className="input" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field full"><label>Select File (maximum 2 MB)</label><input className="input" name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx" required/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShowDocument(false)}>Cancel</button><button className="button" disabled={savingFile}>{savingFile?"Uploading...":"Upload to Vehicle"}</button></div></form>}<div className="document-grid">{vehicleDocs.map(d=><div className="document-card" key={d.id}><div className="document-icon"><FileText/></div><div className="document-content"><div className="row-between"><div><b>{d.type}</b><p>{d.name}</p></div><span className={`badge ${d.fileData?"available":"awaiting"}`}>{d.fileData?"Uploaded":"Record only"}</span></div><small>{d.date}{d.reference?` · ${d.reference}`:""}</small>{d.fileName&&<small>{d.fileName} · {fileSize(d.fileSize)}</small>}<div className="document-actions">{d.fileData&&<><a className="button secondary compact-button" href={d.fileData} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Open</a><a className="button secondary compact-button" href={d.fileData} download={d.fileName||d.name}><Download size={15}/>Download</a></>}<button className="button secondary compact-button danger-button" type="button" onClick={()=>requestDeleteDocument(d)}><Trash2 size={15}/>Delete</button></div></div></div>)}{!vehicleDocs.length&&<div className="panel empty">No documents uploaded for this vehicle.</div>}</div></>}
 {tab==="timeline"&&<section className="panel"><div className="panel-head"><h2>Vehicle Timeline</h2></div><div className="timeline">{timeline.map((x,i)=><div className="timeline-item" key={`${x.date}-${i}`}><div className="timeline-dot"/><div><small>{new Date(x.date).toLocaleString("en-ZM")}</small><b>{x.title}</b><p>{x.detail}</p></div></div>)}</div></section>}
 {tab==="collection"&&<section className="panel"><div className="panel-head"><h2>Collection Trip</h2></div>{trip?<div className="panel-body"><div className="summary-grid">{[["Trip ID",trip.tripId],["Driver",trip.driverName],["Status",trip.status],["Route",`${trip.collectionPoint} → ${trip.destination}`],["Driver Advance",money(Number(trip.advanceZmw??trip.advance))],["Trip Expenses",money(tripSpent(trip))]].map(([k,v])=><div className="summary-item" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div></div>:<div className="empty">No collection trip is linked to this vehicle. This is normal for a local purchase.</div>}</section>}
 {tab==="sales"&&<section className="panel"><div className="panel-head"><h2>Sale & Payment Position</h2></div>{sale?<div className="panel-body"><div className="summary-grid">{[["Sale ID",sale.saleId],["Customer",sale.customerName],["Selling Price",money(sellingPrice)],["Amount Paid",money(amountPaid)],["Outstanding Balance",money(outstanding)],["Payment Method",sale.paymentMethod],["Sale Date",sale.saleDate],["Status",sale.status]].map(([k,v])=><div className="summary-item" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div></div>:<div className="empty">This vehicle has not been sold.</div>}</section>}
 {tab==="audit"&&<section className="panel"><div className="panel-head"><h2>Record Audit</h2></div><div className="panel-body health-list"><div><span>Vehicle created</span><b>{new Date(vehicle.createdAt).toLocaleString("en-ZM")}</b></div><div><span>Status changes</span><b>{vehicle.statusHistory?.length||0}</b></div><div><span>Expenses recorded</span><b>{vehicleExpenses.length}</b></div><div><span>Documents recorded</span><b>{vehicleDocs.length}</b></div><div><span>Sale reference</span><b>{sale?.saleId||"Not sold"}</b></div><div><span>Currency</span><b>ZMW</b></div></div></section>}
 </>;
}