"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {BadgeCheck,Eye,Filter,PenLine,Plus,Search,ShoppingCart,X} from "lucide-react";
import {loadCustomers,Customer} from "@/lib/customer-store";
import {loadSales,nextSaleId,Sale,saveSales} from "@/lib/sales-store";
import {loadVehicles,saveVehicles} from "@/lib/vehicle-store";
import {loadVehicleExpenses,VehicleExpense} from "@/lib/ledger-store";
import {Vehicle} from "@/lib/types";
import {Currency,formatCurrency,normalizeCurrency,toZmw} from "@/lib/currency";
import {saleProfitAnalysis,vehicleCostZmw} from "@/lib/financial-analysis";

export default function SalesPage(){
 const [sales,setSales]=useState<Sale[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[expenses,setExpenses]=useState<VehicleExpense[]>([]),[show,setShow]=useState(false),[editing,setEditing]=useState<Sale|null>(null),[vehicleId,setVehicleId]=useState(""),[currency,setCurrency]=useState<Currency>("ZMW"),[price,setPrice]=useState(""),[rate,setRate]=useState(""),[query,setQuery]=useState(""),[currencyFilter,setCurrencyFilter]=useState("All"),[statusFilter,setStatusFilter]=useState("All"),[message,setMessage]=useState("");
 useEffect(()=>{setSales(loadSales());setVehicles(loadVehicles());setCustomers(loadCustomers());setExpenses(loadVehicleExpenses())},[]);
 const available=useMemo(()=>vehicles.filter(v=>v.status!=="Sold"||v.id===editing?.vehicleId),[vehicles,editing]);
 const filtered=useMemo(()=>sales.filter(s=>`${s.saleId} ${s.stockId} ${s.vehicleName} ${s.customerName}`.toLowerCase().includes(query.toLowerCase())&&(currencyFilter==="All"||normalizeCurrency(s.currency)===currencyFilter)&&(statusFilter==="All"||s.status===statusFilter)),[sales,query,currencyFilter,statusFilter]);
 const totals=sales.reduce((a,s)=>({revenue:a.revenue+Number(s.sellingPriceZmw??toZmw(s.sellingPrice,normalizeCurrency(s.currency),s.exchangeRate)),paid:a.paid+Number(s.amountPaidZmw??toZmw(s.amountPaid,normalizeCurrency(s.currency),s.exchangeRate)),balance:a.balance+Number(s.balanceZmw??toZmw(s.balance,normalizeCurrency(s.currency),s.exchangeRate)),profit:a.profit+saleProfitAnalysis(s,vehicles.find(v=>v.id===s.vehicleId),expenses).profit}),{revenue:0,paid:0,balance:0,profit:0});
 function chooseVehicle(id:string){setVehicleId(id);if(editing)return;const v=vehicles.find(x=>x.id===id);if(v){setCurrency(normalizeCurrency(v.estimatedSellingCurrency));setPrice(v.estimatedSellingPrice?String(v.estimatedSellingPrice):"");setRate(v.estimatedSellingExchangeRate?String(v.estimatedSellingExchangeRate):"")}}
 function resetForm(){setShow(false);setEditing(null);setVehicleId("");setCurrency("ZMW");setPrice("");setRate("")}
 function startEdit(s:Sale){setEditing(s);setShow(true);setVehicleId(s.vehicleId);setCurrency(normalizeCurrency(s.currency));setPrice(String(s.originalSellingPrice??s.sellingPrice));setRate(String(s.exchangeRate||1));window.scrollTo({top:0,behavior:"smooth"})}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),vehicle=vehicles.find(v=>v.id===vehicleId),customer=customers.find(c=>c.id===String(f.get("customerId")));if(!vehicle||!customer)return;const sellingPrice=Number(price),amountPaid=Number(f.get("amountPaid")),exchangeRate=currency==="USD"?Number(rate):1;if(amountPaid>sellingPrice)return setMessage("Amount paid cannot exceed the selling price.");if(currency==="USD"&&exchangeRate<=0)return setMessage("Enter the USD to ZMW exchange rate.");const sellingPriceZmw=toZmw(sellingPrice,currency,exchangeRate),amountPaidZmw=toZmw(amountPaid,currency,exchangeRate);if(editing&&amountPaidZmw>sellingPriceZmw)return setMessage("Selling value cannot be lower than payments already received.");const balance=sellingPrice-amountPaid,balanceZmw=Math.max(0,sellingPriceZmw-amountPaidZmw),vehicleCost=vehicleCostZmw(vehicle,expenses),profit=sellingPriceZmw-vehicleCost;const sale:Sale={...(editing||{} as Sale),id:editing?.id||crypto.randomUUID(),saleId:editing?.saleId||nextSaleId(sales),vehicleId:vehicle.id,stockId:vehicle.stockId,vehicleName:`${vehicle.make} ${vehicle.model} ${vehicle.year}`,customerId:customer.id,customerName:customer.name,saleDate:String(f.get("saleDate")),sellingPrice,amountPaid,balance,vehicleCost,profit,currency,exchangeRate,originalSellingPrice:sellingPrice,originalAmountPaid:amountPaid,originalBalance:balance,sellingPriceZmw,amountPaidZmw,balanceZmw,paymentMethod:String(f.get("paymentMethod")),status:balanceZmw<=0?"Fully Paid":"Partially Paid",createdAt:editing?.createdAt||new Date().toISOString()};const next=editing?sales.map(s=>s.id===editing.id?sale:s):[sale,...sales],nextVehicles=vehicles.map(v=>v.id===vehicle.id?{...v,status:"Sold" as const,currentLocation:"Sold / Delivered"}:v);saveSales(next);saveVehicles(nextVehicles);setSales(next);setVehicles(nextVehicles);setMessage(editing?`${sale.saleId} updated successfully.`:`${sale.saleId} recorded successfully.`);window.setTimeout(()=>setMessage(""),3000);resetForm()}
 return <>{message&&<div className="toast-message"><BadgeCheck size={18}/><span>{message}</span><button type="button" onClick={()=>setMessage("")}><X size={16}/></button></div>}<div className="sales-page-flow"><div className="page-heading sales-heading"><div><h1>Sales & Payments</h1><p>View and update sales while preserving the vehicle and payment record.</p></div><button type="button" className="button sales-primary-action" onClick={()=>{if(show)resetForm();else setShow(true)}}><Plus size={18}/>{show?"Close Form":"Record Sale"}</button></div>
 {show&&<form key={editing?.id||"new"} className="form-card professional-form sales-form" onSubmit={submit}><div className="form-heading"><div><h2>{editing?`Edit ${editing.saleId}`:"Record Vehicle Sale"}</h2>{editing&&<p>Changes recalculate the ZMW selling value, balance and profit.</p>}</div><button type="button" className="icon-button" onClick={resetForm}><X size={18}/></button></div><div className="form-grid"><div className="field"><label>Vehicle</label><select className="select" required value={vehicleId} onChange={e=>chooseVehicle(e.target.value)} disabled={!!editing}><option value="">Select vehicle</option>{available.map(v=><option value={v.id} key={v.id}>{v.stockId} — {v.make} {v.model}</option>)}</select></div><div className="field"><label>Customer</label><select className="select" name="customerId" required defaultValue={editing?.customerId||""}><option value="">Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.customerId} — {c.name}</option>)}</select></div><div className="field"><label>Sale Currency</label><select className="select" value={currency} onChange={e=>setCurrency(e.target.value as Currency)}><option value="ZMW">ZMW</option><option value="USD">USD</option></select></div><div className="field"><label>Actual Selling Price</label><input className="input" type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></div>{currency==="USD"&&<div className="field"><label>USD to ZMW Exchange Rate</label><input className="input" type="number" min="0.0001" step="0.0001" value={rate} onChange={e=>setRate(e.target.value)} required/></div>}<div className="field"><label>Amount Paid</label><input className="input" type="number" min="0" step="0.01" name="amountPaid" defaultValue={editing?.originalAmountPaid??editing?.amountPaid??0} required/></div><div className="field"><label>Sale Date</label><input className="input" type="date" name="saleDate" required defaultValue={editing?.saleDate||new Date().toISOString().slice(0,10)}/></div><div className="field"><label>Payment Method</label><select className="select" name="paymentMethod" defaultValue={editing?.paymentMethod||"Bank Transfer"}><option>Bank Transfer</option><option>Cash</option><option>Mobile Money</option><option>Card</option></select></div></div><div className="actions"><button type="button" className="button secondary" onClick={resetForm}>Cancel</button><button className="button">{editing?"Save Changes":"Complete Sale"}</button></div></form>}
 <section className="panel sales-register"><div className="panel-head"><h2>Sales Register</h2><span className="badge sold">{sales.length} sales</span></div><div className="inventory-toolbar"><div className="search-control"><Search size={17}/><input placeholder="Search sales" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-control"><Filter size={16}/><select value={currencyFilter} onChange={e=>setCurrencyFilter(e.target.value)}><option>All</option><option>ZMW</option><option>USD</option></select></div><div className="filter-control"><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>All</option><option>Fully Paid</option><option>Partially Paid</option></select></div></div><div className="table-wrap"><table><thead><tr><th>Sale</th><th>Vehicle</th><th>Customer</th><th>Original Sale</th><th>ZMW Value</th><th>Paid</th><th>Balance</th><th>Profit</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(s=>{const a=saleProfitAnalysis(s,vehicles.find(v=>v.id===s.vehicleId),expenses),c=normalizeCurrency(s.currency);return <tr key={s.id}><td><b>{s.saleId}</b><br/><small>{s.saleDate}</small></td><td>{s.stockId}<br/><small>{s.vehicleName}</small></td><td>{s.customerName}</td><td>{formatCurrency(s.sellingPrice,c)}</td><td>{formatCurrency(s.sellingPriceZmw??toZmw(s.sellingPrice,c,s.exchangeRate),"ZMW")}</td><td>{formatCurrency(s.amountPaidZmw??toZmw(s.amountPaid,c,s.exchangeRate),"ZMW")}</td><td>{formatCurrency(s.balanceZmw??toZmw(s.balance,c,s.exchangeRate),"ZMW")}</td><td className={a.profit>=0?"profit":"loss"}>{formatCurrency(a.profit,"ZMW")}</td><td><span className={`badge ${s.status==="Fully Paid"?"available":"awaiting"}`}>{s.status}</span></td><td><div className="row-actions"><Link className="button secondary compact-button" href={`/vehicles/${s.vehicleId}`}><Eye size={14}/>View</Link><button className="button secondary compact-button" type="button" onClick={()=>startEdit(s)}><PenLine size={14}/>Edit</button><Link className="row-action" href={`/vehicles/${s.vehicleId}/edit`} title="Edit vehicle"><PenLine size={16}/></Link></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty"><ShoppingCart size={32}/><h3>No sales found</h3></div>}</div></section>
 <section className="panel sales-summary"><div className="panel-head"><h2>Sales Summary (ZMW)</h2></div><div className="sales-summary-grid">{[["Selling Value",totals.revenue],["Payments Received",totals.paid],["Outstanding",totals.balance],["Gross Profit",totals.profit]].map(([label,value])=><div className="sales-summary-item" key={String(label)}><span>{label}</span><div><small>ZMW</small><b>{formatCurrency(Number(value),"ZMW")}</b></div></div>)}</div></section></div></>;
}
