"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Plus,ShoppingCart,WalletCards} from "lucide-react";
import {loadCustomers,Customer} from "@/lib/customer-store";
import {loadSales,nextSaleId,Sale,saveSales} from "@/lib/sales-store";
import {loadVehicles,saveVehicles} from "@/lib/vehicle-store";
import {Vehicle} from "@/lib/types";
import {Currency,formatCurrency,groupCurrencyAmounts,normalizeCurrency} from "@/lib/currency";
export default function SalesPage(){const [sales,setSales]=useState<Sale[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[show,setShow]=useState(false);useEffect(()=>{setSales(loadSales());setVehicles(loadVehicles());setCustomers(loadCustomers());},[]);const available=useMemo(()=>vehicles.filter(v=>v.status!=="Sold"),[vehicles]);const revenue=groupCurrencyAmounts(sales,s=>s.sellingPrice,s=>s.currency),received=groupCurrencyAmounts(sales,s=>s.amountPaid,s=>s.currency),outstanding=groupCurrencyAmounts(sales,s=>s.balance,s=>s.currency),profit=groupCurrencyAmounts(sales.filter(s=>!s.mixedCurrency),s=>s.profit,s=>s.currency);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const vehicle=vehicles.find(v=>v.id===String(f.get("vehicleId")));const customer=customers.find(c=>c.id===String(f.get("customerId")));if(!vehicle||!customer)return;const sellingPrice=Number(f.get("sellingPrice")),amountPaid=Number(f.get("amountPaid"));if(amountPaid>sellingPrice){alert("Amount paid cannot exceed selling price.");return;}const currency=String(f.get("currency")||"ZMW") as Currency;const vehicleCurrency=normalizeCurrency(vehicle.purchaseCurrency);const mixedCurrency=vehicleCurrency!==currency;const vehicleCost=mixedCurrency?0:vehicle.totalCost;const sale:Sale={id:crypto.randomUUID(),saleId:nextSaleId(sales),vehicleId:vehicle.id,stockId:vehicle.stockId,vehicleName:`${vehicle.make} ${vehicle.model} ${vehicle.year}`,customerId:customer.id,customerName:customer.name,saleDate:String(f.get("saleDate")),sellingPrice,amountPaid,balance:sellingPrice-amountPaid,vehicleCost,profit:mixedCurrency?0:sellingPrice-vehicle.totalCost,currency,mixedCurrency,paymentMethod:String(f.get("paymentMethod")),status:amountPaid===sellingPrice?"Fully Paid":"Partially Paid",createdAt:new Date().toISOString()};const nextSales=[sale,...sales];const nextVehicles=vehicles.map(v=>v.id===vehicle.id?{...v,status:"Sold" as const,currentLocation:"Sold / Delivered"}:v);saveSales(nextSales);saveVehicles(nextVehicles);setSales(nextSales);setVehicles(nextVehicles);setShow(false);e.currentTarget.reset();}
 const Dual=({title,values}:{title:string;values:{ZMW:number;USD:number}})=><div className="card"><div className="metric"><div><div className="metric-label">{title}</div><div className="metric-value small-money">{formatCurrency(values.ZMW,"ZMW")}</div><small className="muted">{formatCurrency(values.USD,"USD")}</small></div></div></div>;
 return <><div className="topbar"><div className="title"><h1>Sales & Payments</h1><p>Record every sale exactly as transacted in ZMW or USD. No automatic conversion is applied.</p></div><button className="button" onClick={()=>setShow(!show)}><Plus size={18}/><span>Record Sale</span></button></div><div className="cards"><Dual title="Sales Revenue" values={revenue}/><Dual title="Payments Received" values={received}/><Dual title="Outstanding" values={outstanding}/><Dual title="Comparable Gross Profit" values={profit}/></div>
 {show&&<form className="form-card" onSubmit={submit}><div className="form-grid"><div className="field"><label>Vehicle</label><select className="select" name="vehicleId" required defaultValue=""><option value="" disabled>Select available vehicle</option>{available.map(v=><option value={v.id} key={v.id}>{v.stockId} — {v.make} {v.model} ({formatCurrency(v.totalCost,normalizeCurrency(v.purchaseCurrency))} cost)</option>)}</select></div><div className="field"><label>Customer</label><select className="select" name="customerId" required defaultValue=""><option value="" disabled>Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.customerId} — {c.name}</option>)}</select></div><div className="field"><label>Sale Currency</label><select className="select" name="currency" defaultValue="ZMW"><option value="ZMW">ZMW</option><option value="USD">USD</option></select></div><div className="field"><label>Selling Price</label><input className="input" type="number" min="0" step="0.01" name="sellingPrice" required/></div><div className="field"><label>Deposit / Amount Paid</label><input className="input" type="number" min="0" step="0.01" name="amountPaid" required/></div><div className="field"><label>Sale Date</label><input className="input" type="date" name="saleDate" required defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="field"><label>Payment Method</label><select className="select" name="paymentMethod"><option>Bank Transfer</option><option>Cash</option><option>Mobile Money</option><option>Card</option></select></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShow(false)}>Cancel</button><button className="button">Complete Sale</button></div></form>}
 <div className="panel" style={{marginTop:18}}><div className="panel-head"><h2>Sales Register</h2><span className="badge sold">{sales.length} sales</span></div><div className="table-wrap"><table><thead><tr><th>Sale ID</th><th>Vehicle</th><th>Customer</th><th>Currency</th><th>Selling Price</th><th>Paid</th><th>Balance</th><th>Profit</th><th>Status</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td><strong>{s.saleId}</strong></td><td>{s.stockId}<br/><small>{s.vehicleName}</small></td><td>{s.customerName}</td><td><b>{normalizeCurrency(s.currency)}</b></td><td>{formatCurrency(s.sellingPrice,normalizeCurrency(s.currency))}</td><td>{formatCurrency(s.amountPaid,normalizeCurrency(s.currency))}</td><td>{formatCurrency(s.balance,normalizeCurrency(s.currency))}</td><td className={s.mixedCurrency?"muted":s.profit>=0?"profit":"loss"}>{s.mixedCurrency?"Mixed currency — review":formatCurrency(s.profit,normalizeCurrency(s.currency))}</td><td><span className={`badge ${s.status==="Fully Paid"?"available":"awaiting"}`}>{s.status}</span></td></tr>)}</tbody></table>{!sales.length&&<div className="empty"><ShoppingCart size={34}/><p>No vehicle sales recorded yet.</p></div>}</div></div></>;
}
