"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {CalendarDays,Calculator,FileCheck2,Plus,ReceiptText,Settings2} from "lucide-react";
import {loadSales} from "@/lib/sales-store";
import {loadVehicleExpenses} from "@/lib/ledger-store";
import {loadVehicles} from "@/lib/vehicle-store";
import {loadTaxReturns,loadTaxSettings,saveTaxReturns,saveTaxSettings,TaxReturn,TaxSetting,TaxType} from "@/lib/tax-store";
import {toZmw} from "@/lib/currency";
const money=(n:number)=>new Intl.NumberFormat("en-ZM",{style:"currency",currency:"ZMW",maximumFractionDigits:2}).format(Number(n||0));
type Tab="summary"|"returns"|"calendar"|"settings";
const types:TaxType[]=["VAT","TOT","Income Tax","PAYE","NAPSA","NHIMA","Withholding Tax","Customs & Import Duty"];
export default function TaxPage(){
 const [settings,setSettings]=useState<TaxSetting[]>([]),[returns,setReturns]=useState<TaxReturn[]>([]),[tab,setTab]=useState<Tab>("summary"),[show,setShow]=useState(false);
 const [sales,setSales]=useState<ReturnType<typeof loadSales>>([]),[vehicles,setVehicles]=useState<ReturnType<typeof loadVehicles>>([]),[expenses,setExpenses]=useState<ReturnType<typeof loadVehicleExpenses>>([]);
 useEffect(()=>{setSettings(loadTaxSettings());setReturns(loadTaxReturns());setSales(loadSales());setVehicles(loadVehicles());setExpenses(loadVehicleExpenses())},[]);
 const figures=useMemo(()=>{
  const revenue=sales.reduce((sum,s)=>sum+Number(s.sellingPriceZmw??toZmw(Number(s.originalSellingPrice??s.sellingPrice),s.currency||"ZMW",s.exchangeRate)),0);
  const soldIds=new Set(sales.map(s=>s.vehicleId));
  const purchaseCost=vehicles.filter(v=>soldIds.has(v.id)).reduce((sum,v)=>sum+Number(v.purchasePriceZmw??toZmw(Number(v.originalPurchasePrice??v.purchasePrice),v.purchaseCurrency||"ZMW",v.purchaseExchangeRate)),0);
  const soldExpenses=expenses.filter(e=>soldIds.has(e.vehicleId)).reduce((sum,e)=>sum+Number(e.amount||0),0);
  return {revenue,cost:purchaseCost+soldExpenses,expense:soldExpenses,profit:revenue-purchaseCost-soldExpenses};
 },[sales,vehicles,expenses]);
 const due=returns.filter(r=>r.status!=="Paid").reduce((s,r)=>s+Number(r.taxDue||0),0);
 function addReturn(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),type=String(f.get("type")) as TaxType,taxable=Number(f.get("taxableAmount")),manual=Number(f.get("taxDue"));const rate=settings.find(x=>x.type===type)?.rate||0;const item:TaxReturn={id:crypto.randomUUID(),type,period:String(f.get("period")),taxableAmount:taxable,taxDue:manual||taxable*rate/100,status:String(f.get("status")) as TaxReturn["status"],dueDate:String(f.get("dueDate")),reference:String(f.get("reference")||""),createdAt:new Date().toISOString()};const next=[item,...returns];saveTaxReturns(next);setReturns(next);setShow(false);e.currentTarget.reset()}
 function updateRate(type:TaxType,rate:number){const next=settings.map(x=>x.type===type?{...x,rate}:x);saveTaxSettings(next);setSettings(next)}
 return <><div className="topbar"><div className="title"><h1>Tax Centre</h1><p>Prepare and retain ZMW tax-return working papers from the accounting records.</p></div><button className="button" onClick={()=>setShow(!show)}><Plus size={18}/><span>New Tax Return</span></button></div>
 <div className="cards"><div className="card metric"><div><div className="metric-label">Sales / Turnover (ZMW)</div><div className="metric-value small-money">{money(figures.revenue)}</div></div><div className="metric-icon"><ReceiptText/></div></div><div className="card metric"><div><div className="metric-label">Estimated Gross Profit (ZMW)</div><div className="metric-value small-money">{money(figures.profit)}</div></div><div className="metric-icon"><Calculator/></div></div><div className="card metric"><div><div className="metric-label">Open Tax Liabilities</div><div className="metric-value small-money">{money(due)}</div></div><div className="metric-icon"><FileCheck2/></div></div><div className="card metric"><div><div className="metric-label">Returns Recorded</div><div className="metric-value">{returns.length}</div></div><div className="metric-icon"><CalendarDays/></div></div></div>
 {show&&<form className="form-card section-gap" onSubmit={addReturn}><h2>Create Tax Return Working Paper</h2><div className="form-grid"><div className="field"><label>Tax Type</label><select className="select" name="type">{types.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Period</label><input className="input" name="period" placeholder="e.g. August 2026" required/></div><div className="field"><label>Taxable Amount (ZMW)</label><input className="input" type="number" min="0" step="0.01" name="taxableAmount" required/></div><div className="field"><label>Tax Due (ZMW, optional override)</label><input className="input" type="number" min="0" step="0.01" name="taxDue"/></div><div className="field"><label>Due Date</label><input className="input" type="date" name="dueDate" required/></div><div className="field"><label>Status</label><select className="select" name="status"><option>Draft</option><option>Ready</option><option>Submitted</option><option>Paid</option></select></div><div className="field full"><label>Submission / Payment Reference</label><input className="input" name="reference"/></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShow(false)}>Cancel</button><button className="button">Save Return</button></div></form>}
 <div className="deal-tabs"><button className={tab==="summary"?"active":""} onClick={()=>setTab("summary")}>Tax Summary</button><button className={tab==="returns"?"active":""} onClick={()=>setTab("returns")}>Returns Register</button><button className={tab==="calendar"?"active":""} onClick={()=>setTab("calendar")}>Tax Calendar</button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}><Settings2 size={16}/>Rates & Settings</button></div>
 {tab==="summary"&&<div className="tax-grid">{types.map(type=>{const setting=settings.find(x=>x.type===type),items=returns.filter(r=>r.type===type),tax=items.reduce((s,r)=>s+Number(r.taxDue||0),0);return <div className="panel tax-card" key={type}><div className="panel-head"><h2>{type}</h2><span className={`badge ${setting?.enabled?"available":"awaiting"}`}>{setting?.enabled?"Enabled":"Not configured"}</span></div><div className="panel-body"><div className="metric-label">Recorded Liability</div><div className="metric-value small-money">{money(tax)}</div><p className="muted">{setting?.notes}</p><div className="row-between"><small>{items.length} return(s)</small><b>{setting?.rate||0}% configured</b></div></div></div>})}</div>}
 {tab==="returns"&&<section className="panel"><div className="panel-head"><h2>Tax Returns Register</h2></div><div className="table-wrap"><table><thead><tr><th>Tax</th><th>Period</th><th>Taxable Amount (ZMW)</th><th>Tax Due (ZMW)</th><th>Due Date</th><th>Status</th><th>Reference</th></tr></thead><tbody>{returns.map(r=><tr key={r.id}><td><b>{r.type}</b></td><td>{r.period}</td><td>{money(r.taxableAmount)}</td><td>{money(r.taxDue)}</td><td>{r.dueDate}</td><td><span className={`badge ${r.status==="Paid"?"available":r.status==="Submitted"?"transit":"awaiting"}`}>{r.status}</span></td><td>{r.reference||"—"}</td></tr>)}</tbody></table>{!returns.length&&<div className="empty">No tax returns recorded yet.</div>}</div></section>}
 {tab==="calendar"&&<section className="panel"><div className="panel-head"><h2>Tax Calendar</h2></div><div className="attention-list">{[...returns].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).map(r=><div className="tax-calendar-row" key={r.id}><div className="attention-icon"><CalendarDays size={18}/></div><div><b>{r.type} · {r.period}</b><small>Due {r.dueDate} · {money(r.taxDue)}</small></div><span className={`badge ${r.status==="Paid"?"available":"awaiting"}`}>{r.status}</span></div>)}{!returns.length&&<div className="empty">Add a return to begin the compliance calendar.</div>}</div></section>}
 {tab==="settings"&&<section className="panel"><div className="panel-head"><h2>Configurable Tax Rates</h2></div><div className="table-wrap"><table><thead><tr><th>Tax Type</th><th>Rate %</th><th>Usage Note</th></tr></thead><tbody>{settings.map(s=><tr key={s.type}><td><b>{s.type}</b></td><td><input className="input tax-rate" type="number" min="0" step="0.01" value={s.rate} onChange={e=>updateRate(s.type,Number(e.target.value))}/></td><td>{s.notes}</td></tr>)}</tbody></table></div><div className="panel-body muted tiny">Rates are configurable working assumptions. Confirm the applicable legislation and taxpayer status before filing.</div></section>}
 </>;
}